import Foundation

/// 知识点有效练习题注入包（120 道）。
///
/// 背景：原有 `CuratedKnowledgeQuestions` 共 211 道人工题，覆盖 113/145 个知识点；
/// 32 个知识点一道真题都没有，73 个知识点只有 1 道，其余题目由 `KnowledgePracticeGenerator`
/// 派生，多为「属于哪个学段 / 该用什么策略」一类的元问题，并不是有效的英语练习。
///
/// 本包按两条分布注入 120 道真实练习（4 选 1，含正确答案与讲解）：
///
/// - Pass A「按知识点分布」：为 32 个零真题知识点各补 2 道，做到均衡覆盖；
/// - Pass B「按重要性分布」：以「学段权重 × 能力权重 + 中考核心考点加成」计算重要度，
///   投给 28 个高重要度考点各 2 道，让重点语法与技能练得更密。
///
/// 题目全部是可判定的英语练习：选词填空、辨错、句型转换、语境选择；
/// 干扰项都是真实但错误的语言形式，不臆造"某年某卷"的真题出处。
enum KnowledgeQuestionInjection {
    /// Pass A · 按知识点分布：补齐 32 个零真题知识点（各 2 道，共 64 道）。
    static let distributionBatch: [KnowledgePracticeQuestion] = [
        q("inj-p-nouns-1", "p-nouns", "I have two ___.",
          ["book", "books", "bookes", "book's"], 1, "可数名词前有 two，需用复数 books。", "选词填空"),
        q("inj-p-nouns-2", "p-nouns", "The plural form of 'child' is ___.",
          ["childs", "childes", "children", "childrens"], 2, "child 的复数是不规则形式 children。", "识别"),
        q("inj-p-have-1", "p-have", "She ___ a new bike.",
          ["have", "having", "has", "haves"], 2, "主语 She 是第三人称单数，用 has。", "选词填空"),
        q("inj-p-have-2", "p-have", "I ___ two brothers.",
          ["has", "am", "having", "have"], 3, "主语 I 用 have，不用 has。", "选词填空"),
        q("inj-p-imperative-1", "p-imperative", "___ the door, please.",
          ["Opens", "Opening", "Opened", "Open"], 3, "祈使句以动词原形开头。", "选词填空"),
        q("inj-p-imperative-2", "p-imperative", "___ be late for school.",
          ["Don't", "Not", "Doesn't", "Isn't"], 0, "否定祈使句用 Don't + 动词原形。", "辨错"),
        q("inj-p-wh-1", "p-wh", "___ are you from? — I'm from China.",
          ["Where", "Who", "When", "Why"], 0, "询问来自哪里用 Where。", "选词填空"),
        q("inj-p-wh-2", "p-wh", "___ is your birthday? — It's in May.",
          ["What", "When", "Where", "How"], 1, "询问时间用 When。", "选词填空"),
        q("inj-p-commands-1", "p-commands", "课堂上老师说 'Stand up, please.'，意思是：",
          ["请坐下", "请起立", "请安静", "请举手"], 1, "Stand up 意为起立。", "理解"),
        q("inj-p-commands-2", "p-commands", "'Listen and repeat.' 让同学做什么？",
          ["抄写单词", "举手回答", "听并跟读", "合上书本"], 2, "listen 听，repeat 跟着重复，即听并跟读。", "理解"),
        q("inj-p-past-basic-1", "p-past-basic", "I ___ TV yesterday evening.",
          ["watch", "watches", "watched", "watching"], 2, "yesterday evening 是过去时间标志，用过去式 watched。", "选词填空"),
        q("inj-p-past-basic-2", "p-past-basic", "She ___ to the park last Sunday.",
          ["go", "goes", "going", "went"], 3, "last Sunday 表过去，go 的过去式是 went。", "选词填空"),
        q("inj-p-syllables-1", "p-syllables", "单词 banana 有几个音节？",
          ["一个", "两个", "四个", "三个"], 3, "ba-na-na 共三个音节。", "理解"),
        q("inj-p-syllables-2", "p-syllables", "下面哪个单词的音节划分是正确的？",
          ["ta-ble", "tab-le", "t-able", "ta-b-le"], 0, "table 划分为 ta-ble。", "识别"),
        q("inj-j1-prep-1", "j1-prep", "We have a maths lesson ___ Monday morning.",
          ["on", "in", "at", "for"], 0, "具体某一天的上午用 on。", "选词填空"),
        q("inj-j1-prep-2", "j1-prep", "The cat is hiding ___ the door.",
          ["between", "behind", "during", "among"], 1, "藏在门后面用 behind。", "选词填空"),
        q("inj-j1-sentence-1", "j1-sentence", "Birds fly. 这个句子属于哪种基本句型？",
          ["主系表", "主谓", "主谓宾", "主谓双宾"], 1, "Birds 是主语，fly 是不及物动词，属主谓结构。", "识别"),
        q("inj-j1-sentence-2", "j1-sentence", "She is kind. 这个句子属于哪种基本句型？",
          ["主谓", "主谓宾", "主系表", "There be"], 2, "is 是系动词，kind 是表语，属主系表结构。", "识别"),
        q("inj-j1-whose-1", "j1-whose", "___ bag is this? — It's Lily's.",
          ["Who", "Which", "Whose", "What"], 2, "询问所属关系用 Whose。", "选词填空"),
        q("inj-j1-whose-2", "j1-whose", "___ do you like better, tea or coffee?",
          ["What", "Whose", "Who", "Which"], 3, "在明确范围内选择用 Which。", "选词填空"),
        q("inj-j1-frequency-count-1", "j1-frequency-count", "I go to the library ___ a week.",
          ["one", "first", "one time", "once"], 3, "once a week 表示每周一次。", "选词填空"),
        q("inj-j1-frequency-count-2", "j1-frequency-count", "— How often does he play football? — ___.",
          ["Twice a week", "For two hours", "Two kilometres", "At seven"], 0, "How often 询问频率，回答用 Twice a week。", "理解"),
        q("inj-j1-indefinite-1", "j1-indefinite", "Is there ___ interesting in today's newspaper?",
          ["anything", "something", "everything", "nothing"], 0, "一般疑问句中通常用 anything。", "选词填空"),
        q("inj-j1-indefinite-2", "j1-indefinite", "Everyone in our class ___ the new teacher.",
          ["like", "likes", "liking", "to like"], 1, "everyone 作主语时谓语用单数 likes。", "辨错"),
        q("inj-j1-ordinal-date-1", "j1-ordinal-date", "We celebrate Teachers' Day on September ___.",
          ["ten", "the tenth", "tenth", "tens"], 1, "日期用序数词，且序数词前加 the，即 September the tenth。", "选词填空"),
        q("inj-j1-ordinal-date-2", "j1-ordinal-date", "下面哪个日期表达是正确的？",
          ["in 2020 May", "at May 2020", "on May 5th, 2020", "May in 2020"], 2, "具体日期前用 on，写作 on May 5th, 2020。", "辨错"),
        q("inj-j1-spelling-rules-1", "j1-spelling-rules", "study 的复数形式是 ___.",
          ["studys", "studyes", "studies", "study"], 2, "以辅音字母 + y 结尾的名词变复数时，变 y 为 i 再加 -es。", "识别"),
        q("inj-j1-spelling-rules-2", "j1-spelling-rules", "watch 的第三人称单数形式是 ___.",
          ["watchs", "watchies", "watching", "watches"], 3, "以 ch 结尾的动词加 -es 构成三单。", "识别"),
        q("inj-j1-there-transform-1", "j1-there-transform", "There is a pen on the desk. 改为否定句：",
          ["There not is a pen on the desk.", "There is no a pen on the desk.", "There doesn't a pen on the desk.", "There isn't a pen on the desk."], 3, "There be 句型的否定在 be 后加 not。", "句型转换"),
        q("inj-j1-there-transform-2", "j1-there-transform", "There are some books here. 改为一般疑问句：",
          ["Are there any books here?", "Are there some books here?", "Is there any books here?", "There are books here?"], 0, "疑问句把 be 提前，同时 some 改为 any。", "句型转换"),
        q("inj-j2-reading-1", "j2-reading", "在 'Tom lost his key. He looked for it everywhere.' 中，it 指代：",
          ["the key", "Tom", "everywhere", "the door"], 0, "it 指代前句出现的 key。", "理解"),
        q("inj-j2-reading-2", "j2-reading", "句首的 however 通常表示：",
          ["同一意思的重复", "语义转折", "列举步骤", "提出问题"], 1, "however 是转折词，提示与预期相反。", "理解"),
        q("inj-j2-passages-1", "j2-passages", "概括段落主旨时，最应关注：",
          ["最长的单词", "首句和尾句", "标点符号", "段落行数"], 1, "段落主旨常出现在首句或尾句。", "理解"),
        q("inj-j2-passages-2", "j2-passages", "一段话主要讲 'how students save water at school'，其主旨是：",
          ["教学楼的样子", "学生的爱好", "节约用水", "假期计划"], 2, "段落围绕节水展开，主旨是节约用水。", "理解"),
        q("inj-j2-adjectives-1", "j2-adjectives", "This is ___ book I have ever read.",
          ["most interesting", "more interesting", "the most interesting", "interesting"], 2, "三者以上比较且修饰名词，用最高级 the most interesting。", "选词填空"),
        q("inj-j2-adjectives-2", "j2-adjectives", "He runs ___ than his brother.",
          ["fast", "fastest", "more fast", "faster"], 3, "than 前用比较级，fast 的比较级是 faster。", "选词填空"),
        q("inj-j2-object-1", "j2-object", "下面哪句是正确的？",
          ["She gave a gift me.", "She gave to me a gift.", "She gave me gift.", "She gave me a gift."], 3, "give sb sth 是双宾语结构：She gave me a gift.。", "辨错"),
        q("inj-j2-object-2", "j2-object", "'She showed the picture to me.' 可以改写为：",
          ["She showed me the picture.", "She showed me to the picture.", "She showed the picture me.", "She showed to me picture."], 0, "show sth to sb 可改为 show sb sth。", "句型转换"),
        q("inj-j2-articles-1", "j2-articles", "We play ___ basketball after school.",
          ["无需冠词", "a", "an", "the"], 0, "球类运动名称前不加冠词。", "选词填空"),
        q("inj-j2-articles-2", "j2-articles", "I have ___ breakfast at seven.",
          ["a", "无需冠词", "an", "the"], 1, "三餐名称前不加冠词。", "选词填空"),
        q("inj-j2-future-plan-1", "j2-future-plan", "We ___ visit Beijing next week.",
          ["is going to", "are going to", "going to", "go to"], 1, "主语 We 与 are going to 搭配，表示计划。", "选词填空"),
        q("inj-j2-future-plan-2", "j2-future-plan", "Look at the dark clouds! It ___ rain.",
          ["was going to", "goes to", "is going to", "went to"], 2, "已有迹象预示将要下雨，用 is going to。", "理解"),
        q("inj-j2-question-tags-1", "j2-question-tags", "It is cold today, ___?",
          ["is it", "does it", "isn't it", "doesn't it"], 2, "前肯后否，系动词 is 的附加问句用 isn't it。", "选词填空"),
        q("inj-j2-question-tags-2", "j2-question-tags", "You don't like coffee, ___?",
          ["don't you", "are you", "aren't you", "do you"], 3, "前否后肯，助动词用 do you。", "选词填空"),
        q("inj-j2-direct-speech-1", "j2-direct-speech", "下面哪句标点使用正确？",
          ["He said “I am ready”.", "He said, “I am ready”.", "He said: “I am ready”", "He said, “I am ready.”"], 3, "说话人后用逗号，引号内句子以句号结尾且放在引号内。", "辨错"),
        q("inj-j2-direct-speech-2", "j2-direct-speech", "Tom said, “I like music.” 引号中的内容表示：",
          ["Tom 的原话", "作者的观点", "一条规则", "一个问题"], 0, "直接引语引用说话人的原话。", "理解"),
        q("inj-j2-exclamation-1", "j2-exclamation", "___ beautiful the city is!",
          ["How", "What", "What a", "How a"], 0, "How 修饰形容词 beautiful，构成感叹句。", "选词填空"),
        q("inj-j2-exclamation-2", "j2-exclamation", "___ a clever boy he is!",
          ["How", "What", "What an", "How an"], 1, "中心词是单数可数名词 boy，用 What a。", "选词填空"),
        q("inj-j3-speech-1", "j3-speech", "听到 'Could you tell me the way to the station?'，最可能是哪种场景？",
          ["购物", "问路", "打电话", "天气预报"], 1, "the way to the station 表明是在问路。", "理解"),
        q("inj-j3-speech-2", "j3-speech", "'May I take your order?' 最可能出现在：",
          ["图书馆", "医院", "餐厅", "银行"], 2, "take your order 是餐厅点餐用语。", "理解"),
        q("inj-j3-listening-inference-1", "j3-listening-inference", "女士说：'I've been waiting here for an hour.' 她的意思最可能是：",
          ["她刚到", "她喜欢等待", "她对等待感到不满", "她提前了一小时"], 2, "等了一小时通常表达抱怨或不满。", "理解"),
        q("inj-j3-listening-inference-2", "j3-listening-inference", "男士说：'Would you mind closing the window?' 他想让对方：",
          ["打开窗户", "离开房间", "买一扇窗", "关上窗户"], 3, "Would you mind doing 是委婉请求对方做某事。", "理解"),
        q("inj-j3-ellipsis-1", "j3-ellipsis", "I like tea and so ___ she.",
          ["is", "do", "has", "does"], 3, "so + 助动词 + 主语表同样如此，主语 she 为三单用 does。", "选词填空"),
        q("inj-j3-ellipsis-2", "j3-ellipsis", "— I didn't pass the test. — ___.",
          ["Neither did I", "So did I", "So I did", "Neither I did"], 0, "表示“我也没通过”用 Neither did I。", "语境选择"),
        q("inj-j3-subjunctive-1", "j3-subjunctive", "I wish I ___ fly like a bird.",
          ["could", "can", "am", "will"], 0, "wish 后的愿望用虚拟语气，与现在事实相反用 could。", "选词填空"),
        q("inj-j3-subjunctive-2", "j3-subjunctive", "I wish I ___ more time to practise.",
          ["have", "had", "will have", "am having"], 1, "wish 后表与现在相反的愿望，用过去式 had。", "选词填空"),
        q("inj-j3-indirect-1", "j3-indirect", "She asked where I ___.",
          ["live", "lived", "will live", "am living"], 1, "主句是过去时，宾语从句时态相应用过去式 lived。", "选词填空"),
        q("inj-j3-indirect-2", "j3-indirect", "He asked me if I ___ the film before.",
          ["see", "saw", "had seen", "have seen"], 2, "转述过去之前的动作，用过去完成时 had seen。", "辨错"),
        q("inj-j3-inversion-1", "j3-inversion", "It was Tom ___ helped me yesterday.",
          ["which", "whom", "who", "whose"], 2, "强调句中被强调的是人，连接词用 who（或 that）。", "选词填空"),
        q("inj-j3-inversion-2", "j3-inversion", "Only then ___ the importance of teamwork.",
          ["I realized", "I did realize", "realized I", "did I realize"], 3, "Only + 状语置于句首时，主句部分倒装，用 did I realize。", "辨错"),
        q("inj-j3-argument-1", "j3-argument", "在短篇议论中，提出观点之后应当：",
          ["罗列无关的事实", "重复标题", "讲个笑话", "给出理由和例子"], 3, "观点需要理由和例证支撑。", "理解"),
        q("inj-j3-argument-2", "j3-argument", "下面哪句是在引出理由？",
          ["There are two reasons for this.", "Once upon a time...", "See you tomorrow.", "Turn left at the corner."], 0, "There are two reasons 明确引出理由。", "理解"),
        q("inj-j3-writing-1", "j3-writing", "一篇短文的开头句通常用来：",
          ["引出话题", "给出最后的细节", "罗列全部事实", "结束故事"], 0, "首句一般用来引出话题、点明主题。", "理解"),
        q("inj-j3-writing-2", "j3-writing", "哪个词最适合引出短文的最后一部分？",
          ["First", "Finally", "Also", "Next"], 1, "Finally 用于引出结尾部分。", "理解"),
    ]

    /// Pass B · 按重要性分布：中考核心考点加权（28 个考点各 2 道，共 56 道）。
    static let importanceBatch: [KnowledgePracticeQuestion] = [
        q("inj-j2-comparative-1", "j2-comparative", "This box is ___ than that one.",
          ["heavy", "heavier", "heaviest", "more heavy"], 1, "than 前用比较级，heavy 变 heavier。", "选词填空"),
        q("inj-j2-comparative-2", "j2-comparative", "My sister is two years ___ than me.",
          ["old", "oldest", "older", "more old"], 2, "两者比较用比较级 older。", "选词填空"),
        q("inj-j2-superlative-1", "j2-superlative", "He is ___ student in our class.",
          ["tall", "taller", "the tallest", "tallest"], 2, "在一定范围内比较用最高级，且前面加 the。", "选词填空"),
        q("inj-j2-superlative-2", "j2-superlative", "This is ___ film I have ever seen.",
          ["good", "better", "best", "the best"], 3, "“我看过的最好的”用最高级 the best。", "选词填空"),
        q("inj-j2-future-1", "j2-future", "I ___ my grandparents this weekend.",
          ["will visit", "visit", "visited", "was visiting"], 0, "this weekend 表将来，用 will visit。", "选词填空"),
        q("inj-j2-future-2", "j2-future", "There ___ a sports meeting next Friday.",
          ["is", "will be", "was", "has been"], 1, "next Friday 表将来，There be 用 will be。", "选词填空"),
        q("inj-j2-modal-1", "j2-modal", "You ___ talk loudly in the library.",
          ["needn't", "mustn't", "might", "could"], 1, "图书馆禁止大声说话，用 mustn't。", "选词填空"),
        q("inj-j2-modal-2", "j2-modal", "___ you swim? — Yes, I can.",
          ["Must", "Should", "Can", "Need"], 2, "询问能力用 Can。", "选词填空"),
        q("inj-j2-verb-forms-1", "j2-verb-forms", "buy 的过去式是 ___.",
          ["buyed", "boughted", "bought", "buying"], 2, "buy 的过去式是不规则形式 bought。", "识别"),
        q("inj-j2-verb-forms-2", "j2-verb-forms", "see 的过去分词是 ___.",
          ["saw", "seed", "seeing", "seen"], 3, "see 的过去分词是 seen。", "识别"),
        q("inj-j2-present-perfect-basic-1", "j2-present-perfect-basic", "She ___ just finished her homework.",
          ["have", "has", "is", "was"], 1, "主语 She 是第三人称单数，用 has finished。", "选词填空"),
        q("inj-j2-present-perfect-basic-2", "j2-present-perfect-basic", "I ___ never been to Shanghai.",
          ["has", "am", "have", "was"], 2, "主语 I 用 have，构成 have been to。", "选词填空"),
        q("inj-j2-used-to-1", "j2-used-to", "He ___ get up late, but now he gets up early.",
          ["used to", "uses to", "is used to", "use to"], 0, "used to do 表示过去经常而现在不再。", "选词填空"),
        q("inj-j2-used-to-2", "j2-used-to", "There ___ be a small shop here.",
          ["uses to", "used to", "is used to", "use"], 1, "There used to be 表示过去曾有。", "选词填空"),
        q("inj-j1-present-cont-1", "j1-present-cont", "Look! The boys ___ basketball.",
          ["are playing", "play", "plays", "played"], 0, "Look 提示此刻正在发生，用现在进行时 are playing。", "选词填空"),
        q("inj-j1-present-cont-2", "j1-present-cont", "Listen! Somebody ___ the piano.",
          ["plays", "is playing", "played", "has played"], 1, "Listen 提示正在进行的动作，用 is playing。", "选词填空"),
        q("inj-j1-past-1", "j1-past", "They ___ to the zoo last Saturday.",
          ["go", "went", "goes", "are going"], 1, "last Saturday 表过去，go 用过去式 went。", "选词填空"),
        q("inj-j1-past-2", "j1-past", "— What did you do yesterday? — I ___ my room.",
          ["clean", "cleans", "cleaned", "am cleaning"], 2, "问句用 did，答句用过去式 cleaned。", "选词填空"),
        q("inj-j1-subject-1", "j1-subject", "My brother ___ football very much.",
          ["like", "liking", "to like", "likes"], 3, "主语 My brother 是第三人称单数，用 likes。", "选词填空"),
        q("inj-j1-subject-2", "j1-subject", "The children ___ playing games now.",
          ["are", "is", "am", "be"], 0, "复数主语 The children 与 are 搭配。", "选词填空"),
        q("inj-j3-tag-1", "j3-tag", "She is your sister, ___?",
          ["is she", "does she", "doesn't she", "isn't she"], 3, "前肯后否，系动词 is 的附加问句为 isn't she。", "选词填空"),
        q("inj-j3-tag-2", "j3-tag", "They didn't go home, ___?",
          ["did they", "didn't they", "do they", "don't they"], 0, "前否后肯，助动词用 did they。", "选词填空"),
        q("inj-j3-tenses-review-1", "j3-tenses-review", "Look! The children ___ football on the playground.",
          ["play", "are playing", "played", "have played"], 1, "Look 提示现在正在进行的动作，用 are playing。", "选词填空"),
        q("inj-j3-tenses-review-2", "j3-tenses-review", "My father ___ to work by bus every day.",
          ["go", "went", "goes", "is going"], 2, "every day 表习惯，主语三单用 goes。", "选词填空"),
        q("inj-j3-conjunctions-1", "j3-conjunctions", "I will call you ___ I arrive in Beijing.",
          ["when", "because", "although", "unless"], 0, "when 引导时间状语从句，表“当……时”。", "选词填空"),
        q("inj-j3-conjunctions-2", "j3-conjunctions", "We stayed at home ___ it was raining.",
          ["so", "because", "but", "or"], 1, "下雨是待在家的原因，用 because。", "选词填空"),
        q("inj-j3-perfect-1", "j3-perfect", "We ___ each other for ten years.",
          ["know", "have known", "knew", "are knowing"], 1, "for ten years 表持续到现在，用现在完成时 have known。", "选词填空"),
        q("inj-j3-perfect-2", "j3-perfect", "— Have you ever ___ to the Great Wall? — Yes, twice.",
          ["go", "went", "been", "being"], 2, "have been to 表示“去过某地”。", "选词填空"),
        q("inj-j3-perfect-continuity-1", "j3-perfect-continuity", "He has ___ in Beijing for five years.",
          ["lived", "come", "gone", "arrived"], 0, "for five years 需与延续性动词 lived 搭配。", "选词填空"),
        q("inj-j3-perfect-continuity-2", "j3-perfect-continuity", "I have kept this book ___ two weeks.",
          ["since", "for", "from", "in"], 1, "一段时间 two weeks 前用 for。", "选词填空"),
        q("inj-j3-passive-1", "j3-passive", "The song ___ by many young people now.",
          ["loves", "loved", "is loving", "is loved"], 3, "歌是被人喜爱的，用被动语态 is loved。", "选词填空"),
        q("inj-j3-passive-2", "j3-passive", "These photos ___ in Beijing last summer.",
          ["were taken", "take", "took", "are taken"], 0, "照片是被拍的，且 last summer 表过去，用 were taken。", "选词填空"),
        q("inj-j3-passive-tenses-1", "j3-passive-tenses", "A new library ___ in our school next year.",
          ["builds", "will be built", "will build", "is building"], 1, "图书馆是被建造，且 next year 表将来，用 will be built。", "选词填空"),
        q("inj-j3-passive-tenses-2", "j3-passive-tenses", "The homework ___ by the students yesterday.",
          ["finished", "is finished", "was finished", "finishes"], 2, "作业是被完成的，且 yesterday 表过去，用 was finished。", "选词填空"),
        q("inj-j3-modal-passive-1", "j3-modal-passive", "Waste paper must ___ into the right bin.",
          ["put", "be putting", "putting", "be put"], 3, "情态动词被动结构为 must be done。", "选词填空"),
        q("inj-j3-modal-passive-2", "j3-modal-passive", "The work can ___ in two days.",
          ["be finished", "finish", "finished", "finishing"], 0, "工作是被完成，情态动词后接 be finished。", "选词填空"),
        q("inj-j3-object-clause-1", "j3-object-clause", "I think ___ he is right.",
          ["what", "which", "who", "that"], 3, "宾语从句是陈述句，用 that 引导。", "选词填空"),
        q("inj-j3-object-clause-2", "j3-object-clause", "She wants to know ___ you like the gift.",
          ["if", "that", "what", "which"], 0, "表示“是否”用 if（或 whether）。", "选词填空"),
        q("inj-j3-object-order-1", "j3-object-order", "Could you tell me how ___?",
          ["can I get there", "do I get there", "I can get there", "I get there can"], 2, "宾语从句用陈述语序：how I can get there。", "辨错"),
        q("inj-j3-object-order-2", "j3-object-order", "I don't know what ___.",
          ["does he want", "he want", "wants he", "he wants"], 3, "宾语从句用陈述语序且谓语与主语一致：what he wants。", "辨错"),
        q("inj-j3-relative-1", "j3-relative", "The man ___ is talking to Tom is my uncle.",
          ["who", "which", "whom", "what"], 0, "先行词 man 指人且在从句中作主语，用 who。", "选词填空"),
        q("inj-j3-relative-2", "j3-relative", "This is the house ___ we lived in last year.",
          ["who", "that", "whose", "what"], 1, "先行词 house 指物，关系词作介词 in 的宾语，用 that/which。", "选词填空"),
        q("inj-j3-relative-choice-1", "j3-relative-choice", "I still remember the day ___ we first met.",
          ["which", "when", "who", "whose"], 1, "先行词 day 表时间，用关系副词 when。", "选词填空"),
        q("inj-j3-relative-choice-2", "j3-relative-choice", "This is the pen ___ he is looking for.",
          ["who", "what", "which", "whose"], 2, "先行词 pen 指物，用 which（或 that）。", "选词填空"),
        q("inj-j3-adverbial-1", "j3-adverbial", "___ I was walking home, it began to rain.",
          ["Because of", "While", "Despite", "During"], 1, "While 引导时间状语从句，后接句子。", "选词填空"),
        q("inj-j3-adverbial-2", "j3-adverbial", "___ it was raining hard, they went on working.",
          ["Because", "So", "Although", "If"], 2, "前后为让步关系，用 Although。", "选词填空"),
        q("inj-j3-conditional-review-1", "j3-conditional-review", "You will fail the exam ___ you work harder.",
          ["if", "because", "unless", "so"], 2, "unless 相当于 if not，表示“除非”。", "选词填空"),
        q("inj-j3-conditional-review-2", "j3-conditional-review", "Study hard, ___ you will make progress.",
          ["or", "but", "so", "and"], 3, "祈使句 + and + 结果，表示“这样做就会……”。", "选词填空"),
        q("inj-j3-nonfinite-1", "j3-nonfinite", "It's important for us ___ English well.",
          ["to learn", "learn", "learning", "learned"], 0, "It is + adj + for sb + to do 结构中用不定式。", "选词填空"),
        q("inj-j3-nonfinite-2", "j3-nonfinite", "The girl ___ in a red dress is my sister.",
          ["stand", "standing", "stands", "stood"], 1, "standing 作后置定语，表示主动进行。", "选词填空"),
        q("inj-j3-cloze-1", "j3-cloze", "He studied very hard; ___, he passed the exam.",
          ["however", "therefore", "instead", "although"], 1, "努力学习是原因，通过考试是结果，用 therefore。", "语境选择"),
        q("inj-j3-cloze-2", "j3-cloze", "The bag looks old. ___, it is still very useful.",
          ["Therefore", "Besides", "However", "So"], 2, "前后形成转折，用 However。", "语境选择"),
        q("inj-j3-reading-types-1", "j3-reading-types", "下面哪个问题属于细节题？",
          ["What is the main idea of the passage?", "What does 'it' refer to?", "Why did the writer write it?", "What time did the meeting start?"], 3, "询问具体时间属于细节定位题。", "理解"),
        q("inj-j3-reading-types-2", "j3-reading-types", "题目问 'What does the underlined word mean?' 属于哪种题型？",
          ["词义猜测", "主旨归纳", "推理判断", "细节定位"], 0, "询问画线词含义属于词义猜测题。", "理解"),
        q("inj-j3-word-building-1", "j3-word-building", "possible 的反义词是 ___.",
          ["unpossible", "dispossible", "inpossible", "impossible"], 3, "否定的形容词常用前缀 im-，即 impossible。", "识别"),
        q("inj-j3-word-building-2", "j3-word-building", "use 加上后缀 -ful 构成 ___.",
          ["useful", "useing", "used", "using"], 0, "use + ful 构成形容词 useful。", "识别"),
    ]

    static let all: [KnowledgePracticeQuestion] = distributionBatch + importanceBatch

    private static func q(_ id: String, _ point: String, _ prompt: String,
                          _ options: [String], _ answer: Int,
                          _ explanation: String, _ kind: String) -> KnowledgePracticeQuestion {
        KnowledgePracticeQuestion(id: id, knowledgePointID: point, prompt: prompt,
                                  options: options, answer: answer,
                                  explanation: explanation, kind: kind)
    }
}
