import Foundation

/// 知识点有效练习题·第三轮注入包（145 道）——「英语学习方法」专项。
///
/// 前两轮解决的是「有没有题」和「够不够练」；这一轮解决的是**「会不会学」**：
/// 为 145 个知识点各配 1 道方法题，把英语学科的学习方法落到真实的语言点上。
///
/// 8 个方法（见 `StudyMethod`）：
/// - `timeMarker` 时间标志法 → 时态类知识点
/// - `chunk` 语块记忆法 → 词汇类知识点
/// - `backbone` 主干手术法 → 句子语序与结构类知识点
/// - `evidence` 原文取证法 → 阅读取证类知识点
/// - `scene` 场景预测法 → 听力类知识点
/// - `skeleton` 骨架替换法 → 表达与写作类知识点
/// - `contrast` 对比归类法 → 易混辨析类知识点（some/any、few/little、who/which…）
/// - `spacing` 间隔复盘法 → 每个知识点通用的复习动作
///
/// 出题口径：
/// 1. 每题题干显式标注所用方法（如「【时间标志法】」），学生会反复看到方法名；
/// 2. 选项不是「元问题」式的学段/归属判断，而是**具体到该知识点的操作或语言形式**，
///    例如“先圈出 last Sunday 再定一般过去时”对“先猜一个读起来顺的”；
/// 3. 讲解必须给出方法的步骤编号与该知识点的判据，学生看完能自己复述四步；
/// 4. 干扰项是学生真实会犯的错（凭语感、逐词硬翻、背答案顺序、只看词汇重复）。
///
/// 与前两轮的关系：`CuratedKnowledgeQuestions.all` = 核心题 + 一轮 + 二轮 + 本轮，
/// 知识点练习会优先取人工题，因此方法题会出现在每个知识点练习的前面。
enum KnowledgeQuestionInjection3 {

    /// 小学批次（33 道）。
    static let primaryBatch: [KnowledgePracticeQuestion] = [
        q("inj3-p-can", "p-can", "【骨架替换法】要表达“我会游泳”，骨架是“主语 + can + 动词原形”。骨架替换法的第一步是什么？",
          ["先把 swim 的各种形式都背一遍，再想句子", "先写中文“我会游泳”，再一个词一个词翻译", "先追求句子长度，尽量多加几个形容词", "先定骨架“主语 + can + 动词原形”，再往骨架里填内容词"], 3, "骨架替换法第 1 步：定骨架。can 后面永远接动词原形；骨架定好后只替换主语和动词：I can swim. / She can draw. 换内容不换结构。", "方法"),
        q("inj3-p-food", "p-food", "【骨架替换法】点餐时说“我想要一些面条”，第一步该做什么？",
          ["先把菜单上所有食物的英文列一遍", "先背“面条”的十种说法", "先定骨架“主语 + would like + 食物”，再把 some noodles 填进去", "先写长句，加满形容词和从句"], 2, "骨架是 I'd like + 食物，这是礼貌点餐的固定结构；把食物换掉就是新句子：I'd like some rice. 结构不变，只换内容词。", "方法"),
        q("inj3-p-hobbies", "p-hobbies", "【骨架替换法】把 I can draw. 改成“我会弹钢琴”，应该怎么做？",
          ["保留骨架 I can + 动词，只把 draw 换成 play the piano", "把整句抄写十遍再默写", "把 can 换成十个不同的情态动词各写一句，不看语境", "重新想一个完全不同的句型"], 0, "骨架不变、只换内容词：I can draw. → I can play the piano. 这是最快的迁移方式；替换后要检查新动词是否需要加冠词或介词。", "迁移"),
        q("inj3-p-like", "p-like", "【骨架替换法】把 I like apples. 改成“我喜欢打篮球”，第 3 步做什么？",
          ["把 like 改成 likes，因为篮球是复数", "把句子改成疑问句再改回来", "先把喜欢的十种东西都写出来", "替换内容词：把 apples 换成 playing basketball，骨架 I like + 名词或动名词 不动"], 3, "第 3 步是替换内容词。like 后接名词或动名词：I like playing basketball. 骨架保持 I like + …，只换后面的内容。", "方法"),
        q("inj3-p-polite", "p-polite", "【骨架替换法】进门前想表达“我可以进来吗？”，第一步做什么？",
          ["先写中文，再逐词翻译成英语", "先定礼貌请求骨架：May I + 动词原形 + …?", "先背 may 的全部中文意思", "先把句子写成陈述句 I come in."], 1, "礼貌请求的骨架是 May I / Could I + 动词原形？定好骨架再填内容：May I come in? 换成 sit here 就是新请求，结构完全一致。", "方法"),
        q("inj3-p-routines", "p-routines", "【骨架替换法】把 I go to bed at nine. 改成“我七点起床”，应该怎么做？",
          ["把整句改成进行时，因为起床是正在发生", "把 at 换成 in，因为七点是时间点", "重新写一个和作息无关的句子", "保留骨架“主语 + 动词 + at + 时间”，把 go to bed 换成 get up、nine 换成 seven"], 3, "骨架是 I + 动词 + at + 时间。替换动作和时间即可：I get up at seven. 注意 at 用于具体时刻，不能换成 in。", "迁移"),
        q("inj3-p-weather", "p-weather", "【骨架替换法】用 What is the weather like? 追问“今天热吗”，第 4 步做什么？",
          ["把 weather 换成 seasons，因为问的是天气", "加细节和语气：在骨架上补 today、形容词或附加问句，再检查标点与首字母大小写", "把 What 换成 Where，因为要知道地点", "把整个句子拆成三个短句"], 1, "第 4 步是加细节。骨架 What is the weather like? 保持不动，可补 today、加 is it hot? 或把天气描述接在后面，最后检查问号和首字母大写。", "检查"),
        q("inj3-p-blends", "p-blends", "【场景预测法】听辨 blue / street 这类词首辅音连缀，第一步做什么？",
          ["先把 bl、cl、st、tr 全部抄写十遍再看题", "先看题目给的是单词还是句子，预判会听到含 bl、cl、st、tr 的词", "先猜答案，再决定要不要听", "只听第一个音，后面的音不用管"], 1, "场景预测法第 1 步：先看题目和选项，预判要听什么。确定为辨辅音连缀后，听时只抓词首的辅音组合（bl-ue / str-eet），不必听清每个字母。", "方法"),
        q("inj3-p-commands", "p-commands", "【场景预测法】听 Stand up and open your books. 抓关键动作，第一步做什么？",
          ["先看选项里出现的动作词（stand / open / listen / repeat），预判会听到哪几个", "先把每个动词的过去式都写出来", "先猜老师会不会用中文再说一遍", "先听最后一个词，因为指令在句尾"], 0, "第 1 步是先看选项、猜场景。见到 stand、open 这类动作词，就知道要抓“动词 + 宾语”；听时按动作出现的顺序记，而不是逐词听。", "方法"),
        q("inj3-p-phonics", "p-phonics", "【场景预测法】题目要求判断 sh / ch / th 的发音，第一步做什么？",
          ["先把 26 个字母按顺序背一遍", "先把所有带 h 的单词写出来", "先听整句，抓人物和数字", "先看选项里的字母组合，预判每个组合的可能读音，再听辨"], 3, "第 1 步是按题目预判。看到 sh / ch / th，就准备好两组读音（/ʃ/、/tʃ/、/θ/ 或 /ð/），听时只关心首音，不被无关信息分散注意力。", "方法"),
        q("inj3-p-school", "p-school", "【场景预测法】听“我们周一有英语课”，第一步做什么？",
          ["先看选项，预判要听的是科目、时间还是地点", "先把所有科目名抄一遍", "先听数字，抓住 week 这个词", "先猜说话人是谁，再决定听不听"], 0, "第 1 步看选项定场景。若选项里 Monday、English、classroom 混排，就同时准备抓“科目词 + 星期词”，听时把这两类词配对。", "方法"),
        q("inj3-p-silent-e", "p-silent-e", "【场景预测法】要判断 cap 和 cape 的元音读音，第一步做什么？",
          ["先看给出的词对，预判要辨的是同一词根在闭音节与开音节下的短音和长音", "先把 cap 和 cape 各抄写二十遍", "先听句子里的数字", "先猜哪一个是答案，再听录音验证"], 0, "第 1 步是按题目预判。cap / cape 只差一个 e：闭音节 cap 读短音，开音节 cape 读长音。带着这组对照去听，比逐词辨认快得多。", "方法"),
        q("inj3-p-syllables", "p-syllables", "【场景预测法】要判断 “ba-NA-na” 的重音位置，第一步做什么？",
          ["先把单词按字母数分组", "先把单词的中文意思写出来", "先看题目要给的是音节数还是重音位置，预判要听“几个音节、哪个最响”", "先听最后一个音节，因为重音常在末尾"], 2, "第 1 步是先明确听什么。判断重音只听“哪个音节更响更长”，不用管每个字母；听到 ba-NA-na 中间最响，就记重音在第 2 个音节。", "方法"),
        q("inj3-p-wh", "p-wh", "【对比归类法】把 who / where / when / why 放一起对比，第 2 步列什么条件？",
          ["把五个词的字母数排个序", "把每个词的音标都抄一遍", "按出现频率高低排序", "列提问对象条件：问人、问地点、问时间、问原因、问方式"], 3, "对比归类法第 2 步是列条件。who 问人、where 问地点、when 问时间、why 问原因、how 问方式。条件列清，选择题里出现哪个疑问词都能直接判断。", "辨析"),
        q("inj3-p-past-basic", "p-past-basic", "【时间标志法】句子 I ___ TV yesterday. 要填入正确形式，第一步做什么？",
          ["先看选项里哪项最长，凭语感挑一个", "先圈出 yesterday 这个过去时间标志，确定用一般过去时", "先把 watch 的中文意思写出来再猜形式", "先数句子有几个词，判断是不是长句"], 1, "时间标志法第 1 步：圈时间标志。yesterday / last week / ago 都是过去时信号；确定时态后再处理动词：watch → watched。", "方法"),
        q("inj3-p-present", "p-present", "【时间标志法】句子 He ___ to school every day. 填空，第一步做什么？",
          ["先把 go 的过去式 went 填进去试试", "先圈出 every day，确定用一般现在时，再看主语 He 是第三人称单数", "先看句子长度决定用不用三单", "先猜一个答案，回头再改"], 1, "第 1 步圈标志：every day 是一般现在时信号。第 2 步把标志翻成时间（经常）。第 3 步核对主语 He → 第三人称单数 → 用 goes。", "方法"),
        q("inj3-p-present-progress", "p-present-progress", "【时间标志法】句子 They ___ (play) football now. 填空，第一步做什么？",
          ["先把 play 的各种形式列出来", "先翻译整句中文，再逐词替换", "先看主语是复数，直接把 play 填进去", "先圈出 now，确定用现在进行时，再写 are playing"], 3, "now / Look! / Listen! 是现在进行时的标志。第 3 步核对主语 They 用 are；动词用 -ing 形式 playing。三步都不能跳。", "方法"),
        q("inj3-p-body", "p-body", "【语块记忆法】学 My head hurts. 这句，第一步做什么？",
          ["把 head 抄写二十遍，先记住拼写", "把身体部位的词按字母表顺序背一遍", "先把 hurts 的三态变化背下来", "先记词块 my head hurts（身体部位 + 动词），而不是把 head 单独背下来"], 3, "语块记忆法第 1 至第 2 步：先写词性和核心义，再记固定搭配。身体部位的用法是“部位 + hurt(s)/ache(s)”，连句式一起记，用起来才不会写成 My head is pain。", "方法"),
        q("inj3-p-colors", "p-colors", "【语块记忆法】记 The bag is blue. 里的颜色词，第 3 步做什么？",
          ["把十种颜色的中文意思全背下来", "把 blue 的复数形式写出来", "配一个自己能用的例句，把 bag 换成自己的文具", "把颜色词按首字母排序抄写"], 2, "第 3 步是造自己的例句。记颜色不能只记中文，要放进“物品 + is + 颜色”的描述句里。My pen is black. 这样下次描述东西就能直接用。", "方法"),
        q("inj3-p-family", "p-family", "【语块记忆法】学 My aunt is a doctor. 这句，第 2 步做什么？",
          ["把家庭成员的中文称呼列成表背下来", "只记 doctor 的复数 doctors", "把 aunt 拆成字母逐个背", "记搭配：职业名称前用 a/an，aunt 与 uncle、nephew 成组一起记"], 3, "第 2 步记搭配和词性。家人称呼常与“职业 + a/an”一起出现；成组记才记得牢：uncle / aunt、brother / sister、doctor / nurse。", "方法"),
        q("inj3-p-have", "p-have", "【对比归类法】把 have / has 放一起对比，第 2 步列什么条件？",
          ["比较 have 和 has 哪个字母多", "列主语人称条件：I/you/we/they 用 have，he/she/it 用 has", "把 have 的所有中文意思列出来", "统计它们在课文里各出现多少次"], 1, "对比归类法靠条件分界。have / has 的分界条件是主语：第三人称单数用 has，其余用 have。条件写清楚，题目一看就选得出来。", "辨析"),
        q("inj3-p-nouns", "p-nouns", "【对比归类法】对比 book/books 和 child/children，第 2 步列什么条件？",
          ["列“规则与不规则”的差别：一般加 -s 或 -es，特殊词要单独记（child → children）", "比较两组单词的长度", "把 book 和 child 的音标抄一遍", "按在课本里出现的先后顺序排列"], 0, "对比归类法只看“分界条件”。复数分界在规则变化与不规则变化：规则加 -s/-es，不规则单独记。分开列，考试时先判断属于哪一类。", "辨析"),
        q("inj3-p-numbers", "p-numbers", "【对比归类法】把 three 和 third 放一起对比，第 2 步列什么条件？",
          ["比较两个词的读音长短", "列用途条件：基数词表数量，序数词表顺序和日期", "把 1 到 20 的英文全写一遍", "把两个词的中文意思都记成“三”"], 1, "分界条件是用途：数量用 three books，顺序用 the third day。只记中文“三”会混淆；列出用途条件，做题时先看句意再选词。", "辨析"),
        q("inj3-p-plurals", "p-plurals", "【对比归类法】对比 man/men 与 foot/feet，第一步做什么？",
          ["先把这一组不规则复数找出来（man、foot、tooth、child…）", "先把所有名词都加上 -s", "先背一遍不规则复数的全部变化，不做对比", "先记住 man 的中文是“男人”"], 0, "第 1 步先找出这一组易混项。不规则复数的共同点是元音变化：man→men、foot→feet、tooth→teeth。归成一组一起看，比零散背效率高。", "方法"),
        q("inj3-p-some-any", "p-some-any", "【对比归类法】把 some / any 放一起对比，第 2 步列什么条件？",
          ["比较两个词的字母数", "列句式条件：肯定句用 some，否定句和疑问句用 any", "把两个词都记成“一些”", "把例句抄十遍，不做条件对比"], 1, "some / any 的分界条件是句式。Do you have any milk? — Yes, I have some. 只背“一些”两个词都能填，必须列出句式条件才能判断。", "辨析"),
        q("inj3-p-spelling", "p-spelling", "【语块记忆法】记 Monday 和 I am Tom. 的拼写，第一步做什么？",
          ["只背单词的字母顺序，不管大小写", "先把全部星期名按字母排序背下来", "连大小写一起记词块：星期首字母大写，I 永远大写", "先记住句子有几个单词"], 2, "语块记忆法要求“连写法一起记”。星期、月份、人名首字母大写，I 在任何位置都大写。把拼写规则当成词块的一部分，写句子时才不丢分。", "方法"),
        q("inj3-p-time", "p-time", "【对比归类法】对比 at half past six、on Monday、in July，第一步做什么？",
          ["把三个介词的中文都记成“在”", "只背 at 的用法，其他以后再补", "先找出这一组介词易混项，再列“时刻 / 星期日期 / 月份年份”的对应条件", "把三个短语各抄写十遍"], 2, "第 2 步列条件：at 用于具体时刻，on 用于星期和具体日期，in 用于月份、季节、年份。条件分清，写时间状语就不会错。", "方法"),
        q("inj3-p-articles", "p-articles", "【对比归类法】对比 a / an / the，第 2 步列什么条件？",
          ["列条件：读音是否以元音音素开头决定 a/an，特指或唯一用 the", "比较三个词的长度", "把 a 和 an 都记成“一个”", "按字母表顺序记 a、an、the"], 0, "a / an 的分界条件是读音，不是字母：an hour（读音以元音开头）、a university（读音以辅音开头）。the 的条件是特指或唯一（the sun）。条件列清，填空题就不会犹豫。", "辨析"),
        q("inj3-p-be", "p-be", "【主干手术法】句子 They ___ good friends. 填空，第一步做什么？",
          ["先看句子里有几个词", "先猜一个 be 动词填进去，读一遍顺口就定", "先把 friends 改成单数", "先找主语 They，确认是复数，再定谓语用 are"], 3, "主干手术法第 1 至第 2 步：先找谓语位置，再往前找主语。主语 They 是复数 → are。am/is/are 由主语决定，不能凭语感。", "方法"),
        q("inj3-p-demonstratives", "p-demonstratives", "【对比归类法】把 this / that / these / those 放一起对比，第 2 步列什么条件？",
          ["列两个条件：距离远近（this、these 近；that、those 远）和单复数", "按字母顺序记四个词", "把四个词都记成“这个”", "比较哪个词更常用"], 0, "四个词靠两个条件分界：远近加单复数。This is my pen.（近、单数）；Those are my shoes.（远、复数）。两个条件一交叉，搭配就不会错。", "辨析"),
        q("inj3-p-imperative", "p-imperative", "【主干手术法】写 Open the door, please. 这样的句子，第一步做什么？",
          ["先补上主语 You，写成 You open the door.", "先把 open 改成 opening", "先定骨架：祈使句以动词原形开头，主语 you 省略", "先把句子改成疑问句"], 2, "第 1 步找谓语：祈使句的谓语在最前面，主语 you 省略。加 please 时放在句尾并用逗号隔开。骨架定好，替换动词就是新指令。", "方法"),
        q("inj3-p-prepositions", "p-prepositions", "【对比归类法】对比 in / on / under / between，第一步做什么？",
          ["把五个介词都记成“在”", "先背介词后面的名词", "先找出这一组方位介词，再列“在内部、在表面、在下方、在两者之间”的条件", "按单词长短排序记忆"], 2, "方位介词靠位置条件区分：in 内部、on 表面、under 下方、next to 旁边、between 两者之间。列成一张对照表，看图说话时直接调用。", "方法"),
        q("inj3-p-questions", "p-questions", "【主干手术法】把 You like milk. 改成一般疑问句，第一步做什么？",
          ["先把 like 改成 liking", "先加 not 变成否定句", "先确定谓语类型：有 be 就提 be，实义动词用 do/does/did 提到句首", "先把句子翻译成中文再对照"], 2, "第 1 步确定谓语类型。谓语是实义动词 like → 借助 Do：Do you like milk? 有 be 动词就直接提前（Are you ready?）。骨架规则先定，再动词序。", "方法"),
    ]

    /// 初一批次（33 道）。
    static let juniorOneBatch: [KnowledgePracticeQuestion] = [
        q("inj3-j1-adverbs", "j1-adverbs", "【骨架替换法】把 She speaks slowly. 改成“她英语说得好”，应该怎么做？",
          ["保留骨架“主语 + 动词 + 副词”，把 slowly 换成 well", "把 slowly 换成 good，因为“好”是形容词", "把动词 speaks 换成 speaking", "把副词提前放到句首"], 0, "骨架是“主语 + 动词 + 副词”，副词修饰动词。well 是副词，good 是形容词只能修饰名词。换内容不换结构，副词位置保持在动词之后。", "迁移"),
        q("inj3-j1-exclamatory", "j1-exclamatory", "【对比归类法】对比 What a nice day! 与 How nice the day is!，第 2 步列什么条件？",
          ["列结构条件：What 后接名词短语，How 后接形容词或副词", "比较两个句子的长度", "把 What 和 How 都记成“多么”", "把两句都改成疑问句来判断"], 0, "感叹句的分界条件是中心词：中心词是名词用 What（What a nice day!），中心词是形容词或副词用 How（How nice!）。条件一列，句型题一眼可判。", "辨析"),
        q("inj3-j1-imperative-rules", "j1-imperative-rules", "【骨架替换法】把 Don't run in the hall. 换成“不许在教室里吃东西”，应该怎么做？",
          ["把 Don't 换成 Not", "把动词改成 ing 形式", "保留骨架 Don't + 动词原形 + 地点，把 run 换成 eat、hall 换成 the classroom", "在句首加一个主语 You"], 2, "否定祈使句骨架是 Don't + 动词原形。替换动词和地点即可：Don't eat in the classroom. 骨架不动，规则句可以成批生成。", "迁移"),
        q("inj3-j1-infinitive-purpose", "j1-infinitive-purpose", "【骨架替换法】表达“我出去买面包”，第一步做什么？",
          ["先写两个独立的句子用 and 连接", "先想 bread 的复数形式怎么变", "先加一个 because 从句说明原因", "先定骨架“主语 + 谓语 + to do 表目的”"], 3, "不定式表目的的骨架是“动作 + to do”。I went out to buy bread. 换成买牛奶只需改 to buy milk。骨架定好，目的句就能批量生成。", "方法"),
        q("inj3-j1-invitation", "j1-invitation", "【骨架替换法】发出邀请 Would you like to join us?，应该怎么做？",
          ["把 Would 换成 Will，因为将来时更准确", "把 to join 改成 joining", "保留骨架 Would you like to + 动词，把 join us 换成新活动", "把句子改成陈述句再说一遍"], 2, "邀请骨架是 Would you like to + 动词原形？替换活动内容即可：Would you like to play football? 回应也能套骨架：Yes, I'd love to. 或 I'd love to, but…", "迁移"),
        q("inj3-j1-thanks", "j1-thanks", "【骨架替换法】把 Thanks for your help. 改成“谢谢你帮我学英语”，应该怎么做？",
          ["把 Thanks 换成 Thank you，因为更正式", "把 for 换成 to", "重新写一个完全不同的句型", "保留骨架 Thanks for + 名词或动名词，把 your help 换成 helping me with my English"], 3, "Thanks for + 名词或 doing 是固定骨架。换内容就是 Thanks for helping me with my English. for 是介词，后面接名词性成分，不能接动词原形。", "迁移"),
        q("inj3-j1-directions", "j1-directions", "【场景预测法】听一段问路对话，第一步做什么？",
          ["先把所有方向词抄一遍", "先看选项，预判要听的是方向词还是地点名词", "先听说话人是男是女", "先猜答案长短，长的可能是对的"], 1, "第 1 步按选项预判。选项出现 left / right / across from 就抓方向词与参照物（bank、library）；听时用箭头速记，不追求听清每个词。", "方法"),
        q("inj3-j1-listening-keywords", "j1-listening-keywords", "【场景预测法】听对话抓“人物、时间、数字、地点”，第一步做什么？",
          ["把四类词都写下来，平均用力去听", "先听数字，因为数字最重要", "先听完整段，再凭回忆选答案", "先看题干问的是哪一类信息，再决定重点抓哪一类词"], 3, "第 1 步是先明确听什么。题干问 When 就抓时间，问 How much 就抓数字。目标明确后，其余信息可以主动忽略，注意力就不会被冲散。", "方法"),
        q("inj3-j1-shopping", "j1-shopping", "【场景预测法】听购物对话，第 2 步做什么？",
          ["预判可能答案：价格、尺码、颜色或购买决定", "预判说话人的年龄", "预判对话发生在哪一天", "先把所有衣服名抄一遍"], 0, "购物场景的预判范围固定：How much（价格）、What size（尺码）、What color（颜色）、买还是不买。预判清楚，听到 fifteen 就知道要跟 dollars 配对。", "方法"),
        q("inj3-j1-connectors", "j1-connectors", "【对比归类法】对比 and / but / or / so / because，第 2 步列什么条件？",
          ["按字母顺序记五个词", "把五个词都记成“和”", "只背 because，因为它最常见", "列逻辑条件：并列、转折、选择、结果、原因"], 3, "分界条件是逻辑关系。and 并列、but 转折、or 选择、so 结果、because 原因。条件列清后，做完形填空先判逻辑再选词，而不是凭语感。", "辨析"),
        q("inj3-j1-frequency-question", "j1-frequency-question", "【对比归类法】对比 How often / How soon / How long，第 2 步列什么条件？",
          ["比较三个短语的字母数", "列提问对象条件：问频率、问将来时间、问时长", "把三个都记成“多久”", "只背 How long，因为它最常见"], 1, "三个疑问短语靠“问什么”分界：How often 问频率（答 twice a week）、How soon 问将来（答 in two days）、How long 问时长（答 for two weeks）。条件列清就能秒选。", "辨析"),
        q("inj3-j1-reading-detail", "j1-reading-detail", "【原文取证法】做细节题，第一步做什么？",
          ["先通读全文并背下所有句子", "先看四个选项，选和原文最像的那个", "先读题干划关键词（人名、数字、地点、动词）", "先看文章标题再直接选"], 2, "第 1 步是划题干关键词，第 2 步回原文定位到那一句并划线。答案必须有依据句，划不出来就不能选——这一步能挡掉大部分干扰项。", "方法"),
        q("inj3-j1-frequency", "j1-frequency", "【对比归类法】对比 always / usually / sometimes / never，第 2 步列什么条件？",
          ["把四个词都记成“经常”", "按单词长度排序记忆", "列频率高低顺序和句中位置：助动词与 be 后、实义动词前", "只记 always，其他遇到再说"], 2, "频率副词有两个条件：频率高低（always、usually、sometimes、never 依次降低）和在句子里的位置（实义动词前、be 动词后）。条件列清，语序题和词义题一起解决。", "辨析"),
        q("inj3-j1-frequency-count", "j1-frequency-count", "【对比归类法】对比 once / twice / three times，第 2 步列什么条件？",
          ["只写 three times，不带周期", "先记 once 的中文是“一次”就够", "列“次数 + 周期”的搭配条件，如 twice a week、once a month", "把三个短语各抄十遍"], 2, "次数的用法条件是“次数 + 周期”：once / twice / three times + a week（或 a month）。回答 How often 时必须带上周期，只说 three times 是不完整的。", "辨析"),
        q("inj3-j1-past", "j1-past", "【时间标志法】句子 We ___ (visit) the museum last Sunday. 填空，第一步做什么？",
          ["先把 visit 的三态变化都写上，再挑一个", "先翻译整句中文，凭语感选形式", "先看主语 We 是复数，用 visits", "先圈出 last Sunday，确定用一般过去时，再把 visit 变成 visited"], 3, "时间标志法的顺序是：圈标志（last Sunday）→ 翻时间（过去）→ 核对主语 → 定形式（visited）。第 1 步永远是圈标志。", "方法"),
        q("inj3-j1-present-cont", "j1-present-cont", "【时间标志法】句子 Look! The boys ___ (play) basketball. 填空，第一步做什么？",
          ["先看 boys 是复数，直接把 play 填进去", "先把 play 的各种形式列出来", "先圈出 Look!，确定用现在进行时，再写 are playing", "先猜一个答案，读一遍顺口就行"], 2, "Look! / Listen! / now 都是现在进行时的信号。第 1 步圈标志，第 3 步核对主语 The boys 用 are，动词用 -ing 形式。三步走完再下笔。", "方法"),
        q("inj3-j1-count", "j1-count", "【对比归类法】对比 two apples 和 some water，第 2 步列什么条件？",
          ["列条件：可数名词能直接加数词，不可数名词要用量词（a glass of water）", "把 apples 和 water 都加上 -s", "只记住 water 不能用复数", "按名词长短分类"], 0, "分界条件是能否直接计数。可数：two apples、three books；不可数：some water、a piece of news。条件列清后，数量表达题先判可数性再选形式。", "辨析"),
        q("inj3-j1-indefinite", "j1-indefinite", "【对比归类法】对比 something / anything / everyone，第 2 步列什么条件？",
          ["把三个词都记成“某物”", "比较三个词的字母数", "只记 someone，其余略过", "列条件：指物还是指人、用于肯定还是否定疑问"], 3, "分界条件是“指代对象 + 句式”：something（指物，肯定句）、anything（指物，否定与疑问句）、everyone（指人，作主语时谓语用单数）。条件列清，Everyone is here. 的谓语也不会写错。", "辨析"),
        q("inj3-j1-ordinal-date", "j1-ordinal-date", "【语块记忆法】记 September the seventh 这类日期表达，第一步做什么？",
          ["把“月份 + the + 序数词”当成一个词块整体记", "先单独背月份名，日期以后再说", "把序数词按字母表顺序背一遍", "只记数字 9 和 7 的英文"], 0, "日期是固定词块：September the seventh、October the first。整体记比拆开记更稳；写日期时先月份后序数词，年份前加逗号。", "方法"),
        q("inj3-j1-possessive", "j1-possessive", "【对比归类法】对比 Tom's pencil 和 the students' books，第 2 步列什么条件？",
          ["把所有名词都加 's", "把 's 记成“的”，不看单复数", "列条件：单数名词加 's，以 s 结尾的复数名词只加 '", "按名词是否有生命来分类"], 2, "所有格的分界条件是单复数：Tom's（单数加 's）、the students'（以 s 结尾的复数只加 '）。条件一列，写“学生们的书”就不会写成 students's。", "辨析"),
        q("inj3-j1-prep", "j1-prep", "【对比归类法】对比 at school 和 on Monday，第 2 步列什么条件？",
          ["把 at / on / in 都记成“在”", "只记 at，其他两个很少考", "按介词长短排序记忆", "列条件：at 接具体地点与时刻，on 接星期和具体日期，in 接大地点和月份"], 3, "介词靠条件分界：at school（具体地点）、on Monday（星期）、in July（月份）、in Beijing（大地点）。列成对照表，写时间地点状语时直接调用。", "辨析"),
        q("inj3-j1-prepositions", "j1-prepositions", "【对比归类法】对比 look at / listen to / wait for，第一步做什么？",
          ["先单独背 look、listen、wait 的意思", "先把动词和它固定搭配的介词当成一个整体词块找出来", "按介词把短语重新分类，动词不管", "只背最长的那个短语"], 1, "动词加介词是固定搭配，要整体记。第 2 步把介词相同的归一组（listen to、talk to、speak to），这样遇到新动词也能猜出搭配。", "方法"),
        q("inj3-j1-quantifiers", "j1-quantifiers", "【对比归类法】对比 many / much / a few / a little，第 2 步列什么条件？",
          ["把四个词都记成“许多”", "按字母顺序记四个词", "只记 many，其他靠语感", "列条件：修饰可数还是不可数，语气是肯定还是否定（few 表“几乎没有”）"], 3, "数量词有两个分界条件：可数还是不可数（many students / much water），以及肯定还是否定含义（a few 有一些，few 几乎没有）。条件列清，数量题就不会只靠语感。", "辨析"),
        q("inj3-j1-whose", "j1-whose", "【对比归类法】对比 whose / which / what kind of，第 2 步列什么条件？",
          ["把三个都记成“哪个”", "列提问对象条件：问归属、问限定范围内的选择、问种类", "比较三个词的读音", "只背 whose，因为它最常用"], 1, "分界条件是提问对象：whose 问归属（Whose book is this?）、which 问限定范围内的选择、what kind of 问种类。条件列清，疑问句选择题直接对应。", "辨析"),
        q("inj3-j1-spelling-rules", "j1-spelling-rules", "【对比归类法】对比 study 变 studies 和 play 变 plays，第 2 步列什么条件？",
          ["把所有动词都加 -es", "列条件：辅音字母加 y 结尾变 ies，元音字母加 y 结尾直接加 s", "只背 study 的变形，play 以后再说", "按单词长短决定怎么变"], 1, "拼写变化的分界条件在 y 前面的字母：辅音 + y → ies（study/studies），元音 + y → 直接加 s（play/plays）。条件列清，三单和复数都不会拼错。", "辨析"),
        q("inj3-j1-negative", "j1-negative", "【主干手术法】把 He likes tea. 改成否定句，第一步做什么？",
          ["直接在 likes 后面加 not", "把 likes 改成 doesn't likes", "先确定谓语类型：likes 是实义动词，用 doesn't + 动词原形", "先把句子改成疑问句再加 not"], 2, "第 1 步确定谓语类型：实义动词用 don't / doesn't / didn't + 动词原形，所以是 He doesn't like tea. 只有 be 动词才直接在 be 后加 not。", "方法"),
        q("inj3-j1-possessive-pronoun", "j1-possessive-pronoun", "【对比归类法】对比 my book 和 The book is mine.，第 2 步列什么条件？",
          ["列位置条件：形容词性物主代词后必须接名词，名词性物主代词单独作主语或表语", "把 my 和 mine 都记成“我的”", "比较两个词的字母数", "只记 my，因为它出现最多"], 0, "分界条件是后面有没有名词：my book（后面有名词用形容词性）、The book is mine.（后面没名词，单独用名词性）。条件列清，填空题看空后有没有名词即可判断。", "辨析"),
        q("inj3-j1-pronouns", "j1-pronouns", "【对比归类法】对比 She helps me. 和 This is my bag.，第 2 步列什么条件？",
          ["列句法位置条件：主格作主语、宾格作宾语、形容词性物主代词后接名词", "把 I / me / my 都记成“我”", "按单词长度记忆", "只背主格，其他位置靠语感"], 0, "人称代词靠位置分界：主语位用主格（She、I、They），动词或介词后用宾格（me、him、them），名词前用形容词性物主代词（my、your）。位置条件一列，代词题不出错。", "辨析"),
        q("inj3-j1-reflexive", "j1-reflexive", "【对比归类法】对比 She helps me. 和 I made it myself.，第 2 步列什么条件？",
          ["把 myself 记成“我自己”，见到就选", "列条件：宾语与主语不是同一人用宾格，是同一人用反身代词", "凡是句子里有 I 就用 myself", "把反身代词按人称背一遍，不看主语"], 1, "分界条件是是否指同一人：She helps me.（不同人，用宾格 me）；I made it myself.（同一人，用反身代词 myself）。条件列清，代词填空不会混。", "辨析"),
        q("inj3-j1-sentence", "j1-sentence", "【主干手术法】判断 Birds fly. 属于哪种句型，第一步做什么？",
          ["先找谓语 fly，再找主语 Birds，看是否还需要宾语或表语", "先数句子的单词数量", "先看句子有没有介词短语", "先翻译成中文再判断句型"], 0, "第 3 步是判句型。有主语和谓语、不需要宾语，属于主谓句型（Birds fly.）。She is kind. 中 is 是系动词，后面是表语，属于主系表。句型靠句子成分判断，不靠长度。", "方法"),
        q("inj3-j1-subject", "j1-subject", "【主干手术法】句子 He ___ (like) music. 填空，第一步做什么？",
          ["先看 music 是单数还是复数", "先找主语 He，确认是第三人称单数，再定谓语 likes", "先猜一个形式，读起来顺就行", "先把 like 的各种形式写出来"], 1, "第 1 至第 2 步：先找谓语，再往前找主语。主谓一致看主语：He → likes；They → like。判断顺序永远是“先主语，后谓语形式”。", "方法"),
        q("inj3-j1-there", "j1-there", "【主干手术法】句子 There ___ a tree in the garden. 填空，第一步做什么？",
          ["按 garden 的单复数选 are", "先找 There be 后面的真正主语 a tree，按它的单复数选 is 或 are", "按 there 决定用 is", "先猜一个，再看句子通不通"], 1, "There be 的谓语由后面的名词决定：a tree 是单数用 is，two trees 用 are。第 2 步找主语时要越过 there 往后找，这是最容易错的一步。", "方法"),
        q("inj3-j1-there-transform", "j1-there-transform", "【主干手术法】把 There is a pen. 改成一般疑问句，第一步做什么？",
          ["加助动词 Do：Do there is a pen?", "把 a pen 提到句首", "先定骨架：be 动词提到 there 之前，变成 Is there a pen?", "在句尾加 isn't it"], 2, "There be 的疑问句骨架是把 be 提到 there 前：Is there a pen? 第 1 步先确定谓语是 be 而不是实义动词，所以不借助 do。", "方法"),
    ]

    /// 初二批次（37 道）。
    static let juniorTwoBatch: [KnowledgePracticeQuestion] = [
        q("inj3-j2-advice", "j2-advice", "【骨架替换法】提建议 Why not take a break? 这个骨架应该怎么用？",
          ["保留骨架 Why not + 动词原形，把 take a break 换成新建议", "把 Why not 改成 Why don't you，才符合语法", "把 take 改成 taking", "把句子改成陈述句再读一遍"], 0, "建议句骨架有好几种：Why not + 动词原形、Let's + 动词原形、How about + doing。定好骨架后替换内容即可，特别注意 How about 后接动名词。", "迁移"),
        q("inj3-j2-comparative", "j2-comparative", "【对比归类法】对比 taller 和 more interesting，第 2 步列什么条件？",
          ["把所有形容词都加 more", "把 taller 写成 more tall", "按形容词长短随便选一种形式", "列条件：单音节和部分双音节加 -er，多音节前加 more，后面都接 than"], 3, "比较级的分界条件是音节数：tall → taller，interesting → more interesting。条件列清后，写比较句先数字音节再定形式，than 是固定搭档。", "辨析"),
        q("inj3-j2-direct-speech", "j2-direct-speech", "【骨架替换法】写 He said, “I am ready.” 这样的直接引语，第一步做什么？",
          ["先把引号里的时态改成过去时", "把逗号放在引号里面", "先定骨架：说话人 + said + 逗号 + 引号内原句（标点写在引号内）", "把引号删掉，直接连成一句"], 2, "直接引语的骨架是“主语 + said, + 引号内原句”，引号内保持原时态和原标点。第 4 步再检查标点：逗号在引号外，句号在引号内。", "方法"),
        q("inj3-j2-exclamation", "j2-exclamation", "【对比归类法】对比 What a beautiful city! 和 How beautiful the city is!，第 2 步列什么条件？",
          ["按句子长短来选择", "把 What 和 How 都记成“多么”", "把两句都改成陈述句再判断", "列条件：中心词是名词用 What，中心词是形容词或副词用 How"], 3, "感叹句的判据是中心词：What + 名词短语（What a beautiful city!），How + 形容词或副词 + 主谓（How beautiful the city is!）。条件一列，句型题秒判。", "辨析"),
        q("inj3-j2-gerund", "j2-gerund", "【骨架替换法】表达“读书很有趣”，第一步做什么？",
          ["先写 Read is fun.，因为动词原形更简单", "把句子改成 Reading fun is.", "先加一个主语 I 再写句子", "先定骨架：动名词作主语 + 系动词 + 表语，如 Reading is fun."], 3, "动词作主语要变成动名词：Reading is fun. 骨架是“动名词 + is + 表语”。第 4 步检查谓语用单数，因为动名词作主语视为单数。", "方法"),
        q("inj3-j2-health", "j2-health", "【骨架替换法】给感冒的同学提建议，第一步做什么？",
          ["先写 You are a cold.", "先定骨架：You should + 动词原形 + 补充说明", "先写 It is you should rest.", "先把 should 换成 must，语气更强"], 1, "建议骨架是 You should + 动词原形。You should see a doctor and take a rest. 骨架不动，替换动词就是新建议；should 后永远接原形。", "方法"),
        q("inj3-j2-infinitive", "j2-infinitive", "【骨架替换法】写 I want to learn English. 这样的句子，第一步做什么？",
          ["把 to learn 改成 learning，因为动名词更自然", "把 want 改成 wants，因为学习要用第三人称", "先定骨架：主语 + want + to do", "先写 I want learn English."], 2, "want to do 是固定骨架，to 不能省。定好骨架后替换动词：I want to learn / to travel / to help。第 4 步检查主语人称，决定用 want 还是 wants。", "方法"),
        q("inj3-j2-linking", "j2-linking", "【骨架替换法】写 The soup tastes good. 这样的句子，第一步做什么？",
          ["把 good 改成 well，因为要修饰动词", "把 tastes 改成 is tasting", "先定骨架：主语 + 系动词 + 形容词（表语）", "在形容词前加 very much"], 2, "系动词（look、feel、taste、sound、become）后接形容词作表语，不接副词。骨架定好：The soup tastes good. 换成 The music sounds nice. 结构不变。", "方法"),
        q("inj3-j2-purpose", "j2-purpose", "【骨架替换法】表达“他努力学习为了通过考试”，第一步做什么？",
          ["先定骨架：主语 + 谓语 + in order to 或 so that + 目的", "先写 He studies hard for pass the exam.", "把 in order to 换成 because 表原因", "写成两个句子用 and 连接"], 0, "目的状语骨架：in order to + 动词原形，或 so that + 完整句子。He studies hard in order to pass the exam. 第 4 步检查 to 后是原形、so that 后是完整句子。", "方法"),
        q("inj3-j2-social", "j2-social", "【骨架替换法】借笔时说 Could I borrow your pen?，这个骨架应该怎么用？",
          ["保留骨架 Could I + 动词原形，把 borrow your pen 换成想借的东西", "把 Could I 改成 Can I，因为 could 是过去式", "把 borrow 改成 borrows", "把 borrow 换成 lend，其余不变"], 0, "礼貌请求骨架是 Could I + 动词原形。第 4 步注意词义：borrow 是“借入”，lend 是“借出”，Could I borrow your pen? 不能换成 lend。", "迁移"),
        q("inj3-j2-superlative", "j2-superlative", "【对比归类法】对比 the tallest 和 the most interesting，第 2 步列什么条件？",
          ["列条件：单音节加 -est，多音节前加 most，前面通常加 the", "把所有形容词都加 most", "把 the 去掉，因为最高级自带特指", "按形容词长短随意选一种形式"], 0, "最高级的分界条件与比较级相同（音节数），只是后缀变 -est、前面加 the。条件列清：the tallest boy、the most interesting book。", "辨析"),
        q("inj3-j2-too-enough", "j2-too-enough", "【对比归类法】对比 too old 和 old enough，第 2 步列什么条件？",
          ["把 too 和 enough 都记成“太”", "把 enough 放在形容词前面", "按句子长短来选择", "列条件：too + 形容词表“太…以至于不能”，形容词 + enough 表“足够…可以”"], 3, "分界在位置和含义：too 在形容词前（too old to go，太老不能去），enough 在形容词后（old enough to go，够大可以去）。位置搞反，意思就相反。", "辨析"),
        q("inj3-j2-listening-intent", "j2-listening-intent", "【场景预测法】听 I'd love to, but I have to study. 判断说话人意图，第一步做什么？",
          ["先听每个单词的中文意思", "先猜答案，再听录音核对一遍", "先看选项是在问建议、邀请还是拒绝，预判要抓的是语气和转折词", "先记住说话人的名字"], 2, "意图题的关键是语气和转折：I'd love to, but… 表示礼貌拒绝。第 1 步按选项预判意图类别，第 3 步只抓 but 后面的真实信息。", "方法"),
        q("inj3-j2-telephone", "j2-telephone", "【场景预测法】听电话留言，第 2 步做什么？",
          ["预判电话机是什么牌子", "先听说话人的心情", "先记下所有听到的数字", "预判要记的信息：来电人、留言事由、回电号码或时间"], 3, "电话场景的预判范围固定：谁打的、什么事、什么时候回电。带着这三个问题去听，速记时只写关键词和号码，不用整句听写。", "方法"),
        q("inj3-j2-travel", "j2-travel", "【场景预测法】听出行对话，第 3 步抓哪三类词？",
          ["抓所有形容词和副词", "抓说话人的年龄和职业", "抓数字（时间、车次、价格）、地点名，以及转折和改口（but、instead）", "抓每个动词的时态"], 2, "出行场景的答案几乎都落在时间、地点和价格上；临时改动常用 but、instead 引出。第 3 步锁定这三类词，其余可以略过。", "方法"),
        q("inj3-j2-cause", "j2-cause", "【对比归类法】对比 because / so / as a result，第 2 步列什么条件？",
          ["把三个都记成“因为”", "列逻辑方向：because 后接原因，so 和 as a result 后接结果", "按出现频率排序记忆", "只背 because，其他两个很少考"], 1, "分界在逻辑方向：because 引出原因（It rained, so we stayed home. 中 because 接原因），so 与 as a result 后面是结果。条件列清，完形填空先判因果再选词。", "辨析"),
        q("inj3-j2-conditional", "j2-conditional", "【主干手术法】分析 If it rains, we will stay home. 第一步做什么？",
          ["先把两个句子都改成过去时", "先切分两个分句，找出 if 从句的谓语 rains 和主句的谓语 will stay", "先数句子有几个词", "先看 rains 要不要加 -s，再决定主句时态"], 1, "第 1 步找谓语：if 从句用一般现在时（rains），主句用一般将来时（will stay），这正是“主将从现”的由来。先切分谓语，规则自然显现。", "方法"),
        q("inj3-j2-environment", "j2-environment", "【原文取证法】做环保短文的主旨题，第一步做什么？",
          ["先读题干划关键词，确定问的是主旨还是细节", "先把所有环保词汇抄下来", "先看首句就直接选答案", "先按选项长度排除两个"], 0, "第 1 步划题干关键词并判断题型。主旨题要通读首末句找重复话题词，细节题要回原文定位；题型判断错了，方法就会用错。", "方法"),
        q("inj3-j2-passages", "j2-passages", "【原文取证法】概括段落主旨，应该怎么做？",
          ["划出每段首句、重复出现的话题词和结尾句，再归纳", "只读第一句就定主旨", "把整段逐词翻译一遍", "选出现词汇最多的那个选项"], 0, "第 2 步回原文找依据：主旨依据在首句、重复词和结尾。第 3 步把选项与这些依据比对，范围过大或过小的都要排除。", "迁移"),
        q("inj3-j2-reading", "j2-reading", "【原文取证法】段落中 However, the plan failed. 里的指代和转折，应该怎么处理？",
          ["只记住 However 是“但是”，不看上文", "把 the plan 直接理解成“计划”，不管指哪个计划", "跳过这句，直接读最后一段", "先回上文找到 However 转折的对象和 the plan 的具体所指，再判断该句作用"], 3, "第 2 步定位依据句后，还要向上找指代：However 的转折对象在上文，the plan 的具体内容也在上文。不回读就一定会理解偏。", "迁移"),
        q("inj3-j2-reading-structure", "j2-reading-structure", "【原文取证法】判断短文是“问题与解决”还是“总分”结构，第一步做什么？",
          ["先数文章有几段", "先划出每段的话题句，看段落之间是并列、因果还是问题与对策", "先看文章里有多少生词", "先看题目有几个选项"], 1, "第 2 步回原文找依据：结构依据在各段首句的关系。有 problem 与 solution 对应就是问题解决型，各段并列展开同一主题就是总分型。", "方法"),
        q("inj3-j2-relative-basic", "j2-relative-basic", "【主干手术法】分析 The book that I bought is new. 第一步做什么？",
          ["先翻译整句中文，再找动词", "先找主句谓语 is，把 that I bought 这段定语从句括起来先放一边", "把 that 当成主语，找它后面的谓语", "按单词顺序逐词分析"], 1, "第 1 步找谓语。一句里出现两个动词时，先定主句谓语（is），从句部分（that I bought）先括起来。主干是 The book is new.，意思一下就清楚了。", "方法"),
        q("inj3-j2-frequency", "j2-frequency", "【时间标志法】句子 I ___ (read) at eight last night. 填空，第一步做什么？",
          ["先圈出 at eight last night，确定用过去进行时，再写 was reading", "先看主语 I，直接用 am reading", "先把 read 的三态写出来再挑一个", "先猜一个形式读一遍顺口就定"], 0, "过去进行时的标志是“过去某一时刻”（at eight last night、at that time）。第 1 步圈标志，第 3 步核对主语 I 用 was，动词用 -ing 形式。", "方法"),
        q("inj3-j2-future", "j2-future", "【时间标志法】句子 I ___ (call) you tomorrow. 填空，第一步做什么？",
          ["先把 call 改成 called，因为是将来", "先看主语 I 决定用 am", "先圈出 tomorrow，确定用一般将来时，再写 will call", "先猜 will 还是 would，凭语感定"], 2, "tomorrow / next week / soon 是将来时标志。第 1 步圈标志，第 2 步翻时间（将来），第 3 步定形式 will + 动词原形。", "方法"),
        q("inj3-j2-future-plan", "j2-future-plan", "【时间标志法】句子 We ___ (visit) Beijing next week. 要用 be going to 填空，第一步做什么？",
          ["先看语境是不是已有计划或眼前迹象，再圈 next week，确定 are going to visit", "先看主语 We 是复数，用 is going to", "先把 visit 变成 visited", "先猜 will visit，因为它更简单"], 0, "第 1 步看语境与时间标志：next week 表将来；若语境是已有计划或眼前迹象，用 be going to，主语 We 用 are。will 与 be going to 的区别在语境，不在对错。", "方法"),
        q("inj3-j2-present-perfect-basic", "j2-present-perfect-basic", "【时间标志法】要表达 She ___ (see) the film. 的“她看过这部电影”，第一步做什么？",
          ["先看有没有 yesterday，没有就用一般现在时", "先把 see 改成 saw，因为看电影是过去的事", "先猜答案，读一遍顺口就定", "先判断语境是“经历或结果”而不是具体过去时间，确定用 has seen"], 3, "现在完成时的标志是 already、yet、ever、never，或“到现在为止的结果”，句子不出现具体过去时间。第 1 步先判断语境属于哪一类，再定 has + 过去分词。", "方法"),
        q("inj3-j2-used-to", "j2-used-to", "【对比归类法】对比 used to do 和 be used to doing，第 2 步列什么条件？",
          ["把两个都记成“过去常常”", "按句子长短来选择", "列条件：used to + 动词原形表“过去常常”，be used to + doing 表“习惯于”", "只背 used to，另一个很少考"], 2, "分界在含义和后面接什么：used to be shy（过去常常害羞），be used to getting up early（习惯早起）。条件列清，遇到 used to 先看前面有没有 be。", "辨析"),
        q("inj3-j2-verb-forms", "j2-verb-forms", "【对比归类法】对比 go/went/gone、write/wrote/written，第 2 步列什么条件？",
          ["列条件：第二栏用在一般过去时，第三栏用在完成时和被动语态", "把三态按字母顺序记", "只背原形和过去式，过去分词以后再说", "按单词长度决定用哪一栏"], 0, "分界在“和谁的助动词搭配”：have/has/had 与 be 后用过去分词（gone、written），一般过去时单独用过去式（went、wrote）。列清搭配条件，时态填空就不会混。", "辨析"),
        q("inj3-j2-adjectives", "j2-adjectives", "【对比归类法】对比 as tall as / taller than / the tallest，第 2 步列什么条件？",
          ["把三个形式都加 more", "列比较对象个数的条件：同级比较、两者比较、三者以上比较", "按形容词长度随机选一种", "只记比较级，最高级靠语感"], 1, "形容词的分界条件是“比较对象个数”：同级用 as…as、两者用 -er/more…than、三者以上用 the -est/most。列清条件，语法填空先数对象再定形式。", "辨析"),
        q("inj3-j2-preposition-time", "j2-preposition-time", "【对比归类法】对比 since 2020 / for two years / during the holiday，第 2 步列什么条件？",
          ["把三个都记成“在…期间”", "列条件：since 接时间起点，for 接时间段长度，during 接特定时期", "把 for 和 since 互换使用", "只记 for，其他两个很少考"], 1, "时间介词的分界条件是接什么：since + 起点（since 2020）、for + 长度（for two years）、during + 特定时期（during the holiday）。搭配完成时使用时尤其要分清 since 与 for。", "辨析"),
        q("inj3-j2-articles", "j2-articles", "【对比归类法】对比 play basketball / have breakfast / study history，第 2 步列什么条件？",
          ["在所有名词前都加 the", "把 play basketball 写成 play the basketball", "按名词单复数决定用不用冠词", "列条件：球类、三餐、学科前不加冠词，它们属于固定零冠词搭配"], 3, "零冠词的分界条件是搭配类别：球类（play basketball）、三餐（have breakfast）、学科（study history）。列成一组一起记，写作时就不会多写 the。", "辨析"),
        q("inj3-j2-both-either", "j2-both-either", "【对比归类法】对比 both / either / neither，第 2 步列什么条件？",
          ["把三个都记成“两个都”", "按字母顺序记三个词", "列条件：两者全是 both，任一是 either，两者都不 neither", "只记 both，其他两个很少考"], 2, "分界在“范围与肯否”：Both answers are right.（两个都对）、Either answer is OK.（任一个都行）、Neither answer is right.（两个都不对）。neither 本身是否定，谓语要用肯定形式。", "辨析"),
        q("inj3-j2-modal", "j2-modal", "【对比归类法】对比 can / should / must，第 2 步列什么条件？",
          ["把三个都记成“能”", "按情态动词长短排序记忆", "只背 should，因为建议类题最多", "列语义条件：can 表能力与许可，should 表建议，must 表必须与推测，后面都接动词原形"], 3, "分界在语义强度：can 能或可以、should 应该、must 必须或一定。共同条件是不能接 to，也不能加 -s。条件列清，情态动词题先看语义再定形式。", "辨析"),
        q("inj3-j2-object", "j2-object", "【主干手术法】分析 She gave me a gift. 第一步做什么？",
          ["先翻译整句，再看哪个词是宾语", "先看 me 和 gift 哪个更长", "先找谓语 gave，再找主语 She，识别出后面是“人 + 物”两个宾语", "按单词顺序逐词分析"], 2, "第 3 步判句型：主语 + 谓语 + 间接宾语（人）+ 直接宾语（物）。换成“物 + to 人”时是 She gave a gift to me. 语序规则靠句型判断，不靠背。", "方法"),
        q("inj3-j2-question-forms", "j2-question-forms", "【对比归类法】对比一般疑问、特殊疑问、选择疑问、反意疑问，第 2 步列什么条件？",
          ["把四类疑问句各抄一遍", "只练特殊疑问句", "按句子长短区分四类", "列条件：用什么开头（助动词、疑问词、or）和答案类型（肯否、信息、二选一、求证）"], 3, "疑问句的分界条件在开头形式与答案类型。列清条件后，看到 Do you walk or ride? 就知道是选择疑问句，答语必须二选一，不能答 Yes。", "辨析"),
        q("inj3-j2-question-tags", "j2-question-tags", "【对比归类法】对比 It is cold, isn't it? 和 You don't like tea, do you?，第 2 步列什么条件？",
          ["两句都加 isn't it", "列条件：前肯后否、前否后肯，且附加问句的主语和助动词与主句一致", "按主句长短决定附加部分的形式", "只记前肯后否一种情况"], 1, "分界在主句是肯定还是否定：前肯后否（isn't it）、前否后肯（do you）。还要核对助动词与主语一致，这也是最容易丢分的一步。", "辨析"),
        q("inj3-j2-voice", "j2-voice", "【对比归类法】对比 People speak English here. 和 English is spoken here.，第 2 步列什么条件？",
          ["看到 English 在句首就选被动", "把 speak 改成 spoke 表示被动", "列条件：谁做动作用主动，强调动作承受者用被动（be + 过去分词）", "按句子长短判断主动还是被动"], 2, "主被动的分界在强调谁：强调动作发出者用主动（People speak），强调承受者用被动（English is spoken）。被动形式固定为 be + 过去分词，be 的人称和时态随句意变化。", "辨析"),
    ]

    /// 初三批次（42 道）。
    static let juniorThreeBatch: [KnowledgePracticeQuestion] = [
        q("inj3-j3-argument", "j3-argument", "【骨架替换法】写“我认为阅读有帮助，因为能增长见识”这样一段，第一步做什么？",
          ["先写很多理由，观点放最后", "先把想到的单词都写下来再连句", "先定骨架：观点（I think…）+ 理由（because…）+ 例子或总结", "先追求句子长度，越长越好"], 2, "议论文骨架是“观点—理由—例子或总结”。定好骨架再填内容，文章结构就立住了；第 4 步加 Besides、Therefore 等连接词，让层次更清楚。", "方法"),
        q("inj3-j3-email", "j3-email", "【骨架替换法】写一封请假邮件，第一步做什么？",
          ["先定骨架：称呼（Dear…）+ 事由与请求 + 原因 + 礼貌结尾（Best wishes）", "先写长句，把原因放最前面", "先写结尾，再补内容", "先写中文草稿，再逐句翻译"], 0, "应用文骨架固定：称呼、事由、原因、结尾署名。骨架定好，替换事由就是新邮件；第 4 步检查语气是否礼貌（Could I…? Thank you）。", "方法"),
        q("inj3-j3-indirect", "j3-indirect", "【主干手术法】把 Where does he live? 改成 She asked where he ___. 第一步做什么？",
          ["先切分主句 She asked 与从句，把从句改回陈述语序，再把时态后推", "保留疑问语序 does he live", "把 asked 改成 asks", "先把句子改成被动语态"], 0, "宾语从句的两步固定动作：语序改陈述（where he lives，而不是 where does he live），时态呼应（主句过去则从句用过去）。第 1 步先切分主从句，才有动手的落点。", "方法"),
        q("inj3-j3-narrative", "j3-narrative", "【骨架替换法】写一段小故事，第一步做什么？",
          ["先定骨架：人物 + 事件起因 + 冲突或转折 + 结局", "先写结局，再倒回去补原因", "先把所有形容词都用上", "先写很多句子，最后再看结构"], 0, "记叙文骨架是“人物—起因—冲突或转折—结局”。第 4 步用 At first、Suddenly、At last 串起时间线，故事就有了起伏。", "方法"),
        q("inj3-j3-nonfinite", "j3-nonfinite", "【对比归类法】对比 I saw him running. 和 I want to see him.，第 2 步列什么条件？",
          ["把两个都改成 doing 形式", "在 see 后面加 to", "列条件：see、watch 后接 doing 表“正在做”，want、hope 后接 to do 表“要去做”", "按句子长短选择形式"], 2, "非谓语的分界条件在前面那个动词：感官动词（see、hear、watch）后接 doing 或 do，表示正在或全过程；want、hope、plan 后接 to do 表目的与计划。列清搭配条件，形式题就不靠猜。", "辨析"),
        q("inj3-j3-notice", "j3-notice", "【骨架替换法】写一则“节水倡议”，第一步做什么？",
          ["先写号召，再补具体做法", "先写长篇背景介绍", "把每一句都写成问句", "先定骨架：发起对象与事由 + 具体做法（几条） + 号召"], 3, "倡议书骨架：给谁看（Everyone is welcome）、做什么、为什么、怎么行动。列做法时用 First、Second 或祈使句，第 4 步加一句号召收尾。", "方法"),
        q("inj3-j3-object-clause", "j3-object-clause", "【主干手术法】造句 I think that it is useful. 第一步做什么？",
          ["先把 that 去掉，因为能省就都省", "先定主句骨架 I think，再确认 that 从句用完整的主谓结构", "把从句改成疑问语序", "先写从句，最后补主句"], 1, "宾语从句的骨架是“主句 + that + 完整句子（主谓齐全）”。第 4 步检查从句是否缺主语或谓语——从句缺成分是这类题最常见的错。", "方法"),
        q("inj3-j3-object-order", "j3-object-order", "【主干手术法】把 Where is the bank? 放进宾语从句，第一步做什么？",
          ["先定主句骨架（Do you know…），再把从句改回陈述语序 where the bank is", "保留 be 在主语前面的语序", "在从句前加助动词 do", "把从句改成被动语态"], 0, "第 1 步切分主从句。疑问词后必须用陈述语序：where the bank is，而不是 where is the bank。语序是这类题的得分点，语序对了形式才对。", "方法"),
        q("inj3-j3-opinion", "j3-opinion", "【骨架替换法】表达观点 In my opinion, reading helps. 这个骨架应该怎么用？",
          ["连用两个 In my opinion 加强语气", "把 In my opinion 放到句尾", "保留骨架 In my opinion 或 I think + 主句，把观点内容换掉", "把 opinion 写成 opinions，因为观点很多"], 2, "观点句骨架是“观点标记 + 完整句子”。In my opinion、I think、From my point of view 选一个即可，不叠加；后面必须跟主谓齐全的句子。", "迁移"),
        q("inj3-j3-punctuation", "j3-punctuation", "【骨架替换法】写 First, … Finally, … 这样的衔接，第 4 步检查什么？",
          ["把所有逗号都改成句号", "每句话都加感叹号增强语气", "检查标点与大小写：连接词后加逗号，句子首字母大写，段与段之间用过渡句衔接", "全篇只用逗号连接句子"], 2, "第 4 步是全文检查：However 这类连接词后要有逗号，句号后首字母大写，段落之间用 Besides、In short 过渡。标点错误在书面表达里是直接扣分项。", "检查"),
        q("inj3-j3-reported", "j3-reported", "【主干手术法】把 He is tired. 转述成间接引语，第一步做什么？",
          ["保留 is 不变，因为事实没有变", "先定主句骨架 He said that，再把从句时态往过去推一步（was tired）", "把 He 改成 I", "把 that 从句改成疑问语序"], 1, "第 1 步定主句骨架（He said that + 从句）。主句是过去时，从句时态要后推：is 变 was；同时人称按语境调整。先骨架、后时态，两步不乱。", "方法"),
        q("inj3-j3-subjunctive", "j3-subjunctive", "【主干手术法】表达 I wish I could fly. 第一步做什么？",
          ["在 wish 后接动词原形 I can fly", "把 wish 改成 hope，时态不变", "在从句前加 that 并保留现在时", "先定骨架：wish + 从句，从句用过去式表示与现在事实相反"], 3, "wish 的骨架固定：从句用过去式表示与现在不符的愿望（I wish I could fly.）。第 1 步先确定用 wish 还是 hope——hope 用现在时，wish 用虚拟。", "方法"),
        q("inj3-j3-translation", "j3-translation", "【骨架替换法】把“我每天花一小时读英语”译成英语，第一步做什么？",
          ["按中文顺序逐词翻译", "先把所有单词的英文拼写想出来", "先写成两个短句再用 and 连接", "先定骨架“主语 I + spend + 时间 + doing”，并确定时态用一般现在时"], 3, "汉译英先定主干和时态，再填词块：I spend an hour reading English every day. 骨架是“主语 + spend + 时间 + doing”。逐词硬译一定会出中式英语。", "方法"),
        q("inj3-j3-writing", "j3-writing", "【骨架替换法】写一篇短文，第一步做什么？",
          ["先写中间部分，开头结尾最后想", "先把所有高级词都用上", "先把每句话都写成复合句", "先定骨架：开头点题 + 中间两三个要点 + 结尾总结"], 3, "写作骨架是“开头—主体—结尾”。定好骨架再填内容，第 4 步用 First、Besides、Finally 串联，保证段落层次清晰，不会想到哪写到哪。", "方法"),
        q("inj3-j3-writing-check", "j3-writing-check", "【骨架替换法】写完作文后的自检，第 4 步检查哪些项目？",
          ["只检查有没有生词", "按顺序查人称、时态、主谓一致、拼写和标点", "只检查字数够不够", "只检查有没有用高级句式"], 1, "第 4 步是把骨架装回去检查：人称是否统一、时态是否前后一致、主谓是否一致、拼写与标点是否正确。按固定顺序查，才不会漏项。", "检查"),
        q("inj3-j3-writing-cohesion", "j3-writing-cohesion", "【对比归类法】对比 Besides / However / Therefore，第 2 步列什么条件？",
          ["把三个都记成“而且”", "列逻辑条件：递进用 Besides，转折用 However，因果用 Therefore", "按单词长度排序记忆", "只背 However，其他两个很少用"], 1, "衔接词的分界是逻辑关系：递进、转折、因果、举例。列清条件，写作时先问“这句话和上一句是什么关系”，就不会张冠李戴。", "辨析"),
        q("inj3-j3-listening-inference", "j3-listening-inference", "【场景预测法】听 I'm afraid I can't make it. 判断隐含意思，第一步做什么？",
          ["先听每个单词的中文意思", "先看选项是问“做了什么”还是“什么意思”，预判要抓的是语气和委婉说法", "先猜说话人是男是女", "先记下所有动词的时态"], 1, "推断题的关键是委婉表达：I'm afraid… 常引出拒绝，I'd love to, but… 也是拒绝。第 1 步按选项预判抓语气，第 3 步锁定 afraid、but 之后的真实信息。", "方法"),
        q("inj3-j3-speech", "j3-speech", "【场景预测法】听一段对话，第一步做什么？",
          ["先看题干和选项，预判场景：校园、购物、问路、电话还是计划", "先把所有可能出现的单词背一遍", "先听第一句，再决定要不要继续听", "先看答案长短猜答案"], 0, "第 1 步永远是预判场景。场景确定后，第 2 步预判可能答案，第 3 步只抓数字、地点和转折词，第 4 步用速记补漏。顺序不能颠倒。", "方法"),
        q("inj3-j3-adverbial", "j3-adverbial", "【主干手术法】分析 Although it was late, he kept reading. 第一步做什么？",
          ["先翻译整个句子再找动词", "把 Although 当成主句的开头", "按单词顺序逐词分析", "先切分两个分句，找出让步从句谓语 was 和主句谓语 kept，主句是 he kept reading"], 3, "第 1 步找谓语并切分分句：Although 引导让步从句，主句才是重点信息（he kept reading）。先切分，再判断从句类型（时间、原因、条件、让步）。", "方法"),
        q("inj3-j3-cloze", "j3-cloze", "【对比归类法】对比 however / instead / therefore，做完形填空时第 2 步列什么条件？",
          ["把三个都记成“因此”", "按单词长度来选择", "只凭读起来顺不顺选", "列逻辑条件：转折用 however，替代用 instead，因果用 therefore，并核对与上下句的关系"], 3, "完形填空的转折词靠逻辑关系判断：先读空前后两句，判断是转折、替代还是因果，再选词。搭配和语境复现是另外两条线索，一起用命中率更高。", "辨析"),
        q("inj3-j3-conjunctions", "j3-conjunctions", "【对比归类法】对比 when / while / before / after / although，第 2 步列什么条件？",
          ["把五个都记成“当…时候”", "按字母顺序记忆", "列条件：时间关系（同时或先后）还是让步关系，以及从句用进行时还是完成时", "只记 when，其他靠语感"], 2, "从属连词的分界在逻辑关系：when、while 表时间（while 常接进行时），before、after 表先后，although 表让步。列清条件，状语从句题先判关系再选连词。", "辨析"),
        q("inj3-j3-ellipsis", "j3-ellipsis", "【对比归类法】对比 I like tea and so does she. 和 I like tea and she does too.，第 2 步列什么条件？",
          ["把 so does she 写成 so she does", "两句都加 too", "列条件：so + 助动词 + 主语表示“也一样”需倒装，too 放在句尾不倒装", "按句子长短来判断"], 2, "省略与替代的分界在结构：so does she（倒装，前句肯定时用）、neither 或 nor 用于否定、too 与 also 放句尾。列清条件，替代句就不会写错语序。", "辨析"),
        q("inj3-j3-reading-attitude", "j3-reading-attitude", "【原文取证法】判断作者态度，第一步做什么？",
          ["只看文章标题就判断态度", "先划出文中带评价色彩的形容词和副词（successful、unfortunately、hopefully）", "只数文中正面词和负面词的个数", "凭自己对话题的喜恶判断"], 1, "态度的依据在评价词，不在话题本身。第 2 步把评价词划线并归类（支持、反对、客观），第 3 步再与选项比对。切记：作者写某个话题不等于支持它。", "方法"),
        q("inj3-j3-reading-title", "j3-reading-title", "【原文取证法】选最佳标题，应该怎么做？",
          ["先划出全文重复出现的话题词与核心观点句，再选覆盖全面又不夸大的标题", "选最长的选项，因为信息更全", "选只出现一次的新词所在的选项", "选与第一句完全一样的选项"], 0, "标题的依据是话题词加核心观点。范围太窄（只覆盖一段）或太宽（超出文章）都要排除，这正是第 3 步比对范围和程度的用武之地。", "迁移"),
        q("inj3-j3-reading-types", "j3-reading-types", "【原文取证法】做阅读题之前，第一步做什么？",
          ["先通读全文并背下所有细节", "先读题干判断题型（细节、主旨、推理、词义、标题），再决定取证方式", "先按选项长度排除两个", "先读最后一段，因为结尾最重要"], 1, "第 1 步定题型：细节题定位划线、主旨题看首末句与重复词、推理题找依据再推断、词义题看上下文、标题题看话题词与观点。题型判断对了，取证方式才对。", "方法"),
        q("inj3-j3-relative", "j3-relative", "【主干手术法】分析 The boy who won the game is my friend. 第一步做什么？",
          ["把 who 当成主语，找它后面的谓语", "按单词顺序逐词翻译", "先找主句谓语 is，把 who won the game 这段从句括起来，主干是 The boy is my friend", "先把从句改成疑问句"], 2, "第 1 步找谓语：主句谓语是 is，从句谓语是 won。去掉从句后主干是 The boy is my friend.，句意立刻清晰。长句看不懂时，先做这一步一定有效。", "方法"),
        q("inj3-j3-relative-choice", "j3-relative-choice", "【对比归类法】对比 who / which / whose / that，第 2 步列什么条件？",
          ["所有情况都用 that", "按先行词长短选择关系词", "只记 which 指物，指人的不用管", "列条件：先行词指人用 who 或 that，指物用 which 或 that，表所属用 whose，作宾语可省略"], 3, "关系词的分界条件是“先行词指什么 + 在从句中作什么成分”：指人用 who、指物用 which、表所属用 whose、作宾语可省略。条件列清，定语从句选择题一步定位。", "辨析"),
        q("inj3-j3-sequence", "j3-sequence", "【对比归类法】对比 first / next / then / finally，第 2 步列什么条件？",
          ["把四个都记成“然后”", "按字母顺序排列记忆", "列顺序条件：起点、承接、过渡、结束，用于组织过程或事件", "只记 first，其他靠语感"], 2, "顺序词的分界在过程中的位置：First 起点、Next 与 Then 承接过渡、Finally 结束。列清条件，做事件顺序题和写过程说明时都能直接调用。", "辨析"),
        q("inj3-j3-summary", "j3-summary", "【原文取证法】做阅读推断题，第一步做什么？",
          ["凭常识直接选看起来合理的选项", "选与原文词汇重复最多的选项", "先看选项再决定读不读原文", "先读题干划关键词，判断问的是事实、观点还是推断"], 3, "第 1 步先定题型。推断题不能选原文原句复述（那是事实题答案），要选由依据句合理推出的结论；第 3 步比对时特别注意 must、all 这类过强的表述。", "方法"),
        q("inj3-j3-synonyms", "j3-synonyms", "【原文取证法】题干用 quick，原文写 fast，应该怎么处理？",
          ["找不到 quick 就认为原文没有相关信息", "只找字母完全相同的词", "跳过题干直接读全文", "把题干关键词 quick 与原文的 fast 做同义比对，确认是同一处信息后再作答"], 3, "同义替换是阅读题的核心设置方式：题干词与原文词不一定相同。第 2 步定位时要用“意思”而不是“拼写”去匹配，quick 等于 fast，buy 等于 purchase。", "迁移"),
        q("inj3-j3-conditional-review", "j3-conditional-review", "【对比归类法】对比 If you study, you will improve. 和 Study, and you will improve.，第 2 步列什么条件？",
          ["列条件：if 从句用一般现在时表将来（主将从现），祈使句加 and 或 or 也能表条件与结果", "在 if 从句里也加 will", "把 and 换成 but", "把两句都改成过去时"], 0, "条件句的分界条件是结构形式：if 从句加主将从现，或祈使句加 and 加结果。两条路表达同一逻辑。列清条件，改写题就不会把 will 塞进 if 从句。", "辨析"),
        q("inj3-j3-passive-tenses", "j3-passive-tenses", "【对比归类法】对比 The bridge will be built. 和 The bridge was built.，第 2 步列什么条件？",
          ["把 built 换成 building 表将来", "在 be 后面加 to 表将来", "按句子长短选择时态", "列条件：被动语态的时态由 be 体现，be 的时态随句意变化，过去分词不变"], 3, "被动的时态信息全在 be 上：will be built（将来）、was built（过去）、is being built（此刻）。过去分词始终不变。列清这个条件，被动时态题只需判断时间。", "辨析"),
        q("inj3-j3-perfect", "j3-perfect", "【时间标志法】句子 I ___ (finish) my work already. 填空，第一步做什么？",
          ["先把 finish 改成 finished，因为已经完成", "先看主语 I，用 am finished", "先猜一个形式读一遍顺口就定", "先圈出 already，确定用现在完成时，再写 have finished"], 3, "already、yet、ever、never、just 是现在完成时的标志。第 1 步圈标志，第 3 步核对主语 I 用 have，动词用过去分词 finished。三步走完再落笔。", "方法"),
        q("inj3-j3-perfect-continuity", "j3-perfect-continuity", "【时间标志法】句子 I ___ (live) here for five years. 填空，第一步做什么？",
          ["先看主语 I，用一般现在时 live", "把 for 换成 since 再用一般过去时", "先圈出 for five years，确定用现在完成时并选延续性动词 have lived", "先猜一个形式，读一遍顺口就定"], 2, "for 加时间段、since 加起点都是完成时（持续用法）的标志。第 1 步圈标志，第 4 步核对动词是否延续性（live、study、work 可用，come、go 这类瞬间动词不能搭配 for）。", "方法"),
        q("inj3-j3-tenses-review", "j3-tenses-review", "【对比归类法】对比 since / for / already / yet，第 2 步列什么条件？",
          ["把四个都记成“已经”", "把 since 和 for 互换使用", "只记 already，其他靠语感", "列条件：since 接起点，for 接时长，already 用于肯定句，yet 用于否定句和疑问句"], 3, "完成时的时间标志靠条件分界：since 2020（起点）、for two years（时长）、already（肯定句）、yet（否定与疑问句）。条件列清，时态综合题先圈标志再定时态。", "辨析"),
        q("inj3-j3-context", "j3-context", "【原文取证法】遇到生词 unhappy 不知道意思，应该怎么做？",
          ["直接看选项里出现的中文", "先回上下文找线索：un- 表示“不”，happy 表示“高兴”，再用本句语境确认", "按拼写猜一个发音相近的词", "跳过这个词，全句看不懂就算了"], 1, "语境猜词也是取证：依据在构词（un- 表否定）和上下文（同义或反义复现）。第 2 步把线索划出来，第 3 步用线索验证猜测，比乱猜靠谱得多。", "迁移"),
        q("inj3-j3-phrasal", "j3-phrasal", "【对比归类法】对比 take care of / take off / take up，第 2 步列什么条件？",
          ["列条件：take 后接不同小词，含义完全不同，必须按短语整体记", "只记 take 的意思是“拿”", "把三个短语拆成单词分别背", "按短语长度排序记忆"], 0, "动词短语的分界在小词：take care of 照顾、take off 起飞或脱下、take up 开始从事。整体记搭配，第 3 步再配一个自己的例句，写作文时才敢用。", "辨析"),
        q("inj3-j3-word-building", "j3-word-building", "【对比归类法】对比 careful / careless / carefully，第 2 步列什么条件？",
          ["把三个都记成“仔细”", "列条件：-ful 表“充满”构成形容词，-less 表“没有”构成形容词，-ly 常构成副词", "按后缀长度来选择", "只记 careful，其他遇到再说"], 1, "构词法的分界在后缀含义：-ful 有、-less 无、-ly 副词、-ness 名词。列清条件后，即使不认识新词，也能靠词根加词缀猜出词性和大意。", "辨析"),
        q("inj3-j3-inversion", "j3-inversion", "【对比归类法】对比 It was Tom who helped me. 和 Tom helped me.，第 2 步列什么条件？",
          ["把 Tom 提到句首就是倒装", "列条件：强调句用 It is/was + 被强调部分 + that/who + 其余部分，去掉强调结构后句子仍完整", "在句尾加 only 表示强调", "按句子长短判断是不是强调句"], 1, "强调句的判据是“去掉 It is/was…that 后句子仍完整”：Tom helped me. 成立，所以是强调句。列清这个条件，识别题就能一步判定。", "辨析"),
        q("inj3-j3-modal-passive", "j3-modal-passive", "【对比归类法】对比 Rules must be followed. 和 Rules must follow.，第 2 步列什么条件？",
          ["情态动词后直接加 -ed 表被动", "列条件：主语是动作承受者时用“情态动词 + be + 过去分词”", "把 must 写成 musts 表被动", "按主语单复数判断要不要被动"], 1, "情态动词被动的形式固定：must、should、can + be + 过去分词。主语 Rules 是被遵守的对象，所以用 must be followed。列清条件，形式题不用猜。", "辨析"),
        q("inj3-j3-passive", "j3-passive", "【对比归类法】对比 The book was written in 2020. 和 He wrote the book.，第 2 步列什么条件？",
          ["看到 in 2020 就选被动", "列条件：强调动作承受者用被动（be + 过去分词），强调执行者用主动", "按主语是人还是物判断主动被动", "按句子长度来选择"], 1, "被动的形式是 be + 过去分词，be 的人称与时态随句意变化；主动还是被动取决于想说谁。列清条件后，语态题先问自己“谁做动作”。", "辨析"),
        q("inj3-j3-tag", "j3-tag", "【对比归类法】对比 You like English, don't you? 和 You don't like English, do you?，第 2 步列什么条件？",
          ["两句都用 don't you", "列条件：前肯后否、前否后肯，且附加问句的助动词与主语跟主句一致", "按主句长短决定附加部分的形式", "只记前肯后否一种情况"], 1, "分界在主句是肯定还是否定，再加上助动词与主语一致这两个核查点。主句用 like（实义动词、一般现在时、主语 you），所以附加部分用 don't you 或 do you。", "辨析"),
    ]

    /// 全部 145 道方法题，覆盖 145 个知识点，每个知识点 1 道。
    static let all: [KnowledgePracticeQuestion] =
        primaryBatch + juniorOneBatch + juniorTwoBatch + juniorThreeBatch

    private static func q(_ id: String, _ point: String, _ prompt: String,
                          _ options: [String], _ answer: Int,
                          _ explanation: String, _ kind: String) -> KnowledgePracticeQuestion {
        KnowledgePracticeQuestion(id: id, knowledgePointID: point, prompt: prompt,
                                  options: options, answer: answer,
                                  explanation: explanation, kind: kind)
    }
}
