import Foundation

/// 高频考点库（基于考纲高频统计整理）。狙击算法在此之上为你排序。
enum HighFreqData {

    static let all: [HighFreqPoint] = {
        var r: [HighFreqPoint] = []
        r += grammar; r += clozePoints; r += readingPoints
        r += sevenPoints; r += writingPoints; r += continuationPoints
        r += extra; r += round2
        return r
    }()

    static let grammar: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_nonfinite", module: .grammarFill, name: "非谓语动词",
            frequencyWeight: 0.95,
            digest: "句中已有谓语→空格八成填非谓语：主动进行 -ing，被动/完成 -ed，目的/将来 to do。",
            example: "___ (see) from space, the Earth looks blue. → Seen（地球被看，用过去分词）",
            linkedLevelId: "L1", linkedQuestionIds: ["g2"]),
        HighFreqPoint(id: "hf_attributive", module: .grammarFill, name: "定语从句关系词",
            frequencyWeight: 0.85,
            digest: "先行词指物 which/that、指人 who；表所属 whose；表地点/抽象语境 where。",
            example: "the scientist ___ research changed the field → whose",
            linkedLevelId: "L1", linkedQuestionIds: ["g6"]),
        HighFreqPoint(id: "hf_tense", module: .grammarFill, name: "时态呼应",
            frequencyWeight: 0.80,
            digest: "By the time + 过去 → 主句过去完成；抓 this/last/ago 等时间标志定时态。",
            example: "By the time he arrived, they ___ (wait) for an hour. → had waited",
            linkedLevelId: "L1", linkedQuestionIds: ["g5"]),
        HighFreqPoint(id: "hf_subjunctive", module: .grammarFill, name: "虚拟语气",
            frequencyWeight: 0.60,
            digest: "与过去相反：if had done, would have done；与现在相反：if did, would do。",
            example: "If I ___ (have) time, I would have finished. → had had",
            linkedLevelId: "L1", linkedQuestionIds: ["g8"]),
    ]

    static let clozePoints: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_logic", module: .cloze, name: "逻辑关联词",
            frequencyWeight: 0.90,
            digest: "however 转折 / therefore 因果 / besides 递进 / otherwise 否则——先判前后语义方向再选。",
            example: "She prepared well; ___, she still felt nervous. → however",
            linkedLevelId: "L2", linkedQuestionIds: ["c1", "c5"]),
        HighFreqPoint(id: "hf_verbdiff", module: .cloze, name: "动词与固定搭配辨析",
            frequencyWeight: 0.85,
            digest: "锁定固定搭配与语境：make every effort、overcome one's fear——搭配优先于词义。",
            example: "He finally ___ his fear. → overcame",
            linkedLevelId: "L2", linkedQuestionIds: ["c2", "c6"]),
    ]

    static let readingPoints: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_polysemy", module: .reading, name: "熟词僻义",
            frequencyWeight: 0.80,
            digest: "高频僻义：address 解决、last 持续、figure 人物、subject 使遭受——结合语境别用第一义。",
            example: "We must address the problem. → address = 解决（非‘地址’）",
            linkedLevelId: "L4", linkedQuestionIds: ["r4", "r8"]),
        HighFreqPoint(id: "hf_inference", module: .reading, name: "推理判断",
            frequencyWeight: 0.90,
            digest: "推理＝有据：由原文事实小步推断，拒绝过度引申与无中生有。",
            example: "原文 knew no one → 可推 lonely（有据），不可推 angry（无据）",
            linkedLevelId: "L4", linkedQuestionIds: ["r3", "r7"]),
        HighFreqPoint(id: "hf_wordguess", module: .reading, name: "词义猜测",
            frequencyWeight: 0.75,
            digest: "靠上下文、同位解释、对比、构词法猜义，别凭字面直译。",
            example: "a place to belong → 被接纳的归属感（非字面‘一块地’）",
            linkedLevelId: "L4", linkedQuestionIds: ["r4", "r8"]),
    ]

    static let sevenPoints: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_cohesion", module: .sevenChoose, name: "衔接信号",
            frequencyWeight: 0.85,
            digest: "代词 them/it 找对应单复数先行词；For example/However/As a result 直接定位逻辑。",
            example: "空后 Many of them… → 前句须出现复数名词",
            linkedLevelId: "L3", linkedQuestionIds: ["s2", "s4"]),
    ]

    static let writingPoints: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_advsentence", module: .appliedWriting, name: "高级句式",
            frequencyWeight: 0.85,
            digest: "强调句 It is…that、倒装 Not only…、非谓语作状语——一篇用 1-2 个即提档。",
            example: "Not only did she finish early, but she also helped others.",
            linkedLevelId: "L5", linkedQuestionIds: ["a2"]),
        HighFreqPoint(id: "hf_transition", module: .appliedWriting, name: "过渡衔接词",
            frequencyWeight: 0.80,
            digest: "What's more / In addition 递进，however 转折，as a result 结果——给文章逻辑链。",
            example: "What's more, the activity will build our teamwork.",
            linkedLevelId: "L5", linkedQuestionIds: ["a5"]),
    ]

    static let continuationPoints: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_psych", module: .continuation, name: "心理描写句式",
            frequencyWeight: 0.80,
            digest: "化情绪为身体反应：A chill ran down his spine / A wave of joy washed over him。",
            example: "A wave of joy washed over him as he read the letter.",
            linkedLevelId: "L6", linkedQuestionIds: ["k2", "k4"]),
        HighFreqPoint(id: "hf_plotchain", module: .continuation, name: "情节链衔接",
            frequencyWeight: 0.70,
            digest: "Just then / At that moment 推进当下；承接上文，不跳脱时间线。",
            example: "Just then, a flashlight beam cut through the darkness.",
            linkedLevelId: "L6", linkedQuestionIds: ["k3"]),
    ]

    /// 二期补充高频考点（14 → 30）。
    static let extra: [HighFreqPoint] = extraA + extraB + extraC

    static let extraA: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_svagree", module: .grammarFill, name: "主谓一致",
            frequencyWeight: 0.75,
            digest: "the number of + 单数；a number of + 复数；nor/or 连接看就近原则。",
            example: "The number of students was surprising.",
            linkedLevelId: "L1", linkedQuestionIds: ["g3", "g11"]),
        HighFreqPoint(id: "hf_inversion", module: .grammarFill, name: "倒装句",
            frequencyWeight: 0.65,
            digest: "否定副词(Never/Not until/Only)置于句首→主句部分倒装：助动词提前。",
            example: "Never before had I seen such a sight.",
            linkedLevelId: "L1", linkedQuestionIds: ["g9", "g12"]),
        HighFreqPoint(id: "hf_nounclause", module: .grammarFill, name: "名词性从句",
            frequencyWeight: 0.70,
            digest: "what 引导且充当成分；that 只连接不充当成分；whether/if 表‘是否’。",
            example: "I can't decide what to wear. （what 作 wear 的宾语）",
            linkedLevelId: "L1", linkedQuestionIds: ["g10"]),
        HighFreqPoint(id: "hf_comparison", module: .grammarFill, name: "比较结构",
            frequencyWeight: 0.60,
            digest: "the more…the more；as…as；倍数 + as…as / 比较级。",
            example: "The more you practice, the better you become.",
            linkedLevelId: "L1", linkedQuestionIds: ["g14"]),
        HighFreqPoint(id: "hf_phrasalverb", module: .cloze, name: "高频动词短语",
            frequencyWeight: 0.80,
            digest: "come up with 想出 / look after 照顾 / put off 推迟 / give up 放弃——成片记忆。",
            example: "She managed to come up with a clever solution.",
            linkedLevelId: "L2", linkedQuestionIds: ["c13"]),
    ]

    static let extraB: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_advdiff", module: .cloze, name: "副词辨析",
            frequencyWeight: 0.70,
            digest: "clearly / hardly / rarely / barely 语义差异大，先判句意正负向再选。",
            example: "He spoke clearly so that everyone could follow.",
            linkedLevelId: "L2", linkedQuestionIds: ["c10"]),
        HighFreqPoint(id: "hf_mainidea", module: .reading, name: "主旨大意",
            frequencyWeight: 0.85,
            digest: "抓首段末段与反复出现的高频词，归纳主题而非纠缠细节。",
            example: "全文反复出现 friends/belong → 主旨选‘归属感’",
            linkedLevelId: "L4", linkedQuestionIds: ["r2", "r6", "r11"]),
        HighFreqPoint(id: "hf_detailloc", module: .reading, name: "细节定位",
            frequencyWeight: 0.85,
            digest: "用题干关键词回原文定位，警惕同义改写与张冠李戴。",
            example: "Every Saturday → planted vegetables with neighbors",
            linkedLevelId: "L4", linkedQuestionIds: ["r1", "r5", "r10"]),
        HighFreqPoint(id: "hf_opening", module: .appliedWriting, name: "应用文开头模板",
            frequencyWeight: 0.80,
            digest: "I'm writing to invite / express / suggest…——按写作目的选框架，开门见山。",
            example: "I'm writing to express my sincere thanks for your help.",
            linkedLevelId: "L5", linkedQuestionIds: ["a1", "a9"]),
        HighFreqPoint(id: "hf_actiondetail", module: .continuation, name: "动作细节",
            frequencyWeight: 0.75,
            digest: "连续强动词串联动作：grabbed…threw on…dashed out，节奏感即画面感。",
            example: "She grabbed her bag, threw on her coat, and dashed out.",
            linkedLevelId: "L6", linkedQuestionIds: ["k5", "k11"]),
    ]

    static let extraC: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_passive", module: .grammarFill, name: "被动语态",
            frequencyWeight: 0.70,
            digest: "主语是动作承受者→被动 be + 过去分词；with 复合结构同理用过去分词。",
            example: "With the work done, she left. （work 被完成）",
            linkedLevelId: "L1", linkedQuestionIds: ["g15"]),
        HighFreqPoint(id: "hf_adjdiff", module: .cloze, name: "形容词辨析",
            frequencyWeight: 0.70,
            digest: "形容词要与语境情感同向：harsh/pleasant、willing/reluctant，先判正负再选。",
            example: "Despite the harsh weather, they pressed on.",
            linkedLevelId: "L2", linkedQuestionIds: ["c3", "c7", "c14"]),
        HighFreqPoint(id: "hf_concession", module: .cloze, name: "让步逻辑",
            frequencyWeight: 0.65,
            digest: "Although/Despite/However 表让步：前后语义相反时优先考虑。",
            example: "Although exhausted, she refused to give up.",
            linkedLevelId: "L2", linkedQuestionIds: ["c8", "c15"]),
        HighFreqPoint(id: "hf_attitude", module: .reading, name: "作者态度/情感",
            frequencyWeight: 0.70,
            digest: "抓评价性词与语气(laughed/sadly)，区分 positive/negative/objective。",
            example: "she laughed, \"but they are mine\" → 自豪(positive)",
            linkedLevelId: "L4", linkedQuestionIds: ["r13"]),
        HighFreqPoint(id: "hf_ending", module: .appliedWriting, name: "结尾礼貌句",
            frequencyWeight: 0.75,
            digest: "Looking forward to your reply / I would appreciate it if…——收束得体加分。",
            example: "I'm looking forward to hearing from you soon.",
            linkedLevelId: "L5", linkedQuestionIds: ["a3", "a6"]),
        HighFreqPoint(id: "hf_setting", module: .continuation, name: "环境描写",
            frequencyWeight: 0.70,
            digest: "用环境烘托情绪：风声/光线/天气 + 拟人化动词，as 引导伴随。",
            example: "The wind howled through the empty street as midnight drew near.",
            linkedLevelId: "L6", linkedQuestionIds: ["k1", "k7"]),
    ]

    static func find(_ id: String) -> HighFreqPoint? { all.first { $0.id == id } }

    /// 三期补充高频考点（30 → 56），覆盖七选五等此前过薄的模块，并为应用文六体裁/续写补齐细分技巧点。
    static let round2: [HighFreqPoint] = round2Grammar + round2Cloze + round2Reading
        + round2Seven + round2Writing + round2Continuation

    static let round2Grammar: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_modal", module: .grammarFill, name: "情态动词推测",
            frequencyWeight: 0.70,
            digest: "有依据的肯定推测用 must；可能性用 may/might；强烈质疑用否定推测 can't。",
            example: "The light is still on; she ___ be working late. → must（灯亮=有依据）",
            linkedLevelId: "L1", linkedQuestionIds: ["g16"]),
        HighFreqPoint(id: "hf_prepfixed", module: .grammarFill, name: "介词固定搭配",
            frequencyWeight: 0.75,
            digest: "be good at／depend on／focus on——固定搭配的介词不能凭中文直译猜。",
            example: "Whether you succeed largely depends ___ how hard you work. → on",
            linkedLevelId: "L1", linkedQuestionIds: ["g7", "g13"]),
        HighFreqPoint(id: "hf_absolute", module: .grammarFill, name: "独立主格结构",
            frequencyWeight: 0.55,
            digest: "逗号前是‘名词+分词’且逻辑主语与主句不同→独立主格：主动用 -ing，被动/完成用 -ed。",
            example: "The sun having set, the temperature dropped sharply.",
            linkedLevelId: "L1", linkedQuestionIds: ["g29", "g15"]),
        HighFreqPoint(id: "hf_adverbialconn", module: .grammarFill, name: "状语从句逻辑词",
            frequencyWeight: 0.65,
            digest: "Once 一旦／Unless 除非／Whereas 然而——先判前后句的逻辑关系再选连词。",
            example: "Once you understand the rule, the rest becomes much easier.",
            linkedLevelId: "L1", linkedQuestionIds: ["g24"]),
        HighFreqPoint(id: "hf_article", module: .grammarFill, name: "冠词 a/an/the",
            frequencyWeight: 0.45,
            digest: "a/an 看读音不看字母：useful 开头辅音音素 /j/ 仍用 a；特指或独一无二的事物用 the。",
            example: "What ___ useful piece of advice! → a（useful 读音以辅音 /j/ 开头）",
            linkedLevelId: "L1", linkedQuestionIds: ["g17"]),
    ]

    static let round2Cloze: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_noundiff", module: .cloze, name: "名词辨析",
            frequencyWeight: 0.65,
            digest: "抓住前后行为推断情感色彩：苦练数小时透出的是 passion(热情)而非 doubt/fear。",
            example: "His ___ for music drove him to practice six hours a day. → passion",
            linkedLevelId: "L2", linkedQuestionIds: ["c17"]),
        HighFreqPoint(id: "hf_prepphrase", module: .cloze, name: "介词短语固定搭配",
            frequencyWeight: 0.70,
            digest: "thanks to(多亏)／in spite of(尽管)／regardless of(不顾)——先判语义方向再选介词短语。",
            example: "The project succeeded, thanks to the whole team's effort.",
            linkedLevelId: "L2", linkedQuestionIds: ["c16", "c27"]),
        HighFreqPoint(id: "hf_emotionword", module: .cloze, name: "情感正负词选择",
            frequencyWeight: 0.60,
            digest: "先判断上下文事件的褒贬方向，再选同方向的形容词/名词，排除反向干扰项。",
            example: "He gives away his old books for free; everyone calls him ___. → generous",
            linkedLevelId: "L2", linkedQuestionIds: ["c21"]),
        HighFreqPoint(id: "hf_synonymtrap", module: .cloze, name: "近义词陷阱",
            frequencyWeight: 0.65,
            digest: "eager/willing(乐意) 与 reluctant(不情愿) 词义相近却方向相反——细节决定方向，不可只凭印象选。",
            example: "He was clearly ___ to admit his mistake, mumbling excuses. → reluctant",
            linkedLevelId: "L2", linkedQuestionIds: ["c25"]),
    ]

    static let round2Reading: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_titlechoice", module: .reading, name: "标题选择",
            frequencyWeight: 0.80,
            digest: "标题须概括全文人物+主题，排除只是某个情节细节或片面信息的选项。",
            example: "全文写 68 岁奶奶开始识字学习 → 标题选‘永远不晚’而非‘如何写信’",
            linkedLevelId: "L4", linkedQuestionIds: ["r6", "r11", "r19"]),
        HighFreqPoint(id: "hf_paragraphfunc", module: .reading, name: "段落作用/论证功能",
            frequencyWeight: 0.65,
            digest: "问‘为什么提到…’多考论证功能：是补充原因、举例还是转折，别选成‘作者建议/态度’类误判。",
            example: "提到 tall buildings blocking wind → 是在补充加剧热岛效应的另一因素",
            linkedLevelId: "L4", linkedQuestionIds: ["r32", "r34"]),
        HighFreqPoint(id: "hf_databreakdown", module: .reading, name: "数据细节定位",
            frequencyWeight: 0.55,
            digest: "数字类细节题直接回原文定位关键句，警惕文中出现的其他干扰数字(不同时间点/不同对象)。",
            example: "How many prototypes failed? 回文定位 three failed prototypes → Three",
            linkedLevelId: "L4", linkedQuestionIds: ["r5", "r22", "r28"]),
    ]

    static let round2Seven: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_topicsentence", module: .sevenChoose, name: "总起/总结句定位",
            frequencyWeight: 0.80,
            digest: "空后跟 First…Then… 或空前是 In short 等总结语→该空应是统领全段的总起/总结句。",
            example: "___ First, choose a quiet place. Then, set a clear goal. → Here are some tips for studying effectively.",
            linkedLevelId: "L3", linkedQuestionIds: ["s5", "s12"]),
        HighFreqPoint(id: "hf_causeeffect7", module: .sevenChoose, name: "因果逻辑链",
            frequencyWeight: 0.75,
            digest: "看到 As a result/therefore，空处应是导致该结果的直接原因，而非无关或矛盾的陈述。",
            example: "___ As a result, the floods stopped happening. → The roots held the soil firmly in place.",
            linkedLevelId: "L3", linkedQuestionIds: ["s14", "s27"]),
        HighFreqPoint(id: "hf_refconsistency", module: .sevenChoose, name: "代词/数字指代一致",
            frequencyWeight: 0.70,
            digest: "空后出现 They/Their/it 等代词，空处补的句子必须包含对应单复数先行词，话题不能跳。",
            example: "Volunteers cleaned the beach. ___ Their hard work paid off. → They collected over a hundred bags of trash.",
            linkedLevelId: "L3", linkedQuestionIds: ["s10"]),
        HighFreqPoint(id: "hf_trapdistractor", module: .sevenChoose, name: "干扰项特征识别",
            frequencyWeight: 0.60,
            digest: "干扰项常见两种坑：与上下文事实矛盾，或话题/指代对象跑偏——读完前后句先排除这两类。",
            example: "‘排队抢购’的前一句若选‘涨价/关门’，与结果矛盾，直接排除。",
            linkedLevelId: "L3", linkedQuestionIds: ["s25", "s27"]),
    ]

    static let round2Writing: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_aw_suggest", module: .appliedWriting, name: "建议信句式",
            frequencyWeight: 0.70,
            digest: "I am writing to suggest that…／May I suggest doing…?——建议要委婉，避免 should/must 式命令语气。",
            example: "May I suggest adding more speaking practice to the class?",
            linkedLevelId: "L5", linkedQuestionIds: ["a8", "a16"]),
        HighFreqPoint(id: "hf_aw_thanks", module: .appliedWriting, name: "感谢信细节化",
            frequencyWeight: 0.65,
            digest: "先用 grateful for 概括感谢，再用 In particular 过渡到一个具体细节，避免空泛笼统。",
            example: "In particular, I really enjoyed the cultural workshop on the second day.",
            linkedLevelId: "L5", linkedQuestionIds: ["a18", "a28"]),
        HighFreqPoint(id: "hf_aw_apology", module: .appliedWriting, name: "道歉信句式",
            frequencyWeight: 0.65,
            digest: "apologize for (not) doing 点明致歉事由；委婉拒绝用 I'm afraid + but thank you for… 缓和语气。",
            example: "I'm writing to apologize for not being able to make it to your party.",
            linkedLevelId: "L5", linkedQuestionIds: ["a13", "a24"]),
        HighFreqPoint(id: "hf_aw_notice", module: .appliedWriting, name: "通知信息要素",
            frequencyWeight: 0.70,
            digest: "通知必须信息完整：对象+事项+时间+地点一句给全，列举多项用 In addition/Besides 衔接。",
            example: "In addition, we will visit the local science museum in the afternoon.",
            linkedLevelId: "L5", linkedQuestionIds: ["a14"]),
        HighFreqPoint(id: "hf_aw_lostfound", module: .appliedWriting, name: "寻物启事/海报要素",
            frequencyWeight: 0.55,
            digest: "寻物启事/海报类同样要素优先：物品特征+丢失(或活动)时间+地点一句说清，避免情绪化空话。",
            example: "I lost my black backpack somewhere near the school library yesterday afternoon.",
            linkedLevelId: "L5", linkedQuestionIds: ["a25"]),
        HighFreqPoint(id: "hf_aw_appeal", module: .appliedWriting, name: "委婉呼吁结尾",
            frequencyWeight: 0.60,
            digest: "反映问题类信件结尾用 sincerely hope + can be improved 的被动语态表达期望，避免生硬或带威胁意味。",
            example: "I sincerely hope the canteen service can be improved soon.",
            linkedLevelId: "L5", linkedQuestionIds: ["a27"]),
    ]

    static let round2Continuation: [HighFreqPoint] = [
        HighFreqPoint(id: "hf_dialogue", module: .continuation, name: "对话表现人物",
            frequencyWeight: 0.70,
            digest: "直接引语+伴随动作比间接转述更有现场感：whispered/gripping 比 she said 更传神。",
            example: "\"We can't give up now,\" she whispered, gripping his hand tightly.",
            linkedLevelId: "L6", linkedQuestionIds: ["k8", "k20"]),
        HighFreqPoint(id: "hf_echo", module: .continuation, name: "首尾呼应",
            frequencyWeight: 0.65,
            digest: "结尾呼应开头给出的意象或情绪(如雨/担忧)，用 just like 等关联词把意象与心情挂钩，升华主题。",
            example: "By the time he got home, the rain had finally stopped, just like his worries.",
            linkedLevelId: "L6", linkedQuestionIds: ["k28", "k30"]),
        HighFreqPoint(id: "hf_suspense", module: .continuation, name: "悬念铺垫",
            frequencyWeight: 0.60,
            digest: "用未解的疑问、突然的寂静或逼近的脚步声留白，比直接说破‘紧张/害怕’更抓人。",
            example: "A heavy silence fell over the classroom as every eye turned to the door.",
            linkedLevelId: "L6", linkedQuestionIds: ["k14", "k16"]),
        HighFreqPoint(id: "hf_climaxpace", module: .continuation, name: "高潮节奏",
            frequencyWeight: 0.65,
            digest: "高潮处用连续强动词(grabbed→threw on→dashed)或群体反应(burst into cheers)制造画面与节奏感。",
            example: "She grabbed her bag, threw on her coat, and dashed out the door.",
            linkedLevelId: "L6", linkedQuestionIds: ["k11", "k15"]),
    ]
}
