import Foundation

/// 句式 / 词块库（图鉴 Tab）。读后续写与应用文的高分弹药，可加入复习。
enum PhraseBook {

    static let all: [PhraseCard] = base + extended + roundD

    static let base: [PhraseCard] = [
        // 读后续写·开头/画面
        PhraseCard(id: "p1", category: .continuationOpener,
            en: "Rain poured down as he stumbled along the muddy path.",
            zh: "雨倾盆而下，他踉跄地走在泥泞的小路上。",
            usage: "as 引导伴随动作，开篇即给画面与张力。"),
        PhraseCard(id: "p2", category: .continuationOpener,
            en: "Just then, a flashlight beam cut through the darkness.",
            zh: "就在那时，一道手电光划破黑暗。",
            usage: "Just then 推进当下情节，制造转机。"),
        PhraseCard(id: "p3", category: .continuationOpener,
            en: "A chill ran down his spine as the shadows closed in.",
            zh: "阴影逼近，一阵寒意顺着脊背蔓延。",
            usage: "化‘害怕’为身体反应，远胜直白的 afraid。"),
        // 高级动词替换
        PhraseCard(id: "p4", category: .advancedVerb,
            en: "improve / enhance（替换 make better）",
            zh: "提升、增强",
            usage: "improve our spoken English 比 make English better 更精准地道。"),
        PhraseCard(id: "p5", category: .advancedVerb,
            en: "tackle / address（替换 deal with）",
            zh: "解决、应对",
            usage: "tackle the problem 显书面、显功底。"),
        PhraseCard(id: "p6", category: .advancedVerb,
            en: "gaze / glance（替换 look）",
            zh: "凝视 / 瞥",
            usage: "续写描写视线时，精准动词更有画面感。"),
        // 加分句式
        PhraseCard(id: "p7", category: .sentencePattern,
            en: "Not only did she finish early, but she also helped others.",
            zh: "她不仅提前完成，还帮助了他人。",
            usage: "not only…but also 倒装，议论/记叙皆可加分。"),
        PhraseCard(id: "p8", category: .sentencePattern,
            en: "It was not until that moment that he understood.",
            zh: "直到那一刻他才明白。",
            usage: "not until 强调句，升级时间表达。"),
        PhraseCard(id: "p9", category: .sentencePattern,
            en: "However hard he tried, he never gave up.",
            zh: "无论多努力，他从不放弃。",
            usage: "However + adj/adv 让步状语，凸显人物品质。"),
        // 应用文模板句
        PhraseCard(id: "p10", category: .applied,
            en: "I'm writing to invite you to…",
            zh: "我写信是想邀请你参加……",
            usage: "邀请类应用文标准开头框架。"),
        PhraseCard(id: "p11", category: .applied,
            en: "I would appreciate it if you could…",
            zh: "如果你能……我将不胜感激。",
            usage: "含虚拟语气的礼貌结尾，语域正式、加分稳。"),
        PhraseCard(id: "p12", category: .applied,
            en: "Looking forward to your early reply.",
            zh: "期待你的尽早回复。",
            usage: "书信结尾固定礼貌句，规范得体。"),
    ]

    /// 二期扩充（12 → 30 张，新增熟词僻义档案）；三期补充应用文分体裁开头句（30 → 36 张）。
    static let extended: [PhraseCard] = extendedA + extendedB + extendedC

    static let extendedA: [PhraseCard] = [
        // 续写开头/画面
        PhraseCard(id: "p13", category: .continuationOpener,
            en: "The first rays of dawn crept over the silent hills.",
            zh: "第一缕晨光悄悄爬上寂静的山峦。",
            usage: "用拟人化动词 crept 写景，开篇即有画面。"),
        PhraseCard(id: "p14", category: .continuationOpener,
            en: "Her heart raced as the door creaked slowly open.",
            zh: "门吱呀着缓缓打开，她的心怦怦直跳。",
            usage: "环境(门声)+心理(心跳)并行，制造悬念。"),
        // 高级动词
        PhraseCard(id: "p15", category: .advancedVerb,
            en: "soar / plunge（替换 rise / fall）",
            zh: "骤升 / 骤降",
            usage: "写数据或情绪起伏，soar、plunge 更有张力。"),
        PhraseCard(id: "p16", category: .advancedVerb,
            en: "whisper / murmur（替换 say quietly）",
            zh: "低语 / 喃喃",
            usage: "续写对话时区分音量与情绪。"),
        PhraseCard(id: "p17", category: .advancedVerb,
            en: "grasp / seize（替换 take / hold）",
            zh: "紧抓 / 抓住",
            usage: "seize the chance 抓住机会，比 take 有力。"),
        // 加分句式
        PhraseCard(id: "p18", category: .sentencePattern,
            en: "No sooner had he sat down than the phone rang.",
            zh: "他刚坐下，电话就响了。",
            usage: "No sooner…than 倒装，写‘一……就……’。"),
        PhraseCard(id: "p19", category: .sentencePattern,
            en: "Such was her determination that nothing could stop her.",
            zh: "她的决心如此之大，没什么能阻挡她。",
            usage: "Such…that 倒装，突出程度，议论记叙皆宜。"),
        PhraseCard(id: "p20", category: .sentencePattern,
            en: "It was with great pride that she accepted the award.",
            zh: "她无比自豪地接过了奖项。",
            usage: "It was…that 强调句，强调状语更有感染力。"),
        // 应用文句
        PhraseCard(id: "p21", category: .applied,
            en: "I would be more than happy to help if needed.",
            zh: "如有需要，我非常乐意提供帮助。",
            usage: "表达意愿的礼貌高分句。"),
        PhraseCard(id: "p22", category: .applied,
            en: "Please don't hesitate to contact me for any details.",
            zh: "如需了解任何细节，请随时与我联系。",
            usage: "书信结尾的得体收束句。"),
    ]

    static let extendedB: [PhraseCard] = [
        // 熟词僻义档案（阅读高频陷阱）
        PhraseCard(id: "v1", category: .polysemy,
            en: "address　常义：地址",
            zh: "僻义：解决、处理",
            usage: "We must address the problem at once. 我们必须立即解决问题。"),
        PhraseCard(id: "v2", category: .polysemy,
            en: "last　常义：最后的",
            zh: "僻义：持续；最不可能的",
            usage: "The meeting lasted two hours. 会议持续了两小时。"),
        PhraseCard(id: "v3", category: .polysemy,
            en: "figure　常义：数字",
            zh: "僻义：人物；想出(figure out)",
            usage: "She is a key figure in the field. 她是该领域的重要人物。"),
        PhraseCard(id: "v4", category: .polysemy,
            en: "subject　常义：主题/科目",
            zh: "僻义：使遭受(subject to)",
            usage: "They were subjected to great pressure. 他们承受了巨大压力。"),
        PhraseCard(id: "v5", category: .polysemy,
            en: "content　常义：内容",
            zh: "僻义：满足的(be content with)",
            usage: "He is content with his simple life. 他满足于简朴的生活。"),
        PhraseCard(id: "v6", category: .polysemy,
            en: "novel　常义：小说",
            zh: "僻义：新颖的",
            usage: "It is a novel approach to the issue. 这是解决该问题的新颖方法。"),
        PhraseCard(id: "v7", category: .polysemy,
            en: "bear　常义：熊",
            zh: "僻义：忍受；承担",
            usage: "She had to bear the responsibility. 她不得不承担这份责任。"),
        PhraseCard(id: "v8", category: .polysemy,
            en: "second　常义：第二；秒",
            zh: "僻义：赞同、支持",
            usage: "I second your proposal. 我赞同你的提议。"),
    ]

    static let extendedC: [PhraseCard] = [
        // 应用文·分体裁开头句
        PhraseCard(id: "p23", category: .applied,
            en: "I'm writing to ask for your advice on how to prepare for the speech contest.",
            zh: "我写信是想就如何准备演讲比赛向你请教。",
            usage: "求助信标准开头，先点明求助内容再展开细节。"),
        PhraseCard(id: "p24", category: .applied,
            en: "I'm writing to offer a few suggestions on improving our school's recycling program.",
            zh: "我写信是想就改进学校的回收计划提几点建议。",
            usage: "建议信开头，直接点出建议主题，方便阅卷者快速定位文体。"),
        PhraseCard(id: "p25", category: .applied,
            en: "I'm writing to express my heartfelt thanks for your generous help last weekend.",
            zh: "我写信是想为你上周末的热心帮助表达由衷感谢。",
            usage: "感谢信开头，heartfelt 比 thank you very much 更书面、更有诚意。"),
        PhraseCard(id: "p26", category: .applied,
            en: "I'm writing to sincerely apologize for missing our appointment yesterday.",
            zh: "我写信是想为昨天错过我们的约定真诚致歉。",
            usage: "道歉信开头，sincerely apologize 比单纯的 sorry 更正式得体。"),
        PhraseCard(id: "p27", category: .applied,
            en: "This is to inform all students that the English speech contest will be held this Friday.",
            zh: "现通知全体学生，英语演讲比赛将于本周五举行。",
            usage: "通知类标准开头，This is to inform... 直接点出通知对象与事项。"),
        PhraseCard(id: "p28", category: .applied,
            en: "Those interested are welcome to sign up by emailing the Students' Union before Friday.",
            zh: "有意者可在周五前邮件联系学生会报名。",
            usage: "通知/海报类报名方式的标准表达，信息要素(方式+截止时间)一句给全。"),
    ]

    /// 三期扩充（36 → 68 张）：续写画面/高级动词/加分句式各 +6，应用文补六体裁结尾句 +6，熟词僻义 +8。
    static let roundD: [PhraseCard] = roundD1 + roundD2 + roundD3 + roundD4 + roundD5

    static let roundD1: [PhraseCard] = [
        // 续写开头/画面
        PhraseCard(id: "p29", category: .continuationOpener,
            en: "The old clock on the wall ticked loudly in the empty corridor.",
            zh: "走廊空荡荡的，墙上的旧钟滴答作响。",
            usage: "用环境声音衬托空旷与紧张，无需直接写'安静'二字。"),
        PhraseCard(id: "p30", category: .continuationOpener,
            en: "Snow had been falling since dawn, blanketing the village in silence.",
            zh: "雪从清晨就开始下，给整个村子盖上了一层寂静的白色。",
            usage: "用天气整体铺垫氛围，为接下来的情节定调。"),
        PhraseCard(id: "p31", category: .continuationOpener,
            en: "A single light flickered at the end of the long, narrow alley.",
            zh: "一盏孤灯在狭长的巷子尽头闪烁。",
            usage: "聚焦一个具体细节(灯)制造悬念与方向感，引导读者视线。"),
        PhraseCard(id: "p32", category: .continuationOpener,
            en: "The smell of burning wood drifted through the cool night air.",
            zh: "燃木的气味在清冷的夜空中弥漫开来。",
            usage: "用嗅觉细节增强画面真实感，是续写中常被忽略的感官维度。"),
        PhraseCard(id: "p33", category: .continuationOpener,
            en: "Thunder rumbled in the distance, promising a storm before nightfall.",
            zh: "远处雷声隆隆，预示着夜幕降临前将有一场风暴。",
            usage: "用天气变化铺垫即将发生的转折，给情节增加张力。"),
        PhraseCard(id: "p34", category: .continuationOpener,
            en: "Her footsteps echoed against the cold stone floor as she walked alone.",
            zh: "她独自走着，脚步声在冰冷的石地板上回响。",
            usage: "声音细节+孤独感画面并行开篇，容易让读者迅速代入。"),
    ]

    static let roundD2: [PhraseCard] = [
        // 高级动词替换
        PhraseCard(id: "p35", category: .advancedVerb,
            en: "shatter / crumble（替换 break）",
            zh: "粉碎，破碎 / 崩塌，瓦解",
            usage: "Her confidence shattered in that instant. 写情绪或信念瞬间崩溃，比 break 更有冲击力。"),
        PhraseCard(id: "p36", category: .advancedVerb,
            en: "linger / dwell on（替换 stay in one's mind）",
            zh: "萦绕，徘徊 / 沉浸于(回忆、情绪)",
            usage: "The memory lingered in her mind for days. 比 stayed 更含蓄、更有余味。"),
        PhraseCard(id: "p37", category: .advancedVerb,
            en: "tremble / quiver（替换 shake）",
            zh: "颤抖 / 微微发抖",
            usage: "His hands trembled as he opened the letter. 写紧张或寒冷时的身体反应，比 shake 更精准细腻。"),
        PhraseCard(id: "p38", category: .advancedVerb,
            en: "drift（替换 think randomly / float slowly）",
            zh: "(思绪)飘移，游离 / (物体)漂流",
            usage: "Her thoughts drifted back to that summer afternoon. 写思绪不自觉地回到某段记忆。"),
        PhraseCard(id: "p39", category: .advancedVerb,
            en: "vanish / fade（替换 disappear）",
            zh: "突然消失 / 逐渐淡去",
            usage: "vanish 强调瞬间消失，fade 强调慢慢淡去，比 disappear 更有画面层次。"),
        PhraseCard(id: "p40", category: .advancedVerb,
            en: "clutch / clasp（替换 hold tightly）",
            zh: "紧抓，紧握",
            usage: "She clutched the letter to her chest. 比 held it tightly 更有情绪张力。"),
    ]

    static let roundD3: [PhraseCard] = [
        // 加分句式
        PhraseCard(id: "p41", category: .sentencePattern,
            en: "Hardly had she finished speaking when the audience burst into applause.",
            zh: "她话音刚落，观众就爆发出了掌声。",
            usage: "Hardly…when 倒装，写'刚……就……'的紧密承接，比简单的 As soon as 更显文采。"),
        PhraseCard(id: "p42", category: .sentencePattern,
            en: "So determined was he that no failure could make him quit.",
            zh: "他如此坚定，没有任何失败能让他放弃。",
            usage: "So + 形容词 置于句首引发部分倒装，强调程度，适合塑造人物品质。"),
        PhraseCard(id: "p43", category: .sentencePattern,
            en: "What matters most is not the result, but the effort behind it.",
            zh: "最重要的不是结果，而是背后的努力。",
            usage: "What 引导的主语从句+ not…but… 句式，提升议论文/续写结尾的总结档次。"),
        PhraseCard(id: "p44", category: .sentencePattern,
            en: "Little did she know that this decision would change her whole life.",
            zh: "她不知道，这个决定将改变她的一生。",
            usage: "Little 置于句首引发部分倒装，制造命运感的叙述语气，续写埋伏笔常用。"),
        PhraseCard(id: "p45", category: .sentencePattern,
            en: "There is no denying that hard work always pays off in the end.",
            zh: "不可否认，努力终将得到回报。",
            usage: "There is no denying that… 强调句型，议论文/应用文总结句加分常用。"),
        PhraseCard(id: "p46", category: .sentencePattern,
            en: "Only when we lose something do we realize how precious it was.",
            zh: "只有当我们失去某物时，才会意识到它有多珍贵。",
            usage: "Only when 状语前置触发部分倒装，常用于续写结尾的哲理升华句。"),
    ]

    static let roundD4: [PhraseCard] = [
        // 应用文·分体裁结尾句（与 p23-p28 的开头句一一对应）
        PhraseCard(id: "p47", category: .applied,
            en: "I would be extremely grateful for any advice you could offer on this matter.",
            zh: "如果您能就此事给我提供任何建议，我将非常感激。",
            usage: "求助信结尾，礼貌地再次强调对建议的渴望，呼应 p23 的求助开头。"),
        PhraseCard(id: "p48", category: .applied,
            en: "I do hope you will take these suggestions into consideration.",
            zh: "真心希望您能考虑这些建议。",
            usage: "建议信结尾常用句，语气诚恳又不失分量，呼应 p24 的建议开头。"),
        PhraseCard(id: "p49", category: .applied,
            en: "Once again, thank you from the bottom of my heart for everything you did.",
            zh: "再次从心底感谢您所做的一切。",
            usage: "感谢信结尾强化感激之情，呼应 p25 的感谢开头，首尾呼应更完整。"),
        PhraseCard(id: "p50", category: .applied,
            en: "I promise this will never happen again, and I hope you can forgive me.",
            zh: "我保证这种事不会再发生，希望您能原谅我。",
            usage: "道歉信结尾的标配结构：给出保证 + 请求谅解，呼应 p26 的道歉开头。"),
        PhraseCard(id: "p51", category: .applied,
            en: "For further information, please feel free to contact the Students' Union.",
            zh: "如需了解更多信息，请随时联系学生会。",
            usage: "通知结尾的标准联系方式句，信息要素完整，呼应 p27 的通知开头。"),
        PhraseCard(id: "p52", category: .applied,
            en: "Don't miss this wonderful opportunity — see you there!",
            zh: "别错过这个精彩的机会——到时见！",
            usage: "海报结尾的号召性用语，简短有力，符合海报的视觉与语气特点，呼应 p28。"),
    ]

    static let roundD5: [PhraseCard] = [
        // 熟词僻义档案（续）
        PhraseCard(id: "v9", category: .polysemy,
            en: "object　常义：n. 物体",
            zh: "僻义：vi. 反对(object to sth)",
            usage: "Many local residents object to building a new airport nearby. 许多当地居民反对在附近新建机场。"),
        PhraseCard(id: "v10", category: .polysemy,
            en: "party　常义：n. 聚会",
            zh: "僻义：n. 一方，当事方",
            usage: "Both parties agreed to sign the contract by Friday. 双方都同意在周五前签署合同。"),
        PhraseCard(id: "v11", category: .polysemy,
            en: "right　常义：adj. 正确的；右边的",
            zh: "僻义：n. 权利",
            usage: "Every citizen has the right to a fair trial. 每个公民都有获得公正审判的权利。"),
        PhraseCard(id: "v12", category: .polysemy,
            en: "sound　常义：n. 声音",
            zh: "僻义：adj. 健全的，可靠的",
            usage: "Her plan was based on sound financial advice. 她的计划基于可靠的财务建议。"),
        PhraseCard(id: "v13", category: .polysemy,
            en: "run　常义：v. 跑",
            zh: "僻义：vt. 经营，管理",
            usage: "She has run this small bakery for over twenty years. 她经营这家小面包店已经二十多年了。"),
        PhraseCard(id: "v14", category: .polysemy,
            en: "check　常义：v. 检查",
            zh: "僻义：vt. 制止，抑制(check the spread of)",
            usage: "New measures were introduced to check the spread of the disease. 新措施被引入以抑制疾病的传播。"),
        PhraseCard(id: "v15", category: .polysemy,
            en: "point　常义：n. 点",
            zh: "僻义：n. 意义，作用(There's no point in doing sth)",
            usage: "There's no point in arguing about something we can't change. 争论我们无法改变的事毫无意义。"),
        PhraseCard(id: "v16", category: .polysemy,
            en: "book　常义：n. 书",
            zh: "僻义：vt. 预订",
            usage: "We managed to book the last two tickets for the evening show. 我们设法订到了晚场演出的最后两张票。"),
    ]

    static func cards(in category: PhraseCategory) -> [PhraseCard] {
        all.filter { $0.category == category }
    }
}
