import Foundation

/// 二期扩充题（第二批，接入 QuestionBank.all）。每关 +6 题，撑起刷题厚度。
extension QuestionBank {

    static let extended2: [Question] =
        grammarFill2 + cloze2 + sevenChoose2 + reading2 + applied2 + continuation2

    // MARK: 语法填空 g10–g15

    static let grammarFill2: [Question] = [
        Question(id: "g10", module: .grammarFill, levelId: "L1",
            stem: "I really can't decide ___ to wear to the graduation ceremony.",
            options: ["what", "that", "which", "whether"], answer: 0,
            pointTag: "名词性从句·what + to do",
            strategy: ["decide 后接宾语从句", "wear 缺宾语，需 what 充当", "what to wear = 穿什么"],
            trap: "that 不充当成分，无法做 wear 的宾语。", difficulty: 0.5),
        Question(id: "g11", module: .grammarFill, levelId: "L1",
            stem: "The number of students who passed the exam ___ surprising.",
            options: ["was", "were", "are", "being"], answer: 0,
            pointTag: "主谓一致·the number of",
            strategy: ["the number of = ‘……的数量’，作主语视为单数", "谓语用单数 was", "区别 a number of(许多)+复数"],
            trap: "被 students 复数干扰误填 were。", difficulty: 0.55),
        Question(id: "g12", module: .grammarFill, levelId: "L1",
            stem: "Never before ___ such a breathtaking sunrise.",
            options: ["had I seen", "I had seen", "I saw", "did I saw"], answer: 0,
            pointTag: "倒装·否定副词置首",
            strategy: ["Never 等否定副词置于句首", "主句部分倒装：助动词提到主语前", "had I seen"],
            trap: "不倒装 I had seen，或 did I saw 双重错误。", difficulty: 0.65),
        Question(id: "g13", module: .grammarFill, levelId: "L1",
            stem: "Whether you succeed largely depends ___ how hard you work.",
            options: ["on", "in", "at", "for"], answer: 0,
            pointTag: "固定搭配·depend on",
            strategy: ["depend on 固定搭配=取决于", "后接 how 引导的宾语从句", "depend on"],
            trap: "depend in/at 均不成立。", difficulty: 0.35),
        Question(id: "g14", module: .grammarFill, levelId: "L1",
            stem: "The more you practice, the ___ you will become.",
            options: ["better", "best", "good", "well"], answer: 0,
            pointTag: "比较级·the more…the more",
            strategy: ["the + 比较级…, the + 比较级… 句型", "第二空需形容词比较级作表语", "the better"],
            trap: "误用最高级 best 或原级 good。", difficulty: 0.4),
        Question(id: "g15", module: .grammarFill, levelId: "L1",
            stem: "With all the work ___, she finally went home to rest.",
            options: ["done", "doing", "do", "to do"], answer: 0,
            pointTag: "with 复合结构·过去分词",
            strategy: ["with + 宾语 + 非谓语 的独立结构", "work 与 do 是被动完成关系", "用过去分词 done"],
            trap: "doing 表主动进行，与‘工作被做完’矛盾。", difficulty: 0.6),
    ]

    // MARK: 完形填空 c10–c15

    static let cloze2: [Question] = [
        Question(id: "c10", module: .cloze, levelId: "L2",
            stem: "He explained the rules ___, so that everyone could follow.",
            options: ["clearly", "hardly", "rarely", "barely"], answer: 0,
            pointTag: "副词辨析",
            strategy: ["so that everyone could follow = 大家能跟上", "需正向副词 clearly", "排除否定意味的 hardly/rarely/barely"],
            trap: "hardly/barely 表‘几乎不’，使句意自相矛盾。", difficulty: 0.4),
        Question(id: "c11", module: .cloze, levelId: "L2",
            stem: "Her ___ to help strangers won everyone's respect.",
            options: ["willingness", "refusal", "failure", "fear"], answer: 0,
            pointTag: "名词辨析·语境正向",
            strategy: ["won everyone's respect = 赢得尊重→正面品质", "willingness to help = 乐于助人", "排除负面名词"],
            trap: "refusal/failure 与‘赢得尊重’矛盾。", difficulty: 0.55),
        Question(id: "c12", module: .cloze, levelId: "L2",
            stem: "Hurry up, ___ we'll miss the last train home.",
            options: ["or", "and", "so", "but"], answer: 0,
            pointTag: "逻辑·祈使句 + or",
            strategy: ["祈使句 + or = 否则", "前后是‘快点’与‘否则误车’", "用 or"],
            trap: "祈使句 + and 表‘就会’（正面结果），此处不通。", difficulty: 0.45),
        Question(id: "c13", module: .cloze, levelId: "L2",
            stem: "Under great pressure, she still managed to ___ a clever solution.",
            options: ["come up with", "look after", "give up", "put off"], answer: 0,
            pointTag: "动词短语·come up with",
            strategy: ["come up with = 想出（主意/办法）", "宾语是 solution", "其余短语语义不符"],
            trap: "give up(放弃)与 managed to(成功做到)矛盾。", difficulty: 0.5),
        Question(id: "c14", module: .cloze, levelId: "L2",
            stem: "Despite the ___ weather, the rescue team pressed on into the storm.",
            options: ["harsh", "pleasant", "mild", "warm"], answer: 0,
            pointTag: "语境复现·反推",
            strategy: ["into the storm + Despite 让步→天气恶劣", "harsh weather = 恶劣天气", "排除正面/温和词"],
            trap: "pleasant/mild 与‘冲进风暴’的语境冲突。", difficulty: 0.55),
        Question(id: "c15", module: .cloze, levelId: "L2",
            stem: "___ all the setbacks, the team never lost their hope.",
            options: ["Despite", "Because of", "Thanks to", "Due to"], answer: 0,
            pointTag: "逻辑·让步介词",
            strategy: ["挫折 vs 不失希望→让步", "Despite + 名词短语 = 尽管", "排除因果介词"],
            trap: "Because of/Due to 表原因，逻辑相反。", difficulty: 0.5),
    ]

    // MARK: 七选五 s9–s14

    static let sevenChoose2: [Question] = [
        Question(id: "s9", module: .sevenChoose, levelId: "L3",
            stem: "___ For instance, a single smile can brighten a stranger's whole day.",
            options: ["Small acts of kindness can have a big impact.", "Kindness is a waste of time.",
                      "I never talk to strangers.", "Days are usually long and dull."], answer: 0,
            pointTag: "衔接·For instance 指向总起句",
            strategy: ["空后 For instance 举例", "空处是被例证支撑的总起观点", "选概括‘善举有影响’"],
            trap: "选否定句无法被后面的正面例子支撑。", difficulty: 0.5),
        Question(id: "s10", module: .sevenChoose, levelId: "L3",
            stem: "Volunteers cleaned the beach all morning. ___ Their hard work soon paid off.",
            options: ["They collected over a hundred bags of trash.", "The sea was far from the city.",
                      "Nobody was willing to help them.", "It began to rain very heavily."], answer: 0,
            pointTag: "衔接·Their 指代一致",
            strategy: ["空后 Their 指代志愿者，话题须一致", "空处继续描述志愿者的行动", "选 They collected…"],
            trap: "选‘没人帮忙’与‘他们的努力’指代和逻辑都断。", difficulty: 0.55),
        Question(id: "s11", module: .sevenChoose, levelId: "L3",
            stem: "Online learning offers great flexibility. ___ However, it demands strong self-discipline.",
            options: ["You can study anytime and anywhere.", "It is completely useless for students.",
                      "Teachers are no longer needed at all.", "Nobody is able to learn online."], answer: 0,
            pointTag: "衔接·However 前的正面句",
            strategy: ["空后 However 转折到‘需自律’", "空处应延续‘灵活’的好处", "选‘随时随地学习’"],
            trap: "选负面句会与 However 后的负面句重复，失去转折。", difficulty: 0.6),
        Question(id: "s12", module: .sevenChoose, levelId: "L3",
            stem: "___ In short, reading is one of the best habits anyone can build.",
            options: ["Reading enriches the mind and broadens our horizons.", "Reading is a complete waste of time.",
                      "Books are far too heavy to carry.", "I really dislike going to the library."], answer: 0,
            pointTag: "衔接·In short 前的铺陈句",
            strategy: ["空后 In short 总结‘阅读是好习惯’", "空处应正面铺陈阅读的益处", "选‘丰富心智、开阔视野’"],
            trap: "选负面句与总结句的褒义立场冲突。", difficulty: 0.5),
        Question(id: "s13", module: .sevenChoose, levelId: "L3",
            stem: "Regular exercise strengthens the body. ___ Besides, it lifts our mood after a long day.",
            options: ["It also helps us sleep more soundly at night.", "Exercise is dangerous for everyone.",
                      "Nobody really needs to exercise.", "Sleeping all day is quite enough."], answer: 0,
            pointTag: "衔接·Besides 递进同向",
            strategy: ["空后 Besides 递进，仍讲运动的好处", "空处需与‘强身/提神’同向", "选‘助眠’这一好处"],
            trap: "选负面句破坏 Besides 的递进同向关系。", difficulty: 0.55),
        Question(id: "s14", module: .sevenChoose, levelId: "L3",
            stem: "The shop announced big discounts last week. ___ As a result, customers lined up before dawn.",
            options: ["The news spread quickly across the whole town.", "The shop had always been empty.",
                      "All the prices went up sharply.", "It closed down for good last month."], answer: 0,
            pointTag: "衔接·As a result 前的起因句",
            strategy: ["空后 As a result 引出‘排队’的结果", "空处应是造成排队的起因", "选‘消息迅速传开’"],
            trap: "选‘涨价/关门’与‘排队抢购’的结果矛盾。", difficulty: 0.6),
    ]

    // MARK: 阅读理解 r10–r15（第三篇短文）

    private static let passage3 =
    "Grandma Wang, 68, never went to school as a child. Last year, she joined a free evening class in her village. " +
    "Holding a pencil felt strange at first, and the other students were decades younger. Yet she practiced every night " +
    "by lamplight. This spring, she wrote her very first letter to her grandson. \"The words are crooked,\" she laughed, " +
    "\"but they are mine.\""

    static let reading2: [Question] = [
        Question(id: "r10", module: .reading, levelId: "L4",
            stem: passage3 + "\n\nWhen did Grandma Wang join the evening class?",
            options: ["Last year", "This spring", "As a child", "Decades ago"], answer: 0,
            pointTag: "细节·时间定位",
            strategy: ["回原文找 join", "定位句:Last year, she joined…", "选 Last year"],
            trap: "This spring 是她写信的时间，注意区分。", difficulty: 0.35),
        Question(id: "r11", module: .reading, levelId: "L4",
            stem: passage3 + "\n\nWhich is the best title for the passage?",
            options: ["It's Never Too Late to Learn", "How to Write a Letter",
                      "Daily Life in a Village", "A Hard Childhood"], answer: 0,
            pointTag: "主旨·标题归纳",
            strategy: ["全文写 68 岁奶奶开始识字学习", "主题=活到老学到老", "选‘永远不晚’"],
            trap: "‘如何写信’只是其中一个情节，非主旨。", difficulty: 0.55),
        Question(id: "r12", module: .reading, levelId: "L4",
            stem: passage3 + "\n\nWhat can we infer about Grandma Wang?",
            options: ["She is determined to learn.", "She dislikes writing.",
                      "She quit the class halfway.", "She used to be a teacher."], answer: 0,
            pointTag: "推理·人物品质",
            strategy: ["原文 practiced every night by lamplight", "据坚持推断有决心", "选 determined"],
            trap: "‘半途放弃’与‘每晚练习’相反。", difficulty: 0.5),
        Question(id: "r13", module: .reading, levelId: "L4",
            stem: passage3 + "\n\nThe sentence \"but they are mine\" suggests that she feels ___.",
            options: ["proud", "ashamed", "bored", "frightened"], answer: 0,
            pointTag: "推理·情感态度",
            strategy: ["she laughed + ‘是我自己写的’", "笑着说体现自豪", "选 proud"],
            trap: "字虽歪扭，但语气是骄傲而非羞愧。", difficulty: 0.55),
        Question(id: "r14", module: .reading, levelId: "L4",
            stem: passage3 + "\n\nWhat did Grandma Wang write this spring?",
            options: ["A letter to her grandson", "A school exam paper",
                      "A daily diary", "A shopping list"], answer: 0,
            pointTag: "细节·定位",
            strategy: ["回原文 This spring", "定位:wrote her very first letter to her grandson", "选 A letter…"],
            trap: "其余选项原文均未提及。", difficulty: 0.4),
        Question(id: "r15", module: .reading, levelId: "L4",
            stem: passage3 + "\n\nThe author tells this story mainly to ___.",
            options: ["encourage lifelong learning", "teach English grammar",
                      "sell cheap pencils", "describe village scenery"], answer: 0,
            pointTag: "推理·写作目的",
            strategy: ["励志故事的写作意图", "鼓励人们终身学习", "选 encourage lifelong learning"],
            trap: "卖铅笔/写风景均属过度引申。", difficulty: 0.55),
    ]

    // MARK: 应用文 a7–a12

    static let applied2: [Question] = [
        Question(id: "a7", module: .appliedWriting, levelId: "L5",
            stem: "写一则校运动会通知，下列开头哪句最规范？",
            options: ["The school sports meet will be held next Friday on the playground.",
                      "Sports meet, come everyone!", "There is a sports thing.", "We sports next week ok."], answer: 0,
            pointTag: "应用文·通知开头",
            strategy: ["通知需交代事件+时间+地点", "用规范陈述句", "排除口语化/残缺句"],
            trap: "其余选项信息残缺、语气随意。", difficulty: 0.4),
        Question(id: "a8", module: .appliedWriting, levelId: "L5",
            stem: "向外教委婉建议增加口语课，哪句更得体？",
            options: ["May I suggest adding more speaking practice to the class?",
                      "You should add speaking class.", "Add a speaking class right now.", "I want a speaking class."], answer: 0,
            pointTag: "应用文·委婉建议句",
            strategy: ["建议宜委婉:May I suggest…?", "用疑问/虚拟降低强加感", "排除命令式表达"],
            trap: "‘You should/Add now’ 语气生硬，失礼。", difficulty: 0.5),
        Question(id: "a9", module: .appliedWriting, levelId: "L5",
            stem: "给帮助过你的笔友写感谢信，开头哪句最佳？",
            options: ["I'm writing to express my sincere thanks for your kind help.",
                      "Thanks for your help.", "You helped me, thank you.", "I thank you very now."], answer: 0,
            pointTag: "应用文·感谢信开头",
            strategy: ["express one's sincere thanks for… 正式框架", "点明感谢事由", "排除口语化/语法错"],
            trap: "‘thank you very now’ 不成句。", difficulty: 0.45),
        Question(id: "a10", module: .appliedWriting, levelId: "L5",
            stem: "想强调‘这次活动很重要’，哪句更高级地道？",
            options: ["The event plays a vital role in our personal growth.",
                      "The event is very important.", "The event is so important.", "The event is important much."], answer: 0,
            pointTag: "应用文·亮点句 play a vital role",
            strategy: ["play a vital role in… = 起重要作用", "比 very important 更书面", "排除口语/语法错"],
            trap: "‘important much’ 搭配错误。", difficulty: 0.5),
        Question(id: "a11", module: .appliedWriting, levelId: "L5",
            stem: "表达‘因此我很想参加’，哪句衔接最佳？",
            options: ["Therefore, I would love to take part in the activity.",
                      "So I want join.", "Because I join it.", "I join therefore now."], answer: 0,
            pointTag: "应用文·因果过渡 Therefore",
            strategy: ["承接前文给出结论用 Therefore", "would love to do 礼貌表意愿", "结构完整"],
            trap: "‘So I want join’ 缺 to 且口语化。", difficulty: 0.45),
        Question(id: "a12", module: .appliedWriting, levelId: "L5",
            stem: "倡议节约用水，结尾号召句哪句最佳？",
            options: ["Let's act now and save every drop of water together.",
                      "Save water please.", "Water important, save it.", "You must save the water."], answer: 0,
            pointTag: "应用文·倡议结尾号召",
            strategy: ["倡议书结尾宜用 Let's… 号召", "有行动指向且有感染力", "排除生硬/残缺句"],
            trap: "‘You must’ 命令口吻不适合倡议。", difficulty: 0.45),
    ]

    // MARK: 读后续写 k7–k12

    static let continuation2: [Question] = [
        Question(id: "k7", module: .continuation, levelId: "L6",
            stem: "续写开头要烘托紧张气氛，哪句最佳？",
            options: ["The wind howled through the empty street as midnight drew near.",
                      "It was night. The street was empty. Tom stood there.",
                      "Something happened to Tom that night.", "The street was very empty and dark very much."], answer: 0,
            pointTag: "续写·环境烘托",
            strategy: ["用环境(风声/午夜)营造氛围", "as 引导伴随推进时间", "排除流水账/笼统句"],
            trap: "短句罗列缺乏画面与张力。", difficulty: 0.6),
        Question(id: "k8", module: .continuation, levelId: "L6",
            stem: "想用对话自然推进情节，哪句最佳？",
            options: ["\"We can't give up now,\" she whispered, gripping his hand tightly.",
                      "She said don't give up to him.", "\"Give up\" she did not say.", "She talked about not giving up."], answer: 0,
            pointTag: "续写·对话+动作并行",
            strategy: ["直接引语+动作描写让对话有画面", "whispered/gripping 传情绪", "排除间接转述/语病"],
            trap: "间接转述削弱现场感与张力。", difficulty: 0.6),
        Question(id: "k9", module: .continuation, levelId: "L6",
            stem: "描写‘厨房飘来香味’，哪句更有画面感？",
            options: ["The sweet smell of fresh bread drifted out from the kitchen.",
                      "The kitchen had a good smell of bread.", "Bread smelled good in the kitchen.", "There was a bread smell."], answer: 0,
            pointTag: "续写·感官描写",
            strategy: ["调动嗅觉:sweet smell…drifted out", "动词 drift 让香味有动态", "排除平铺直叙"],
            trap: "‘had a good smell’ 平淡，无画面。", difficulty: 0.55),
        Question(id: "k10", module: .continuation, levelId: "L6",
            stem: "把‘他突然有了信心’写得更高级，选哪句？",
            options: ["A spark of confidence suddenly lit up inside him.",
                      "He suddenly had confidence.", "He was confident suddenly very much.", "Confidence came to him fast."], answer: 0,
            pointTag: "续写·化抽象为意象",
            strategy: ["用‘火花点亮’的意象写信心", "A spark…lit up inside him 生动", "排除直白/语病"],
            trap: "‘confident suddenly very much’ 堆砌且不地道。", difficulty: 0.6),
        Question(id: "k11", module: .continuation, levelId: "L6",
            stem: "描写‘她迅速收拾东西冲出门’，哪句最佳？",
            options: ["She grabbed her bag, threw on her coat, and dashed out the door.",
                      "She took her bag and coat and went out fast.", "She quickly went out with her things.", "She run out with her bag quickly."], answer: 0,
            pointTag: "续写·连续强动词",
            strategy: ["grabbed→threw on→dashed 连续动作显节奏", "强动词替代 went fast", "排除笼统/语病(run)"],
            trap: "‘run out’ 时态错误且动作平淡。", difficulty: 0.6),
        Question(id: "k12", module: .continuation, levelId: "L6",
            stem: "续写结尾升华‘亲情’主题，哪句最佳？",
            options: ["In that warm embrace, he finally understood the true meaning of home.",
                      "They hugged. He was happy. The end.", "So they became a family again happily.", "Then he went to sleep and forgot it all."], answer: 0,
            pointTag: "续写·结尾升华点题",
            strategy: ["由拥抱的场景升华到‘家的意义’", "understood the true meaning of home 点题", "排除草率收尾"],
            trap: "‘睡觉忘掉一切’让亲情主题落空。", difficulty: 0.6),
    ]
}
