import Foundation

/// 二期扩充题（第四批）。语法填空/完形/七选五推到 30 题，撑满客观题靶场。
extension QuestionBank {

    static let extended4: [Question] =
        grammarFill4 + cloze4 + sevenChoose4

    // MARK: 语法填空 g21–g30

    static let grammarFill4: [Question] = [
        Question(id: "g21", module: .grammarFill, levelId: "L1",
            stem: "The hotel ___ we stayed last summer has now been turned into a museum.",
            options: ["where", "which", "that", "when"], answer: 0,
            pointTag: "定语从句·where 地点先行词",
            strategy: ["先行词 hotel 表地点", "从句 stayed 不缺主谓宾成分，缺地点状语", "用 where(=in/at which)"],
            trap: "which/that 通常替代主谓宾成分，此处从句成分已完整。", difficulty: 0.6),
        Question(id: "g22", module: .grammarFill, levelId: "L1",
            stem: "___ that the bridge was unsafe, the workers closed it to traffic at once.",
            options: ["Knowing", "Known", "To know", "Knew"], answer: 0,
            pointTag: "非谓语·现在分词作原因状语",
            strategy: ["逻辑主语 the workers 与 know 是主动关系", "表原因的伴随状语，动作几乎同时发生", "用现在分词主动式 Knowing"],
            trap: "Known(过去分词，被动)与‘工人主动知道’的关系矛盾。", difficulty: 0.55),
        Question(id: "g23", module: .grammarFill, levelId: "L1",
            stem: "By the end of next year, this new railway line ___ between the two cities.",
            options: ["will have been built", "will build", "is building", "was built"], answer: 0,
            pointTag: "时态·将来完成时的被动",
            strategy: ["By the end of next year 提示将来完成", "railway line 是被建造的对象，需被动语态", "will have been + done"],
            trap: "will build 是主动语态，但铁路线是被建造，应用被动。", difficulty: 0.65),
        Question(id: "g24", module: .grammarFill, levelId: "L1",
            stem: "___ you understand the basic rule, the rest of the grammar becomes much easier.",
            options: ["Once", "Unless", "Until", "Whereas"], answer: 0,
            pointTag: "状语从句·once 一旦",
            strategy: ["语境:一旦理解基本规则，其余就变容易", "once = 一旦……就……", "选 Once"],
            trap: "Unless(除非)/Until(直到) 与‘理解后变容易’的顺承逻辑不符。", difficulty: 0.5),
        Question(id: "g25", module: .grammarFill, levelId: "L1",
            stem: "She couldn't ignore the fact ___ her savings were running low.",
            options: ["that", "which", "what", "where"], answer: 0,
            pointTag: "同位语从句·the fact that",
            strategy: ["the fact 后接从句说明具体内容", "从句成分完整，不缺成分", "用同位语从句标志词 that"],
            trap: "which 引导定语从句需在从句中充当成分，此处从句已完整。", difficulty: 0.6),
        Question(id: "g26", module: .grammarFill, levelId: "L1",
            stem: "The bag was ___ heavy for the little boy to carry on his own.",
            options: ["too", "so", "very", "quite"], answer: 0,
            pointTag: "固定结构·too…to",
            strategy: ["too + adj + for sb + to do = 太……以致于不能", "语境是男孩拿不动", "选 too"],
            trap: "so heavy 需接 that 从句，不能直接接 for sb to do。", difficulty: 0.45),
        Question(id: "g27", module: .grammarFill, levelId: "L1",
            stem: "Her latest novel is every bit ___ interesting as her first one.",
            options: ["as", "so", "more", "very"], answer: 0,
            pointTag: "比较·as…as 同级比较",
            strategy: ["every bit as + adj + as = 同……一样", "需 as…as 结构呼应后面的 as", "选 as"],
            trap: "so 通常用于否定句 not so…as，此处为肯定句应用 as。", difficulty: 0.5),
        Question(id: "g28", module: .grammarFill, levelId: "L1",
            stem: "Many people are still curious about the way ___ the ancient pyramids were built.",
            options: ["in which", "which", "what", "how which"], answer: 0,
            pointTag: "定语从句·介词+which",
            strategy: ["先行词 way 在从句中作方式状语", "方式状语需介词 in 引出", "in which = 以这种方式"],
            trap: "way 后若不加介词，which 不能单独充当方式状语。", difficulty: 0.65),
        Question(id: "g29", module: .grammarFill, levelId: "L1",
            stem: "___, the temperature dropped sharply within minutes.",
            options: ["The sun having set", "The sun had set", "Having set the sun", "The sun was setting"], answer: 0,
            pointTag: "独立主格·分词表时间",
            strategy: ["分句有独立的逻辑主语 the sun，与主句主语不同", "用‘名词+分词’独立主格结构", "having set 表示先发生的动作"],
            trap: "The sun had set 是完整主谓结构，与主句间缺连词，无法直接用逗号连接。", difficulty: 0.7),
        Question(id: "g30", module: .grammarFill, levelId: "L1",
            stem: "It was the young intern, not the manager, ___ first noticed the error in the report.",
            options: ["who", "which", "that he", "whom"], answer: 0,
            pointTag: "强调句·强调人作主语用 who/that",
            strategy: ["It was…that/who… 强调句强调主语", "被强调对象 the young intern 是人", "用 who 引出(此处也可用 that)"],
            trap: "which 只能强调物；whom 是宾格，而此处缺的是从句主语。", difficulty: 0.6),
    ]

    // MARK: 完形填空 c19–c30

    static let cloze4: [Question] = [
        Question(id: "c19", module: .cloze, levelId: "L2",
            stem: "The plan looked risky on paper; ___, the team decided to give it a try.",
            options: ["nevertheless", "moreover", "namely", "likewise"], answer: 0,
            pointTag: "逻辑·尽管如此 nevertheless",
            strategy: ["前句:计划看起来冒险；后句:仍然尝试", "前后是让步转折关系", "nevertheless = 尽管如此"],
            trap: "moreover(此外)/likewise(同样地) 不表达‘尽管如此’的让步语气。", difficulty: 0.55),
        Question(id: "c20", module: .cloze, levelId: "L2",
            stem: "Smart shoppers always ___ of the year-end sales to buy what they need at lower prices.",
            options: ["take advantage", "take charge", "take care", "take notice"], answer: 0,
            pointTag: "固定搭配·take advantage of",
            strategy: ["take advantage of = 利用", "语境:利用年末促销低价购物", "选 take advantage"],
            trap: "take charge of(负责)/take care of(照顾) 与‘利用促销买东西’不符。", difficulty: 0.45),
        Question(id: "c21", module: .cloze, levelId: "L2",
            stem: "Mr. Lee often gives away his old books for free; everyone in the neighborhood calls him ___.",
            options: ["generous", "selfish", "stubborn", "cautious"], answer: 0,
            pointTag: "形容词反推·语境",
            strategy: ["免费送书=慷慨大方", "generous = 慷慨的", "排除负面/不相关形容词"],
            trap: "selfish(自私)与‘免费送书’直接相反。", difficulty: 0.4),
        Question(id: "c22", module: .cloze, levelId: "L2",
            stem: "You won't fully master a language ___ you practice it every single day.",
            options: ["unless", "although", "since", "while"], answer: 0,
            pointTag: "逻辑·除非 unless",
            strategy: ["语境:不每天练习就无法精通", "unless = 除非，相当于 if…not", "选 unless"],
            trap: "although(尽管)/since(既然) 不能表达‘除非……否则不’的条件关系。", difficulty: 0.5),
        Question(id: "c23", module: .cloze, levelId: "L2",
            stem: "When the fire ___ in the warehouse, workers evacuated within minutes.",
            options: ["broke out", "broke down", "broke up", "broke in"], answer: 0,
            pointTag: "动词短语·break out(突发)",
            strategy: ["break out 用于火灾/战争/疫情等突发事件", "语境:仓库起火", "选 broke out"],
            trap: "break down(损坏/崩溃)/break up(分裂) 不用于描述火灾发生。", difficulty: 0.5),
        Question(id: "c24", module: .cloze, levelId: "L2",
            stem: "It took great ___ for her to speak up in front of the whole school.",
            options: ["courage", "shame", "doubt", "regret"], answer: 0,
            pointTag: "名词反推·语境",
            strategy: ["在全校面前发言需要勇气", "It takes courage to do sth", "选 courage"],
            trap: "shame(羞愧)/regret(后悔) 与‘当众发言’的情境不符。", difficulty: 0.45),
        Question(id: "c25", module: .cloze, levelId: "L2",
            stem: "He was clearly ___ to admit his mistake, mumbling excuses instead of saying sorry directly.",
            options: ["reluctant", "eager", "willing", "proud"], answer: 0,
            pointTag: "形容词辨析·reluctant",
            strategy: ["支支吾吾找借口=不情愿", "reluctant to do = 不情愿做", "排除 eager/willing 等正面词"],
            trap: "eager/willing 表‘乐意’，与‘找借口而不直接道歉’相反。", difficulty: 0.5),
        Question(id: "c26", module: .cloze, levelId: "L2",
            stem: "After the accident, the driver became extremely ___, checking his mirrors every few seconds.",
            options: ["cautious", "careless", "confident", "curious"], answer: 0,
            pointTag: "形容词反推·语境",
            strategy: ["事故后频繁查看镜子=谨慎", "cautious = 谨慎的", "排除其余不符语境的形容词"],
            trap: "careless(粗心)与‘频繁检查’的行为直接相反。", difficulty: 0.45),
        Question(id: "c27", module: .cloze, levelId: "L2",
            stem: "___ the heavy traffic, she managed to arrive at the interview right on time.",
            options: ["In spite of", "Because of", "Instead of", "In favor of"], answer: 0,
            pointTag: "介词短语·in spite of",
            strategy: ["交通拥堵 vs 准时到达→让步关系", "in spite of = 尽管", "排除因果/替代/支持类介词"],
            trap: "Because of 表原因，与‘准时到达’的让步逻辑相反。", difficulty: 0.5),
        Question(id: "c28", module: .cloze, levelId: "L2",
            stem: "Dr. Lin has ___ her entire career to researching rare childhood diseases.",
            options: ["devoted", "borrowed", "wasted", "doubted"], answer: 0,
            pointTag: "动词搭配·devote…to",
            strategy: ["devote sth to (doing) sth = 把……奉献给", "语境:把职业生涯投入研究", "选 devoted"],
            trap: "wasted(浪费)与‘致力于研究罕见疾病’的积极语境矛盾。", difficulty: 0.5),
        Question(id: "c29", module: .cloze, levelId: "L2",
            stem: "Teaching toddlers requires endless ___; you can never rush them.",
            options: ["patience", "impatience", "anger", "pride"], answer: 0,
            pointTag: "名词反推·语境对比",
            strategy: ["‘不能催促’对应‘需要耐心’", "patience = 耐心", "排除 impatience 等相反/不符词"],
            trap: "impatience(不耐烦)与后文‘不能催促’的建议正好相反。", difficulty: 0.45),
        Question(id: "c30", module: .cloze, levelId: "L2",
            stem: "Some students prefer studying alone, ___ others learn better in groups.",
            options: ["whereas", "so", "for", "or"], answer: 0,
            pointTag: "逻辑·对比 whereas",
            strategy: ["两种学习方式形成对比", "whereas = 然而，表对比", "排除因果/选择类连词"],
            trap: "so(因此)/for(因为) 表因果，不表两种情况的并列对比。", difficulty: 0.5),
    ]

    // MARK: 七选五 s17–s30

    static let sevenChoose4: [Question] = [
        Question(id: "s17", module: .sevenChoose, levelId: "L3",
            stem: "Jogging every morning keeps the body fit. ___ In addition, it clears the mind before a busy day.",
            options: ["It also helps people sleep better at night.", "Jogging is bad for the knees.",
                      "Most people hate getting up early.", "Morning traffic is often heavy."], answer: 0,
            pointTag: "衔接·In addition 递进同向",
            strategy: ["空后 In addition 递进，仍讲晨跑好处", "空处需与‘健身/提神’同向", "选‘还能助眠’这一好处"],
            trap: "选‘伤膝盖’会与递进句列举的正面好处矛盾。", difficulty: 0.5),
        Question(id: "s18", module: .sevenChoose, levelId: "L3",
            stem: "Working from home saves commuting time. ___ On the other hand, it can make people feel isolated.",
            options: ["It also offers more flexible working hours.", "Offices are always too noisy.",
                      "Nobody enjoys working from home.", "Commuting is good exercise."], answer: 0,
            pointTag: "衔接·On the other hand 对比",
            strategy: ["On the other hand 引出与前文相对的另一面", "空处应先延续‘居家办公的好处’再转向坏处", "选‘更灵活的工作时间’"],
            trap: "选‘没人喜欢居家办公’与首句的正面陈述自相矛盾。", difficulty: 0.55),
        Question(id: "s19", module: .sevenChoose, levelId: "L3",
            stem: "___ To begin with, it provides job opportunities for local people.",
            options: ["A new factory brings several benefits to this small town.", "Factories always pollute the environment.",
                      "Nobody wants a factory nearby.", "This town has no industry at all."], answer: 0,
            pointTag: "衔接·To begin with 指向总起句",
            strategy: ["空后 To begin with 引出第一点理由", "空处应是被这些理由支撑的总起观点", "选‘新工厂带来好处’"],
            trap: "选‘工厂总是污染环境’与后文‘提供就业’的正面理由矛盾。", difficulty: 0.5),
        Question(id: "s20", module: .sevenChoose, levelId: "L3",
            stem: "The new policy aims to reduce paperwork in schools. ___ In other words, teachers can finally spend more time teaching.",
            options: ["It cuts the amount of time spent on forms and reports.", "It will close down every school.",
                      "Students will no longer attend classes.", "Teachers will receive less training."], answer: 0,
            pointTag: "衔接·In other words 同义重述",
            strategy: ["In other words 后是对前文的换说", "‘减少文书工作’与‘有更多时间教学’呼应", "选直接说明‘减少表格和报告时间’的句子"],
            trap: "选‘关闭学校’与‘老师能专心教学’的积极结果毫无关联。", difficulty: 0.55),
        Question(id: "s21", module: .sevenChoose, levelId: "L3",
            stem: "Please back up your files regularly. ___ Otherwise, you may lose months of work in seconds.",
            options: ["A single computer crash can destroy everything.", "Computers never break down.",
                      "Backing up files is a complete waste of time.", "Most files are too small to matter."], answer: 0,
            pointTag: "衔接·Otherwise 提示后果",
            strategy: ["Otherwise 后给出不这样做的后果", "空处应说明‘不备份的风险’作为铺垫", "选‘电脑故障可能摧毁所有数据’"],
            trap: "选‘电脑从不出故障’与 Otherwise 提示的风险逻辑相反。", difficulty: 0.55),
        Question(id: "s22", module: .sevenChoose, levelId: "L3",
            stem: "Plants need sunlight to grow strong and healthy. ___ Similarly, children need encouragement to develop confidence.",
            options: ["Without enough light, they grow weak and pale.", "Plants can survive without any water.",
                      "Sunlight is harmful to most plants.", "Children dislike spending time outdoors."], answer: 0,
            pointTag: "衔接·Similarly 类比",
            strategy: ["Similarly 前后是平行类比关系", "空处需延续‘植物缺光会怎样’，对应后面‘孩子缺鼓励’", "选‘缺光会长得瘦弱发白’"],
            trap: "选‘阳光对植物有害’与下文用阳光类比鼓励的正面类比相反。", difficulty: 0.6),
        Question(id: "s23", module: .sevenChoose, levelId: "L3",
            stem: "Many believe that talent alone leads to success. ___ In fact, hard work matters far more than raw talent.",
            options: ["But this idea is only half true.", "Talent is the only thing that matters.",
                      "Success always comes easily to gifted people.", "Hard work can never replace talent."], answer: 0,
            pointTag: "衔接·But/In fact 转折强调",
            strategy: ["In fact 引出与‘只看天赋’相反的真相", "空处用 But 承上转折，引出下文强调努力", "选‘这种想法只对了一半’"],
            trap: "选‘天赋是唯一决定因素’与下文‘努力更重要’直接矛盾。", difficulty: 0.6),
        Question(id: "s24", module: .sevenChoose, levelId: "L3",
            stem: "Cycling to work reduces air pollution. ___ What's more, it saves a great deal of money on fuel.",
            options: ["It also gives riders a daily dose of exercise.", "Bicycles are far too expensive to buy.",
                      "Cycling is only possible in summer.", "Most roads are unsafe for cyclists."], answer: 0,
            pointTag: "衔接·What's more 递进",
            strategy: ["What's more 递进，仍讲骑车上班的好处", "空处需与‘减少污染/省钱’同向", "选‘还能锻炼身体’"],
            trap: "选‘自行车太贵’与递进句列举好处的方向相反。", difficulty: 0.5),
        Question(id: "s25", module: .sevenChoose, levelId: "L3",
            stem: "The chef prepared the sauce slowly over low heat. ___ Meanwhile, his assistant chopped the vegetables for the salad.",
            options: ["He wanted the flavors to blend perfectly.", "The kitchen had been closed for repairs.",
                      "Nobody was working in the kitchen that day.", "The restaurant had run out of vegetables."], answer: 0,
            pointTag: "衔接·Meanwhile 同时性",
            strategy: ["Meanwhile 引出同时发生的另一动作", "空处应交代主厨这一动作的目的，承接上文", "选‘他想让味道完美融合’"],
            trap: "选‘厨房当天没人工作’与 Meanwhile 后‘助手在切菜’相矛盾。", difficulty: 0.55),
        Question(id: "s26", module: .sevenChoose, levelId: "L3",
            stem: "___ For example, she once walked three miles in the rain just to return a borrowed book on time.",
            options: ["Mia is known for keeping every promise she makes.", "Mia often forgets her own birthday.",
                      "Borrowing books is not allowed in this town.", "Rain rarely falls in this region."], answer: 0,
            pointTag: "衔接·For example 指向总起句",
            strategy: ["空后 For example 举具体事例", "事例:雨中走三英里还书=守信", "选概括‘她信守每一个承诺’"],
            trap: "选‘经常忘记自己生日’与‘守信’的举例方向无关。", difficulty: 0.5),
        Question(id: "s27", module: .sevenChoose, levelId: "L3",
            stem: "The villagers planted thousands of trees along the riverbank. ___ As a result, the floods that once destroyed crops every spring stopped happening.",
            options: ["The roots held the soil firmly in place.", "The river had always been completely dry.",
                      "Nobody in the village liked trees.", "The crops had never been damaged before."], answer: 0,
            pointTag: "衔接·As a result 前的起因句",
            strategy: ["空后 As a result 引出‘洪水不再发生’的结果", "空处应是导致这一结果的直接原因", "选‘树根牢牢固定住了土壤’"],
            trap: "选‘庄稼以前从未受损’与首句‘洪水曾摧毁庄稼’矛盾。", difficulty: 0.6),
        Question(id: "s28", module: .sevenChoose, levelId: "L3",
            stem: "Street food looks tempting and tastes delicious. ___ However, eating it too often can upset your stomach.",
            options: ["It is also far cheaper than eating at a restaurant.", "Nobody enjoys eating street food.",
                      "Restaurants always taste better than street stalls.", "Stomach problems are extremely rare."], answer: 0,
            pointTag: "衔接·However 前的正面句",
            strategy: ["空后 However 转折到‘吃太多伤胃’", "空处应延续‘街头小吃’的好处", "选‘更便宜’"],
            trap: "选‘没人喜欢街头小吃’与首句‘看起来诱人好吃’矛盾。", difficulty: 0.5),
        Question(id: "s29", module: .sevenChoose, levelId: "L3",
            stem: "A good leader listens carefully to every team member. ___ Above all, a good leader takes responsibility when things go wrong.",
            options: ["A good leader also gives credit generously when things go right.", "A good leader never makes any decisions.",
                      "Most leaders avoid talking to their team.", "Mistakes are always someone else's fault."], answer: 0,
            pointTag: "衔接·Above all 总结递进",
            strategy: ["Above all 引出最重要的一点，前面应有并列的其他品质", "空处需延续‘好领导的品质’", "选‘也乐于在事情顺利时给予肯定’"],
            trap: "选‘从不做决定’与‘好领导’的正面形象矛盾。", difficulty: 0.55),
        Question(id: "s30", module: .sevenChoose, levelId: "L3",
            stem: "___ In a word, small daily habits shape who we eventually become.",
            options: ["What we choose to do every single day adds up over time.", "Habits never really affect anyone's life.",
                      "Big life-changing moments are all that matter.", "Most people never think about their habits."], answer: 0,
            pointTag: "衔接·In a word 前的铺陈句",
            strategy: ["空后 In a word 总结‘日常习惯塑造我们’", "空处应正面铺陈‘日常选择会累积’", "选与总结句呼应的铺陈句"],
            trap: "选‘习惯从不影响人生’与总结句的核心观点直接相反。", difficulty: 0.55),
    ]
}
