import Foundation

/// 第四轮补题：按 ROI 权重查缺补漏（共 60 道）。
///
/// 权重公式：`learnability(可学性) × examWeight(考试权重) / effortWeight(提分代价)`，
/// 得分越高越值得先补，同时兼顾原题量最薄的模块：
///
/// | 模块 | 原量 | 新增 | 权重依据 |
/// |---|---|---|---|
/// | 语法填空 L1 | 56 | 11 | 可学性 0.90、代价最低(1.0)，规则最强 |
/// | 阅读 L4 | 66 | 11 | 考试权重最大(37.5/150)，仍是最主要得分场 |
/// | 听力 L7 | 58 | 10 | 考试权重 30 分，且原有高频考点覆盖不足 |
/// | 应用文 L5 | 45 | 9 | 可学性 0.85、代价 1.2，模板收益高 |
/// | 七选五 L3 | 40 | 8 | 可学性 0.80、代价 1.1，原量最薄 |
/// | 完形 L2 | 65 | 6 | 可学性 0.70，靠词汇与语境，性价比中等 |
/// | 读后续写 L6 | 47 | 5 | 可学性 0.55、代价 2.2，权重最低，少量补强 |
///
/// 拆分说明：`extended9`(53 道) 进入模考套卷一~五的轮转池，
/// `paper6Supplement`(7 道) 并入套卷六专属批次 `extended8`。
/// 这样各模块在六套卷之间的题量差仍不超过 1，满足 `testFixedPapersAreDeterministicAndBalanced`。
extension QuestionBank {

    // MARK: 第九批 · 轮转池（53 道）

    static let extended9: [Question] = [
        // L1 语法填空（10）
        Question(id: "g9-01", module: .grammarFill, levelId: "L1",
                 stem: "The committee ___ divided over the proposal, so no decision was reached.",
                 options: ["was", "were", "are", "have been"], answer: 0,
                 pointTag: "主谓一致·集合名词",
                 strategy: ["集合名词 committee 强调整体时按单数处理", "后半句 no decision 说明结果未出，用过去时", "确定 was"],
                 trap: "看到 committee 就填 were——强调整体时用单数。", difficulty: 0.6),
        Question(id: "g9-02", module: .grammarFill, levelId: "L1",
                 stem: "Hardly ___ she stepped onto the stage when the lights went out.",
                 options: ["had", "did", "has", "was"], answer: 0,
                 pointTag: "倒装·hardly...when",
                 strategy: ["hardly 置于句首要部分倒装", "hardly...when 固定搭配，主句用过去完成时", "确定 had"],
                 trap: "填 did——hardly 句型要求过去完成时。", difficulty: 0.65),
        Question(id: "g9-03", module: .grammarFill, levelId: "L1",
                 stem: "The report needs ___ before Friday's meeting.",
                 options: ["checking", "check", "to checking", "checked"], answer: 0,
                 pointTag: "非谓语·need doing",
                 strategy: ["need 后接动名词表被动含义", "need doing = need to be done", "确定 checking"],
                 trap: "填 to checking——不定式符号后不能接动名词。", difficulty: 0.55),
        Question(id: "g9-04", module: .grammarFill, levelId: "L1",
                 stem: "It is the third time that he ___ late for class this week.",
                 options: ["has been", "was", "is", "had been"], answer: 0,
                 pointTag: "时态·现在完成",
                 strategy: ["It is the ... time that 从句用现在完成时", "this week 表示与现在相关的时间段", "确定 has been"],
                 trap: "填 was——固定句型要求完成时。", difficulty: 0.55),
        Question(id: "g9-05", module: .grammarFill, levelId: "L1",
                 stem: "___ the terrible weather, the match went ahead as planned.",
                 options: ["Despite", "Although", "Though", "Even"], answer: 0,
                 pointTag: "介词·despite",
                 strategy: ["空后是名词短语 the terrible weather", "接名词用介词 despite", "接句子才用 although/though"],
                 trap: "填 Although——它后面要接句子而不是名词短语。", difficulty: 0.5),
        Question(id: "g9-06", module: .grammarFill, levelId: "L1",
                 stem: "The novel ___ I borrowed from the library is already overdue.",
                 options: ["that", "what", "whose", "who"], answer: 0,
                 pointTag: "定语从句·关系代词",
                 strategy: ["先行词 the novel 是物", "从句缺宾语，用 that/which", "what 不能引导定语从句"],
                 trap: "填 what——what 不能作定语从句的关系词。", difficulty: 0.45),
        Question(id: "g9-07", module: .grammarFill, levelId: "L1",
                 stem: "If I ___ you, I would apologise to her first.",
                 options: ["were", "am", "was", "be"], answer: 0,
                 pointTag: "虚拟语气·if I were",
                 strategy: ["与现在事实相反的假设", "be 动词一律用 were", "主句 would + 动词原形"],
                 trap: "填 was——虚拟语气中固定用 were。", difficulty: 0.55),
        Question(id: "g9-08", module: .grammarFill, levelId: "L1",
                 stem: "She suggested that the meeting ___ put off until next Monday.",
                 options: ["be", "is", "was", "will be"], answer: 0,
                 pointTag: "虚拟语气·suggest",
                 strategy: ["suggest 表建议时从句用 (should) + 动词原形", "会议是被推迟，用被动 be put off", "确定 be"],
                 trap: "填 is/was——suggest 后要用虚拟语气原形。", difficulty: 0.6),
        Question(id: "g9-09", module: .grammarFill, levelId: "L1",
                 stem: "___ more attention, the young plants would have grown much better.",
                 options: ["Given", "Giving", "To give", "Give"], answer: 0,
                 pointTag: "非谓语·过去分词",
                 strategy: ["找逻辑主语 the young plants", "植物是被给予关注，属被动", "被动用过去分词 Given"],
                 trap: "填 Giving（主动）——植物是被动接受照料。", difficulty: 0.65),
        Question(id: "g9-10", module: .grammarFill, levelId: "L1",
                 stem: "Not only ___ the difficult exam, but he also won a national prize.",
                 options: ["did he pass", "he passed", "passed he", "he did pass"], answer: 0,
                 pointTag: "倒装·not only",
                 strategy: ["not only 置于句首时该分句要部分倒装", "谓语动词是实义动词 pass，借助动词 did", "确定 did he pass"],
                 trap: "填 he passed——not only 在句首必须倒装。", difficulty: 0.7),

        // L2 完形（5）
        Question(id: "c9-01", module: .cloze, levelId: "L2",
                 stem: "She managed to ___ her fear and speak calmly in front of the whole school.",
                 options: ["overcome", "overtake", "overlook", "overload"], answer: 0,
                 pointTag: "完形·动词辨析",
                 strategy: ["宾语是 fear，需搭配‘克服’", "overcome fear 是固定搭配", "overlook 是忽视，语义不符"],
                 trap: "形近词干扰：overtake(超越)/overlook(俯瞰、忽视)都不接 fear。", difficulty: 0.5),
        Question(id: "c9-02", module: .cloze, levelId: "L2",
                 stem: "His voice ___ with emotion as he thanked the team for their support.",
                 options: ["trembled", "transferred", "translated", "transformed"], answer: 0,
                 pointTag: "完形·语境动词",
                 strategy: ["语境是激动地道谢", "with emotion 提示声音颤抖", "确定 trembled"],
                 trap: "几个词都以 trans- 开头，但只有 trembled 能与 voice 搭配。", difficulty: 0.55),
        Question(id: "c9-03", module: .cloze, levelId: "L2",
                 stem: "The old photograph ___ memories of her childhood in the countryside.",
                 options: ["brought back", "brought up", "brought about", "brought in"], answer: 0,
                 pointTag: "完形·短语动词",
                 strategy: ["宾语是 memories，需要‘唤起’", "bring back memories 为固定搭配", "bring up 是抚养、提出"],
                 trap: "bring about(导致)/bring in(引进)都不与 memories 搭配。", difficulty: 0.55),
        Question(id: "c9-04", module: .cloze, levelId: "L2",
                 stem: "The mountain path was ___ by fallen trees after the storm, so we turned back.",
                 options: ["blocked", "covered", "crowded", "packed"], answer: 0,
                 pointTag: "完形·语境逻辑",
                 strategy: ["后文 so we turned back 说明无法通行", "倒下的树把路‘堵住’", "确定 blocked"],
                 trap: "covered(覆盖)只表示表面被盖住，不能解释原路折返。", difficulty: 0.45),
        Question(id: "c9-05", module: .cloze, levelId: "L2",
                 stem: "To my ___, he still remembered my name after ten long years.",
                 options: ["astonishment", "annoyance", "anxiety", "ambition"], answer: 0,
                 pointTag: "完形·名词辨析",
                 strategy: ["十年后仍记得名字是令人惊讶的事", "to my + 情感名词", "确定 astonishment"],
                 trap: "annoyance(恼怒)/anxiety(焦虑)与‘惊喜’的语境相反。", difficulty: 0.5),

        // L3 七选五（7）
        Question(id: "s9-01", module: .sevenChoose, levelId: "L3",
                 stem: "空白处位于段落开头，后文依次出现 First...、Second...、Finally...，应填入哪一句？",
                 options: ["Here are three practical steps you can take.", "However, the results were disappointing.", "In conclusion, the plan failed.", "He never tried again."], answer: 0,
                 pointTag: "七选五·段首总起",
                 strategy: ["看空白位置：段首句通常总领全段", "后文 First/Second/Finally 说明是分条建议", "选概括性的总起句"],
                 trap: "带 However/In conclusion 的句子是转折或总结，不能放在段首引出步骤。", difficulty: 0.45),
        Question(id: "s9-02", module: .sevenChoose, levelId: "L3",
                 stem: "前文讲她屡遭失败，后文讲她最终完成了作品，空白处应填入？",
                 options: ["Yet she refused to give up.", "Therefore she succeeded at once.", "For example, she slept for hours.", "Meanwhile it began to rain."], answer: 0,
                 pointTag: "七选五·转折衔接",
                 strategy: ["判断前后语义关系：失败→成功，是转折", "需要带让步/转折标记的句子", "Yet 引出转折并衔接后文"],
                 trap: "Therefore 表因果，与‘屡遭失败’的前提矛盾。", difficulty: 0.5),
        Question(id: "s9-03", module: .sevenChoose, levelId: "L3",
                 stem: "本段通篇讲阅读如何拓宽视野，段末空白处最适合填入？",
                 options: ["In short, reading shapes the way we think.", "However, reading is a waste of time.", "Next, we will discuss cooking.", "He bought a book yesterday."], answer: 0,
                 pointTag: "七选五·段末总结",
                 strategy: ["空白在段末，优先考虑总结句", "总结句须回扣本段主题‘阅读的价值’", "In short 是典型总结标记"],
                 trap: "However 引导相反观点，与本段褒扬阅读的立场冲突。", difficulty: 0.45),
        Question(id: "s9-04", module: .sevenChoose, levelId: "L3",
                 stem: "上文提到 'small habits can make a big difference'，空白处应该？",
                 options: ["Take making your bed every morning, for instance.", "As a result, the war finally ended.", "On the contrary, nothing ever changed.", "In addition, the sky was clear blue."], answer: 0,
                 pointTag: "七选五·举例衔接",
                 strategy: ["前句是抽象观点，后文通常举例支撑", "找包含具体事例的句子", "for instance 是举例标记"],
                 trap: "与 war/sky 有关的选项都脱离了‘习惯’这一话题。", difficulty: 0.45),
        Question(id: "s9-05", module: .sevenChoose, levelId: "L3",
                 stem: "空白处后一句为 'They can save both time and money.'，应填入哪一句？",
                 options: ["Public transport has clear advantages.", "The weather was terrible that day.", "Nobody cared about the result.", "He sold his car last month."], answer: 0,
                 pointTag: "七选五·代词指代",
                 strategy: ["锁定后文代词 They 指代什么", "They 应是复数名词且能‘省时省钱’", "Public transport 符合且语义连贯"],
                 trap: "与天气、人物相关的选项都无法充当 They 的先行词。", difficulty: 0.55),
        Question(id: "s9-06", module: .sevenChoose, levelId: "L3",
                 stem: "前一句以 'On the one hand' 开头，空白处应填入？",
                 options: ["On the other hand", "As a result", "For instance", "In the meantime"], answer: 0,
                 pointTag: "七选五·固定搭配",
                 strategy: ["识别固定搭配 on the one hand...on the other hand", "两句之间是并列对比关系", "确定 On the other hand"],
                 trap: "As a result 表因果，破坏了 on the one hand 的对照结构。", difficulty: 0.4),
        Question(id: "s9-07", module: .sevenChoose, levelId: "L3",
                 stem: "本段讲的是把一天切成若干时间段专注做事，小标题应为？",
                 options: ["Manage your time in blocks.", "Cook a healthy meal.", "Learn a second language.", "Travel around the world."], answer: 0,
                 pointTag: "七选五·小标题",
                 strategy: ["小标题须概括全段", "段落关键词是‘时间段、专注’", "选与时间管理相关的标题"],
                 trap: "做饭、学语言、旅行都与本段的时间切块无关。", difficulty: 0.45),

        // L4 阅读（9）
        Question(id: "r9-01", module: .reading, levelId: "L4",
                 stem: "The author mentions 'the silent majority' mainly to show that ___.",
                 options: ["most people never voiced their opinions", "most people were very noisy", "the election was already over", "the author opposes democracy"], answer: 0,
                 pointTag: "阅读·写作意图",
                 strategy: ["定位原词 the silent majority 所在句", "silent 对应‘不发声’，majority 对应‘多数’", "结合段落论点判断作者意图是‘多数人未表达意见’"],
                 trap: "把 silent 误解为‘安静的环境’，或脱离段落自行联想。", difficulty: 0.55),
        Question(id: "r9-02", module: .reading, levelId: "L4",
                 stem: "Why does the writer begin the passage with a question?",
                 options: ["To draw readers in and introduce the topic", "To show that he has no answer", "To make the article longer", "To end the discussion"], answer: 0,
                 pointTag: "阅读·写作手法",
                 strategy: ["问句开篇常见作用是设疑引趣", "后文随即展开讨论，说明是引出话题", "排除与后文走向矛盾的选项"],
                 trap: "把修辞性问句当成作者真的不知道答案。", difficulty: 0.5),
        Question(id: "r9-03", module: .reading, levelId: "L4",
                 stem: "Which of the following would the author most likely agree with?",
                 options: ["Small daily habits shape long-term results.", "Talent matters far more than effort.", "Technology solves every problem.", "Money is the only measure of success."], answer: 0,
                 pointTag: "阅读·观点态度",
                 strategy: ["通读寻找反复出现的核心主张", "全文强调积累与坚持的价值", "选与主旨一致的选项"],
                 trap: "绝对化表述(far more/every/only)通常是错误项。", difficulty: 0.5),
        Question(id: "r9-04", module: .reading, levelId: "L4",
                 stem: "The word 'resilient' in paragraph 3 is closest in meaning to ___.",
                 options: ["able to recover quickly", "easily broken", "highly sensitive", "completely silent"], answer: 0,
                 pointTag: "阅读·词义猜测",
                 strategy: ["回到原句看 resilient 修饰的对象", "结合后文‘很快恢复常态’的语境", "确定‘恢复力强’"],
                 trap: "easily broken 与 resilient 含义正好相反。", difficulty: 0.55),
        Question(id: "r9-05", module: .reading, levelId: "L4",
                 stem: "What is the main idea of the passage?",
                 options: ["How a community garden changed a neighbourhood", "The history of city planning", "How to grow tomatoes", "The cost of building a park"], answer: 0,
                 pointTag: "阅读·主旨大意",
                 strategy: ["概括各段大意再取交集", "文章首尾都围绕社区花园展开", "选覆盖全文、最具概括力的选项"],
                 trap: "只讲种植或花费的选项属于细节，不能作主旨。", difficulty: 0.45),
        Question(id: "r9-06", module: .reading, levelId: "L4",
                 stem: "The author mentions the 1998 study mainly to ___.",
                 options: ["support the argument with evidence", "introduce a new topic", "criticise earlier research", "describe a personal experience"], answer: 0,
                 pointTag: "阅读·论据作用",
                 strategy: ["看该研究出现的位置与上下文论点", "研究是用来佐证作者观点的", "确定‘提供论据’"],
                 trap: "研究不是作者的亲身经历，也不是为了批评前人。", difficulty: 0.55),
        Question(id: "r9-07", module: .reading, levelId: "L4",
                 stem: "What can be inferred from the last paragraph?",
                 options: ["The program will probably continue.", "The program has already failed.", "Nobody joined the program.", "The writer will leave the city."], answer: 0,
                 pointTag: "阅读·推理判断",
                 strategy: ["末段常交代走向或前景", "原文提到反响良好与续期计划", "推出‘项目很可能继续’"],
                 trap: "推理必须基于原文线索，不能凭空否定或夸大。", difficulty: 0.6),
        Question(id: "r9-08", module: .reading, levelId: "L4",
                 stem: "The tone of the passage is best described as ___.",
                 options: ["objective yet concerned", "angry and bitter", "humorous and light", "cold and distant"], answer: 0,
                 pointTag: "阅读·语气态度",
                 strategy: ["看形容词与评价性用词", "文章摆事实但不冷漠，含关切之情", "确定 objective yet concerned"],
                 trap: "幽默、愤怒等情绪在文中没有依据。", difficulty: 0.55),
        Question(id: "r9-09", module: .reading, levelId: "L4",
                 stem: "Which sentence best shows that the author changed her mind?",
                 options: ["'I used to think practice was pointless, until the results proved otherwise.'", "'The weather was fine that morning.'", "'She walked into the room quietly.'", "'The train arrived on time.'"], answer: 0,
                 pointTag: "阅读·细节理解",
                 strategy: ["找含有今昔对比标记的句子", "used to...until... 明确表示态度转变", "其余句子只是客观叙述"],
                 trap: "细节描写句不含态度变化的信息。", difficulty: 0.5),

        // L5 应用文（8）
        Question(id: "a9-01", module: .appliedWriting, levelId: "L5",
                 stem: "写感谢信时，开头最恰当的一句是？",
                 options: ["I am writing to express my sincere thanks for your help.", "I am writing to complain about your service.", "I am writing to apply for the position.", "I am writing to say goodbye forever."], answer: 0,
                 pointTag: "应用文·感谢信",
                 strategy: ["感谢信首句要点明写作目的", "用 express my thanks 直接表明意图", "排除投诉、申请、告别等无关功能句"],
                 trap: "首句不要绕弯，否则读者无法立刻判断信件类型。", difficulty: 0.4),
        Question(id: "a9-02", module: .appliedWriting, levelId: "L5",
                 stem: "写一则活动通知，正文必须包含的信息是？",
                 options: ["时间、地点、参加对象与事项", "作者的兴趣爱好", "当天的天气情况", "作者的个人感受"], answer: 0,
                 pointTag: "应用文·通知要素",
                 strategy: ["通知的本质是让人能按时到场", "四要素：时间、地点、参加对象、事项", "与之无关的信息一律删去"],
                 trap: "通知里写感受或天气会挤占关键信息。", difficulty: 0.4),
        Question(id: "a9-03", module: .appliedWriting, levelId: "L5",
                 stem: "邀请信的结尾通常怎样写才得体？",
                 options: ["We look forward to your reply.", "Please pay the bill today.", "I quit my job last week.", "Good luck with nothing."], answer: 0,
                 pointTag: "应用文·邀请信",
                 strategy: ["邀请信结尾要表达期待回复", "用 look forward to 的固定表达", "语气礼貌且不施压"],
                 trap: "账单、辞职等句子与邀请信功能无关。", difficulty: 0.4),
        Question(id: "a9-04", module: .appliedWriting, levelId: "L5",
                 stem: "申请信中说明自己的优势时，应该？",
                 options: ["用具体经历和事例来支撑", "反复强调自己很优秀", "只谈自己的缺点", "完全不提任何经历"], answer: 0,
                 pointTag: "应用文·申请信",
                 strategy: ["优势要有证据，不能空喊", "挑选与申请事项最相关的一两个经历", "先写做法，再写结果"],
                 trap: "自夸式形容词没有说服力，招聘方要看事实。", difficulty: 0.45),
        Question(id: "a9-05", module: .appliedWriting, levelId: "L5",
                 stem: "写投诉信时，语气应当？",
                 options: ["礼貌克制但立场明确", "愤怒并带有威胁", "含糊其辞不敢说明", "一味恭维不做要求"], answer: 0,
                 pointTag: "应用文·投诉信",
                 strategy: ["投诉信要解决问题而非发泄情绪", "先说明事实，再提出具体要求", "保持礼貌有利于对方配合"],
                 trap: "情绪化表达会让对方产生防御，反而不利于解决。", difficulty: 0.45),
        Question(id: "a9-06", module: .appliedWriting, levelId: "L5",
                 stem: "倡议书的写作目的主要是？",
                 options: ["呼吁大家共同参与某项行动", "介绍一部电影的剧情", "批评某一个具体的人", "总结一场比赛的比分"], answer: 0,
                 pointTag: "应用文·倡议书",
                 strategy: ["倡议书的核心是号召行动", "要明确倡议内容与参与方式", "结尾再次发出号召"],
                 trap: "写成剧情介绍或赛事总结就偏离了文体功能。", difficulty: 0.4),
        Question(id: "a9-07", module: .appliedWriting, levelId: "L5",
                 stem: "建议信中的建议部分，较好的写法是？",
                 options: ["分条列出，并逐条说明理由", "只给一条且不解释", "只批评现状不给建议", "只讲大道理不提做法"], answer: 0,
                 pointTag: "应用文·建议信",
                 strategy: ["建议要分条，便于对方执行", "每条都说明理由，增强说服力", "语气用 I suggest / It would help to..."],
                 trap: "只批评不提方案，对方无法行动。", difficulty: 0.45),
        Question(id: "a9-08", module: .appliedWriting, levelId: "L5",
                 stem: "英文书信中 'Dear Sir or Madam' 适用于哪种情况？",
                 options: ["不知道收信人姓名时", "写给亲密好友时", "写给家人时", "写给同班同学时"], answer: 0,
                 pointTag: "应用文·称呼",
                 strategy: ["正式书信在不知姓名时用通用称呼", "知道姓名则直接写 Dear Mr. Smith", "亲友之间用名字即可"],
                 trap: "对熟人用 Sir or Madam 会显得生分。", difficulty: 0.35),

        // L6 读后续写（5）
        Question(id: "w9-01", module: .continuation, levelId: "L6",
                 stem: "第一段的首句已给出，接下来最应该怎样写？",
                 options: ["顺着首句展开人物的动作与心理", "另起一个完全无关的场景", "直接跳到结局不做铺垫", "把前文内容复述一遍"], answer: 0,
                 pointTag: "续写·情节衔接",
                 strategy: ["首句已定方向，后文必须承接", "补上动作、心理、环境细节推进情节", "避免新增无关人物"],
                 trap: "复述前文或跳到结局都会被判为衔接不当。", difficulty: 0.5),
        Question(id: "w9-02", module: .continuation, levelId: "L6",
                 stem: "两段续写之间必须保持一致的是？",
                 options: ["人称、时态与人物性格", "只要情节精彩即可", "可以随意更换人称", "时态可以来回切换"], answer: 0,
                 pointTag: "续写·一致性",
                 strategy: ["检查人称是否仍与原文一致", "检查时态是否沿用原文的过去时", "检查人物性格是否与前文吻合"],
                 trap: "人称或时态跳变是续写最常见的扣分点。", difficulty: 0.5),
        Question(id: "w9-03", module: .continuation, levelId: "L6",
                 stem: "要让续写更有画面感，应该多写？",
                 options: ["动作、神态与环境细节", "抽象的评价性词语", "大段议论和说理", "反复堆砌同一个形容词"], answer: 0,
                 pointTag: "续写·细节描写",
                 strategy: ["用具体动词替代笼统评价", "加入神态与感官细节", "让情节自己说话，少发议论"],
                 trap: "抽象形容词再多也造不出画面。", difficulty: 0.5),
        Question(id: "w9-04", module: .continuation, levelId: "L6",
                 stem: "续写的结尾较好的处理方式是？",
                 options: ["呼应前文伏笔并升华主题", "写到一半突然中断", "在结尾引入全新人物", "毫无铺垫地改成悲剧"], answer: 0,
                 pointTag: "续写·结尾升华",
                 strategy: ["回看前文埋下的伏笔", "结尾照应伏笔，形成闭环", "用一句感悟自然升华，不喊口号"],
                 trap: "结尾硬转悲剧或新增人物会让故事失衡。", difficulty: 0.55),
        Question(id: "w9-05", module: .continuation, levelId: "L6",
                 stem: "续写中想提升语言档次，应优先使用？",
                 options: ["倒装、非谓语与定语从句", "生僻但用错的难词", "不管对错的长难句堆砌", "清一色的简单句"], answer: 0,
                 pointTag: "续写·语言升级",
                 strategy: ["在保证正确的前提下使用复杂结构", "倒装强调情绪、非谓语压缩信息", "每句写完检查主谓是否完整"],
                 trap: "宁可句式简单也不能写错句。", difficulty: 0.55),

        // L7 听力（9）
        Question(id: "ln9-01", module: .listening, levelId: "L7",
                 stem: "What is the announcement mainly about?",
                 listeningScript: script9_1,
                 options: ["A school English festival", "A sports meeting", "A maths exam", "A book sale"], answer: 0,
                 pointTag: "听力·主旨大意",
                 strategy: ["听前扫选项，判断这是主旨题", "抓住开头重复出现的 English festival", "整段围绕节日安排展开"],
                 trap: "只听到个别词如 hall 就误判成运动会。", difficulty: 0.35),
        Question(id: "ln9-02", module: .listening, levelId: "L7",
                 stem: "When does the speech contest start?",
                 listeningScript: script9_1,
                 options: ["At two thirty", "At two", "At four", "At three thirty"], answer: 0,
                 pointTag: "听力·时间信息",
                 strategy: ["预判数字题，重点听 contest 后的时间", "男士问 two，女士更正为 two thirty", "锁定 two thirty"],
                 trap: "two 是干扰项，four 是话剧的时间。", difficulty: 0.4),
        Question(id: "ln9-03", module: .listening, levelId: "L7",
                 stem: "Where will the festival be held?",
                 listeningScript: script9_1,
                 options: ["In the school hall", "On the playground", "In the library", "In the gym"], answer: 0,
                 pointTag: "听力·地点信息",
                 strategy: ["预判地点题，激活场所词汇", "听到 in the school hall", "其余场所未被提及"],
                 trap: "操场、图书馆都是常见场所词，但原文未出现。", difficulty: 0.35),
        Question(id: "ln9-04", module: .listening, levelId: "L7",
                 stem: "Why should students come early?",
                 listeningScript: script9_1,
                 options: ["Seats are limited", "Tickets must be bought", "It may rain", "The hall closes early"], answer: 0,
                 pointTag: "听力·原因细节",
                 strategy: ["预判原因题，注意 so 后的解释", "听到 seats are limited, so come early", "确定座位有限"],
                 trap: "原文说 free for all students，不需要买票。", difficulty: 0.45),
        Question(id: "ln9-05", module: .listening, levelId: "L7",
                 stem: "What does the woman say about the weather?",
                 listeningScript: script9_1,
                 options: ["It will not affect the event", "The festival may be cancelled", "It will rain heavily", "They will move outdoors"], answer: 0,
                 pointTag: "听力·细节判断",
                 strategy: ["预判天气相关表述", "听到 everything is indoors，天气不成问题", "确定不会影响"],
                 trap: "男士提到 rain 只是假设，女士否定了这一顾虑。", difficulty: 0.45),
        Question(id: "ln9-06", module: .listening, levelId: "L7",
                 stem: "What did Lisa do in the mountain village?",
                 listeningScript: script9_2,
                 options: ["She taught English", "She built houses", "She worked as a doctor", "She sold books"], answer: 0,
                 pointTag: "听力·细节捕捉",
                 strategy: ["预判职业题，注意 I ... there 的自述", "听到 I taught English there", "锁定教英语"],
                 trap: "盖房、行医都是常见志愿活动，容易先入为主。", difficulty: 0.4),
        Question(id: "ln9-07", module: .listening, levelId: "L7",
                 stem: "What was the hardest part at first?",
                 listeningScript: script9_2,
                 options: ["The language barrier", "The long walks", "The cold weather", "The lack of food"], answer: 0,
                 pointTag: "听力·细节定位",
                 strategy: ["预判困难题，注意 hardest 后的回答", "听到 the language barrier", "确定语言障碍"],
                 trap: "走路、天气、食物都是干扰项，原文未提。", difficulty: 0.45),
        Question(id: "ln9-08", module: .listening, levelId: "L7",
                 stem: "How did Lisa deal with the problem?",
                 listeningScript: script9_2,
                 options: ["By using pictures and games", "By giving up", "By speaking louder", "By hiring a translator"], answer: 0,
                 pointTag: "听力·信息推理",
                 strategy: ["注意 How did you deal with it 后的回答", "听到 used pictures and games", "确定用图片和游戏"],
                 trap: "提高音量、请翻译都是想当然的解决办法。", difficulty: 0.5),
        Question(id: "ln9-09", module: .listening, levelId: "L7",
                 stem: "How does Lisa feel about going back?",
                 listeningScript: script9_2,
                 options: ["She would go back immediately", "She refuses to go back", "She is unsure", "She wants a different job"], answer: 0,
                 pointTag: "听力·态度判断",
                 strategy: ["注意 Would you go back 的回答", "听到 In a heartbeat（立刻、毫不犹豫）", "推出她非常愿意回去"],
                 trap: "把 In a heartbeat 误听成犹豫不决。", difficulty: 0.55)
    ]

    // MARK: 套卷六补充（7 道：按模块配平后并入 extended8）

    static let paper6Supplement: [Question] = [
        Question(id: "g9-p6-01", module: .grammarFill, levelId: "L1",
                 stem: "The number of applicants for the program ___ risen sharply this year.",
                 options: ["has", "have", "are", "were"], answer: 0,
                 pointTag: "主谓一致·the number of",
                 strategy: ["the number of + 复数名词，谓语用单数", "a number of 才接复数谓语", "确定 has"],
                 trap: "applicants 是复数，容易误填 have。", difficulty: 0.6),
        Question(id: "c9-p6-01", module: .cloze, levelId: "L2",
                 stem: "The teacher's praise gave her the ___ to keep trying.",
                 options: ["confidence", "convenience", "consequence", "competence"], answer: 0,
                 pointTag: "完形·名词辨析",
                 strategy: ["表扬带来的是继续尝试的信心", "give sb. confidence to do sth.", "确定 confidence"],
                 trap: "四个词形近，但只有 confidence 能与‘继续尝试’构成因果。", difficulty: 0.5),
        Question(id: "s9-p6-01", module: .sevenChoose, levelId: "L3",
                 stem: "空白处后一句为 'The same rule applies to writing.'，应填入？",
                 options: ["Reading aloud improves your memory", "Writing is a waste of time", "Nobody likes grammar", "The meeting was cancelled"], answer: 0,
                 pointTag: "七选五·主题句",
                 strategy: ["后文 the same rule 说明前句讲了一条规律", "规律应来自学习方法的主题", "朗读有助于记忆可与写作规则并列"],
                 trap: "贬低写作或说会议取消都偏离了‘学习方法’主题。", difficulty: 0.5),
        Question(id: "r9-p6-01", module: .reading, levelId: "L4",
                 stem: "According to the passage, why did the team slow down?",
                 options: ["They realised speed was costing them accuracy", "They ran out of money", "They lost interest in the work", "The manager resigned suddenly"], answer: 0,
                 pointTag: "阅读·因果细节",
                 strategy: ["定位 slow down 所在句", "向后找 because/realised 等因果标记", "确定是速度牺牲了准确率"],
                 trap: "资金、兴趣、人事变动都是无中生有的原因。", difficulty: 0.55),
        Question(id: "r9-p6-02", module: .reading, levelId: "L4",
                 stem: "Which of the following is the best title for the passage?",
                 options: ["Why slow readers remember more", "How to read faster", "The history of printing", "A guide to city libraries"], answer: 0,
                 pointTag: "阅读·标题概括",
                 strategy: ["标题要覆盖全文主旨且有吸引力", "全文论证慢读与记忆的关系", "选含核心矛盾的选项"],
                 trap: "‘如何读得快’与文章立场相反。", difficulty: 0.5),
        Question(id: "a9-p6-01", module: .appliedWriting, levelId: "L5",
                 stem: "一篇活动报道的最后一段通常写什么？",
                 options: ["活动的意义与师生反响", "把通知再抄一遍", "介绍自己的家庭情况", "宣布活动取消"], answer: 0,
                 pointTag: "应用文·报道结构",
                 strategy: ["报道按‘过程—亮点—意义’推进", "末段收束在影响与反馈上", "不重复前文的通知内容"],
                 trap: "报道是事后回顾，不能再出现通知口吻。", difficulty: 0.45),
        Question(id: "ln9-p6-01", module: .listening, levelId: "L7",
                 stem: "What does Lisa mean by her last words?",
                 listeningScript: script9_2,
                 options: ["The experience changed her deeply", "The children learned nothing", "She regrets going there", "She found the work boring"], answer: 0,
                 pointTag: "听力·句意理解",
                 strategy: ["定位最后一句 The children changed me more than I changed them", "比较级说明她自己被改变得更多", "推出这段经历对她影响很深"],
                 trap: "把 more than 的比较方向听反，会误选‘她后悔了’。", difficulty: 0.6)
    ]

    // MARK: 第九批听力材料

    private static let script9_1 =
    "W: Attention please. The school English festival will be held next Friday in the school hall. " +
    "M: Will the speech contest start at two? " +
    "W: No, it starts at two thirty, and the drama show begins at four. " +
    "M: Do we need tickets? " +
    "W: No, it is free for all students, but seats are limited, so come early. " +
    "M: What if it rains? " +
    "W: Everything is indoors, so the weather will not be a problem."

    private static let script9_2 =
    "M: Today we are talking with Lisa, who spent a year volunteering in a mountain village. " +
    "W: Yes, I taught English there. " +
    "M: What was the hardest part? " +
    "W: At first, the language barrier. Many children spoke only the local dialect. " +
    "M: How did you deal with it? " +
    "W: I used pictures and games, and slowly we could understand each other. " +
    "M: Would you go back? " +
    "W: In a heartbeat. The children changed me more than I changed them."
}
