import Foundation

/// 二期扩充题（第五批）。阅读/应用文/读后续写推到 30 题，题型靶场全线补满。
extension QuestionBank {

    static let extended5: [Question] =
        reading4 + reading5 + applied4 + continuation4

    // MARK: 阅读理解 r21–r30（第五、六篇短文）

    private static let passage5 =
    "When Daniel noticed that his deaf classmate, Amy, struggled to follow group discussions, he didn't just feel " +
    "sorry for her—he built something. Using parts from an old phone and a microphone, Daniel created a small device " +
    "that turned spoken words into text on a screen. It took him three failed prototypes and countless late nights " +
    "before it finally worked. Now Amy reads every class discussion in real time, and several other schools have asked " +
    "to borrow Daniel's design. \"I just wanted my friend to stop missing out,\" Daniel said with a shrug."

    static let reading4: [Question] = [
        Question(id: "r21", module: .reading, levelId: "L4",
            stem: passage5 + "\n\nWhat problem did Daniel notice about his classmate Amy?",
            options: ["She found it hard to follow group discussions.", "She had lost her phone.",
                      "She could not afford a computer.", "She disliked working in groups."], answer: 0,
            pointTag: "细节·定位",
            strategy: ["回原文 struggled to follow group discussions", "定位句即题干的同义改写", "选第一项"],
            trap: "其余选项原文均未提及。", difficulty: 0.35),
        Question(id: "r22", module: .reading, levelId: "L4",
            stem: passage5 + "\n\nHow many prototypes failed before Daniel's device worked?",
            options: ["Three", "Two", "Five", "None"], answer: 0,
            pointTag: "细节·数字定位",
            strategy: ["回原文 three failed prototypes", "定位句直接给出数字", "选 Three"],
            trap: "其余数字均为原文未提及的干扰项。", difficulty: 0.3),
        Question(id: "r23", module: .reading, levelId: "L4",
            stem: passage5 + "\n\nWhat can we infer about Daniel?",
            options: ["He is caring and resourceful.", "He dislikes spending time with friends.",
                      "He is interested only in profit.", "He gave up easily after the first failure."], answer: 0,
            pointTag: "推理·人物品质",
            strategy: ["原文:为帮朋友造装置，且三次失败仍坚持", "据行为推断关心他人且有创造力", "选 caring and resourceful"],
            trap: "‘第一次失败就放弃’与‘三次失败仍坚持’相反。", difficulty: 0.55),
        Question(id: "r24", module: .reading, levelId: "L4",
            stem: passage5 + "\n\nWhy did Daniel say \"I just wanted my friend to stop missing out\"?",
            options: ["To explain his real motivation for the invention", "To complain about his classmate",
                      "To ask for money from the school", "To advertise his invention for sale"], answer: 0,
            pointTag: "推理·言外之意",
            strategy: ["这句话紧跟在故事结尾，解释他做这件事的初心", "动机是单纯帮助朋友，不为名利", "选‘解释真实动机’"],
            trap: "原文没有‘卖钱/抱怨同学’的依据，属过度推断。", difficulty: 0.5),
        Question(id: "r25", module: .reading, levelId: "L4",
            stem: passage5 + "\n\nWhich is the best title for the passage?",
            options: ["A Small Invention, A Big Difference", "How Phones Are Made",
                      "The History of Sign Language", "A School Without Computers"], answer: 0,
            pointTag: "主旨·标题归纳",
            strategy: ["全文讲一个小发明帮助同学融入课堂讨论", "标题需概括‘小发明+大改变’", "选第一项"],
            trap: "‘手机制造历史’只是材料来源细节，非主旨。", difficulty: 0.55),
    ]

    private static let passage6 =
    "Last season, Wei finished last in almost every swim meet. Instead of quitting, she asked her coach for honest " +
    "feedback after every race. He pointed out one small fix at a time—her breathing, her turns, her start. Wei " +
    "practiced each fix for weeks before moving to the next. By the final meet of the season, she had shaved twelve " +
    "seconds off her best time and placed third. Her coach later said, \"She didn't get faster overnight. She just " +
    "refused to stay the same.\""

    static let reading5: [Question] = [
        Question(id: "r26", module: .reading, levelId: "L4",
            stem: passage6 + "\n\nHow did Wei perform last season at the start?",
            options: ["She finished last in nearly every race.", "She broke a school record.",
                      "She refused to compete at all.", "She won every meet easily."], answer: 0,
            pointTag: "细节·定位",
            strategy: ["回原文 finished last in almost every swim meet", "定位句直接对应题干", "选第一项"],
            trap: "其余选项与原文相反或未提及。", difficulty: 0.3),
        Question(id: "r27", module: .reading, levelId: "L4",
            stem: passage6 + "\n\nWhat did Wei's coach do after every race?",
            options: ["Gave her honest, specific feedback", "Told her to quit swimming",
                      "Ignored her completely", "Compared her unfavorably to other swimmers"], answer: 0,
            pointTag: "细节·定位",
            strategy: ["回原文 asked her coach for honest feedback", "定位:He pointed out one small fix at a time", "选第一项"],
            trap: "其余选项原文未提及，或与‘耐心指出问题’相反。", difficulty: 0.4),
        Question(id: "r28", module: .reading, levelId: "L4",
            stem: passage6 + "\n\nHow much faster was Wei's best time by the final meet?",
            options: ["Twelve seconds", "Twenty seconds", "Two minutes", "Three seconds"], answer: 0,
            pointTag: "细节·数字定位",
            strategy: ["回原文 shaved twelve seconds off her best time", "定位句直接给出数字", "选 Twelve seconds"],
            trap: "其余数字均为原文未提及的干扰项。", difficulty: 0.3),
        Question(id: "r29", module: .reading, levelId: "L4",
            stem: passage6 + "\n\nWhat does the coach's quote mainly suggest?",
            options: ["Steady effort, not luck, brought her progress.", "She improved due to natural talent alone.",
                      "Her success happened in a single night.", "Coaches deserve all the credit for her success."], answer: 0,
            pointTag: "推理·言外之意",
            strategy: ["‘didn't get faster overnight…refused to stay the same’", "强调持续努力而非天赋或运气", "选‘稳定的努力带来进步’"],
            trap: "‘一夜之间成功’与‘didn't get faster overnight’直接相反。", difficulty: 0.55),
        Question(id: "r30", module: .reading, levelId: "L4",
            stem: passage6 + "\n\nWhich is the best title for the passage?",
            options: ["Small Fixes, Steady Progress", "The Rules of Competitive Swimming",
                      "Why Talent Matters Most", "A Coach's Daily Schedule"], answer: 0,
            pointTag: "主旨·标题归纳",
            strategy: ["全文讲她一点点改进直到进步显著", "标题需概括‘小修正+持续进步’", "选第一项"],
            trap: "‘天赋最重要’与全文‘靠努力非天赋’的主旨相反。", difficulty: 0.55),
    ]

    // MARK: 应用文 a16–a30

    static let applied4: [Question] = [
        Question(id: "a16", module: .appliedWriting, levelId: "L5",
            stem: "写信向学校建议增设社团，开头哪句最佳？",
            options: ["I am writing to suggest that our school set up a photography club.",
                      "School should have photography club.", "I think club is good idea.", "Give us a club please now."], answer: 0,
            pointTag: "应用文·建议信开头",
            strategy: ["I am writing to suggest that… 标准建议信框架", "suggest 后接 (that) sb (should) do", "排除残缺/口语化句"],
            trap: "‘School should have’ 缺逻辑主语，且非正式语域。", difficulty: 0.4),
        Question(id: "a17", module: .appliedWriting, levelId: "L5",
            stem: "对网购商品不满写投诉信，开头哪句最得体？",
            options: ["I am writing to complain about the faulty product I received last week.",
                      "Your product is bad, I am angry.", "This thing you sold no good.", "I complain you now about product."], answer: 0,
            pointTag: "应用文·投诉信开头",
            strategy: ["complain about sth 固定搭配", "点明事由(faulty product)+时间", "排除口语化/语法错"],
            trap: "‘I complain you’ 缺介词 about，且语气欠礼貌。", difficulty: 0.4),
        Question(id: "a18", module: .appliedWriting, levelId: "L5",
            stem: "想表达‘非常感激你的耐心指导’，哪句更得体？",
            options: ["I'm truly grateful for your patient guidance throughout this project.",
                      "Thanks you teach me patient.", "You guide me patient, thanks much.", "I thank your patient very."], answer: 0,
            pointTag: "应用文·感谢句·grateful for",
            strategy: ["be grateful for sth 固定搭配", "throughout this project 补充具体情境", "排除语法错误的选项"],
            trap: "其余选项均存在明显语法错误(动词形式/词性混用)。", difficulty: 0.4),
        Question(id: "a19", module: .appliedWriting, levelId: "L5",
            stem: "投诉信结尾想表达‘希望尽快解决这个问题’，哪句最佳？",
            options: ["I would appreciate a prompt solution to this issue.",
                      "Solve it fast please now.", "You must fix problem soon.", "Fix now or I am angry."], answer: 0,
            pointTag: "应用文·投诉信结尾·礼貌而坚定",
            strategy: ["I would appreciate + 名词 是礼貌且正式的表达", "prompt solution = 迅速解决", "排除命令式/威胁式语气"],
            trap: "‘Fix now or I am angry’ 带威胁语气，不符合正式投诉信语域。", difficulty: 0.45),
        Question(id: "a20", module: .appliedWriting, levelId: "L5",
            stem: "给交换生写信介绍本地美食文化，开头哪句最佳？",
            options: ["Let me tell you something about the local food culture here.",
                      "Food here, you will like, I think so.", "I tell you food now ok.", "Local food very good you know."], answer: 0,
            pointTag: "应用文·介绍性开头",
            strategy: ["Let me tell you something about… 自然引出话题", "语法完整、语域适中", "排除中式直译/残缺句"],
            trap: "其余选项均为中式直译，语法不通顺。", difficulty: 0.4),
        Question(id: "a21", module: .appliedWriting, levelId: "L5",
            stem: "想表达‘这次经历让我受益匪浅’，哪句更地道？",
            options: ["This experience has taught me a great deal.",
                      "This experience let me learn many many things.", "I benefit much from this experience very.", "This experience good for learning things."], answer: 0,
            pointTag: "应用文·亮点句·teach sb a great deal",
            strategy: ["teach sb a great deal = 使人受益良多", "表达精炼且地道", "排除累赘/语法错的选项"],
            trap: "‘learn many many things’ 重复堆砌，不地道。", difficulty: 0.45),
        Question(id: "a22", module: .appliedWriting, levelId: "L5",
            stem: "写信申请学校的奖学金，开头哪句最规范？",
            options: ["I am writing to apply for the scholarship offered by your school.",
                      "I want money from school scholarship.", "Give me scholarship please.", "Scholarship I want very much."], answer: 0,
            pointTag: "应用文·申请信开头",
            strategy: ["apply for sth 固定搭配", "点明事由:申请奖学金", "排除直白/失礼的表达"],
            trap: "‘Give me scholarship please’ 语气如同索要，不适合申请信。", difficulty: 0.4),
        Question(id: "a23", module: .appliedWriting, levelId: "L5",
            stem: "推荐一本书给笔友，从介绍书名过渡到讲述理由，哪句最自然？",
            options: ["The reason I recommend it is that it changed the way I see the world.",
                      "Why I tell you is book good.", "Reason is book is nice for reading.", "Because book nice I tell you it."], answer: 0,
            pointTag: "应用文·过渡句·the reason is that",
            strategy: ["The reason (why) I … is that … 是规范的解释性过渡句", "后接完整从句", "排除语序混乱/语法错的选项"],
            trap: "其余选项语序混乱，明显是中式直译。", difficulty: 0.45),
        Question(id: "a24", module: .appliedWriting, levelId: "L5",
            stem: "想委婉拒绝一个邀请，哪句最得体？",
            options: ["I'm afraid I won't be able to make it this time, but thank you for thinking of me.",
                      "No, I can't come, sorry.", "I don't want to come this time.", "Not possible for me, bye."], answer: 0,
            pointTag: "应用文·委婉拒绝句",
            strategy: ["I'm afraid + 委婉拒绝", "加 but thank you for… 缓和语气", "排除生硬/简短失礼的表达"],
            trap: "‘Not possible for me, bye’ 过于生硬，缺乏礼貌缓冲。", difficulty: 0.5),
        Question(id: "a25", module: .appliedWriting, levelId: "L5",
            stem: "写一封寻物启事，开头哪句最规范？",
            options: ["I lost my black backpack somewhere near the school library yesterday afternoon.",
                      "My bag lost, help me find.", "Bag gone yesterday near library.", "I lost bag, very sad now."], answer: 0,
            pointTag: "应用文·寻物启事·信息完整",
            strategy: ["寻物启事需交代物品+地点+时间", "句子结构完整、信息齐全", "排除信息残缺/语法错的选项"],
            trap: "其余选项缺主语或动词，信息不完整。", difficulty: 0.4),
        Question(id: "a26", module: .appliedWriting, levelId: "L5",
            stem: "想表达‘我对这个项目非常感兴趣，期待能加入’，哪句最佳？",
            options: ["I'm genuinely interested in this project and would love to be a part of it.",
                      "I interested project, want join.", "Project interesting, I join maybe.", "I am very interest to join this."], answer: 0,
            pointTag: "应用文·亮点句·be interested in",
            strategy: ["be genuinely interested in… 表达诚意", "would love to be a part of… 礼貌且积极", "排除语法错误的选项(interest 词性误用)"],
            trap: "‘very interest’ 应为 interested，词性误用。", difficulty: 0.4),
        Question(id: "a27", module: .appliedWriting, levelId: "L5",
            stem: "写信向校长反映食堂问题，结尾呼吁改进，哪句最佳？",
            options: ["I sincerely hope the canteen service can be improved soon.",
                      "Canteen bad, change now please.", "Please change canteen, thanks bye.", "Improve canteen or we complain more."], answer: 0,
            pointTag: "应用文·呼吁改进结尾",
            strategy: ["sincerely hope + 从句 表达真诚期望", "can be improved 用被动语态显客观", "排除生硬/带威胁意味的表达"],
            trap: "‘or we complain more’ 带威胁意味，不适合正式信函。", difficulty: 0.5),
        Question(id: "a28", module: .appliedWriting, levelId: "L5",
            stem: "感谢信中从笼统感谢过渡到具体细节，哪句最自然？",
            options: ["In particular, I really enjoyed the cultural workshop on the second day.",
                      "Also workshop day two good for me.", "Workshop second day, I like very.", "And the workshop, second day, nice."], answer: 0,
            pointTag: "应用文·过渡句·In particular",
            strategy: ["In particular 引出具体细节，承接上文笼统的感谢", "后接完整句", "排除语序混乱的选项"],
            trap: "其余选项语序混乱，缺乏正式信函应有的句子结构。", difficulty: 0.45),
        Question(id: "a29", module: .appliedWriting, levelId: "L5",
            stem: "想表达‘无论结果如何，我都尽力了’作为信件结尾亮点句，哪句最佳？",
            options: ["Whatever the result turns out to be, I will know I gave it my best.",
                      "No matter result, I tried my best very.", "Result anything, I try hard already.", "I tried best, result not matter."], answer: 0,
            pointTag: "应用文·亮点句·Whatever 让步",
            strategy: ["Whatever + 主语 + 动词 引导让步状语", "give it one's best = 全力以赴", "排除中式直译/语法错"],
            trap: "其余选项受中文语序影响，语法不通顺。", difficulty: 0.5),
        Question(id: "a30", module: .appliedWriting, levelId: "L5",
            stem: "写倡议书呼吁减少使用塑料袋，开头哪句最规范？",
            options: ["It is high time that we took action to reduce the use of plastic bags.",
                      "Plastic bags bad, we stop now.", "We should not plastic bags more.", "Stop plastic bags is good idea."], answer: 0,
            pointTag: "应用文·倡议书开头·It is high time that",
            strategy: ["It is high time that + 从句(用过去式) 表达‘早该……了’的紧迫感", "适合倡议书开头", "排除中式直译/语法错的选项"],
            trap: "‘we should not plastic bags’ 缺动词，语法不通。", difficulty: 0.55),
    ]

    // MARK: 读后续写 k16–k30

    static let continuation4: [Question] = [
        Question(id: "k16", module: .continuation, levelId: "L6",
            stem: "描写‘教室突然安静下来’营造悬念，哪句最佳？",
            options: ["A heavy silence fell over the classroom as every eye turned to the door.",
                      "The classroom became quiet suddenly.", "It was quiet. Everyone looked at door.", "The room was very quiet very much."], answer: 0,
            pointTag: "续写·悬念氛围",
            strategy: ["用 A heavy silence fell over… 营造画面与悬念", "every eye turned to the door 补焦点细节", "排除平铺直叙/语病句"],
            trap: "‘very quiet very much’ 副词堆砌，缺乏画面。", difficulty: 0.6),
        Question(id: "k17", module: .continuation, levelId: "L6",
            stem: "描写‘她内心五味杂陈’，哪句更高级？",
            options: ["A mixture of relief and regret washed over her all at once.",
                      "She felt many feelings at the same time.", "Her heart had feelings, complex ones.", "She felt complex very much inside."], answer: 0,
            pointTag: "续写·复杂心理具体化",
            strategy: ["把‘五味杂陈’拆解为具体情绪(relief/regret)", "wash over sb 描写情绪涌来", "排除笼统/语病句"],
            trap: "‘complex very much’ 既笼统又不地道。", difficulty: 0.6),
        Question(id: "k18", module: .continuation, levelId: "L6",
            stem: "用环境反衬人物心情(她很沮丧，但天气很好)，哪句最佳？",
            options: ["The sun shone brightly outside, yet nothing could lift her heavy heart.",
                      "It was sunny but she was sad.", "Sun was good but heart bad for her.", "Outside sunny, her heart not happy."], answer: 0,
            pointTag: "续写·环境反衬",
            strategy: ["yet 制造‘天气晴朗 vs 心情沉重’的反差", "heavy heart 化抽象情绪为具体意象", "排除直白罗列的选项"],
            trap: "‘Sun was good but heart bad’ 是中式直译，搭配不当。", difficulty: 0.6),
        Question(id: "k19", module: .continuation, levelId: "L6",
            stem: "描写‘脚步声越来越近’营造紧张感，哪句最佳？",
            options: ["Footsteps grew louder behind her, closing in with every second.",
                      "Someone walked behind her, getting near.", "The footstep sound was loud and near.", "Steps came near her more and more."], answer: 0,
            pointTag: "续写·听觉细节+节奏",
            strategy: ["growing louder + closing in 制造逼近的紧张感", "with every second 强化时间紧迫", "排除笼统陈述句"],
            trap: "‘Steps came near her more and more’ 重复且不地道。", difficulty: 0.6),
        Question(id: "k20", module: .continuation, levelId: "L6",
            stem: "用对话+停顿表现人物的犹豫，哪句最佳？",
            options: ["\"I... I don't know if I can do this,\" he said, his voice trailing off.",
                      "He said he was not sure if he could do it.", "\"I don't know\" he said simple.", "He talk and said not sure thing."], answer: 0,
            pointTag: "续写·对话表现犹豫",
            strategy: ["用省略号与 trailing off 直接呈现犹豫", "直接引语比间接转述更有现场感", "排除转述/语病句"],
            trap: "间接转述(He said he was not sure)削弱了犹豫的现场感。", difficulty: 0.55),
        Question(id: "k21", module: .continuation, levelId: "L6",
            stem: "描写‘她紧紧抱住妈妈’传达失而复得的情感，哪句最佳？",
            options: ["She threw her arms around her mother and refused to let go.",
                      "She hugged mom tightly and didn't let go quickly.", "She hold her mother very tight long time.", "Mother and she hugged each very tight."], answer: 0,
            pointTag: "续写·动作传情",
            strategy: ["threw her arms around 比 hugged 更有冲击力/画面感", "refused to let go 传达不舍/失而复得的情感", "排除语法错/笼统表达"],
            trap: "‘hold...very tight long time’ 时态与搭配均有误。", difficulty: 0.55),
        Question(id: "k22", module: .continuation, levelId: "L6",
            stem: "用嗅觉细节描写‘医院的气味’营造场景真实感，哪句最佳？",
            options: ["The sharp smell of disinfectant hung in the hospital corridor.",
                      "The hospital smelled like medicine a lot.", "There was a smell in hospital, not good.", "Hospital smell strong, she did not like."], answer: 0,
            pointTag: "续写·嗅觉细节",
            strategy: ["sharp smell of disinfectant 精准的嗅觉意象", "hung in the corridor 让气味有‘弥漫’的画面感", "排除笼统/语病句"],
            trap: "‘smell in hospital, not good’ 语法残缺且笼统。", difficulty: 0.55),
        Question(id: "k23", module: .continuation, levelId: "L6",
            stem: "描写‘暴风雨突然停了’作为情节转折，哪句最佳？",
            options: ["As suddenly as it had begun, the storm fell silent, leaving only dripping leaves.",
                      "The storm stopped suddenly then.", "Rain stop. Quiet now everywhere.", "The big storm just stopped very fast."], answer: 0,
            pointTag: "续写·情节转折+画面收束",
            strategy: ["As suddenly as it had begun 呼应开头，制造转折的戏剧性", "dripping leaves 补充转折后的画面细节", "排除短句堆砌"],
            trap: "‘Rain stop. Quiet now everywhere.’ 是不完整短句堆砌，缺乏文采。", difficulty: 0.65),
        Question(id: "k24", module: .continuation, levelId: "L6",
            stem: "用比喻描写‘教练的话像一盏灯’，哪句最佳？",
            options: ["His coach's words were like a lamp, guiding him through the darkest moment.",
                      "Coach words were good like light for him.", "His coach said good words, like lamp.", "Coach's words good, helped him much."], answer: 0,
            pointTag: "续写·比喻修辞",
            strategy: ["用 like a lamp 比喻教练话语的指引作用", "guiding him through… 补充比喻的具体作用", "排除直译/语病句"],
            trap: "‘words were good like light’ 比喻生硬，搭配不当。", difficulty: 0.6),
        Question(id: "k25", module: .continuation, levelId: "L6",
            stem: "描写‘她终于松了一口气’，哪句最佳？",
            options: ["A long breath escaped her lips, and her shoulders finally relaxed.",
                      "She breathed out and felt relax now.", "She let breath go and was relax.", "Her breath was long and she relax."], answer: 0,
            pointTag: "续写·身体细节传情",
            strategy: ["escaped her lips + shoulders relaxed 两个身体细节叠加传达‘松了口气’", "比直白的 felt relax 更有画面感", "排除语法错(relax 应为 relaxed)"],
            trap: "‘felt relax’ 词性错误，应为形容词 relaxed。", difficulty: 0.55),
        Question(id: "k26", module: .continuation, levelId: "L6",
            stem: "用对比手法描写‘曾经的胆怯与现在的勇敢’，哪句最佳？",
            options: ["The boy who once hid behind his mother now stood tall before the whole crowd.",
                      "He was shy before but brave now very much.", "Before he scared, now he is brave boy.", "He changed from scared to brave quickly."], answer: 0,
            pointTag: "续写·今昔对比",
            strategy: ["用具体画面(躲在妈妈身后 vs 站在人群前)对比", "比直白的‘以前害怕现在勇敢’更有张力", "排除直白罗列/语病句"],
            trap: "‘he scared’ 缺动词 was，语法有误。", difficulty: 0.6),
        Question(id: "k27", module: .continuation, levelId: "L6",
            stem: "描写‘她在人群中寻找熟悉的脸’，哪句最佳？",
            options: ["Her eyes darted through the crowd, searching for one familiar face.",
                      "She looked at the crowd to find someone she knew.", "She search crowd for a face she know.", "Her eyes saw many people but no one she know."], answer: 0,
            pointTag: "续写·视觉细节+动作",
            strategy: ["darted through 比 looked at 更生动地写出焦急寻找的状态", "one familiar face 聚焦具体目标", "排除时态错误/平淡表达"],
            trap: "‘She search crowd’ 主谓不一致，缺 -es。", difficulty: 0.55),
        Question(id: "k28", module: .continuation, levelId: "L6",
            stem: "续写结尾想呼应文章开头的‘雨’意象，哪句最佳？",
            options: ["By the time he got home, the rain had finally stopped, just like his worries.",
                      "The rain stopped and he went home happy.", "It stopped raining when he arrived home.", "Rain over, he was no longer worried now."], answer: 0,
            pointTag: "续写·首尾呼应",
            strategy: ["By the time…had stopped 呼应开头的雨，时态准确(过去完成)", "just like his worries 把雨与心情关联，升华呼应", "排除单纯陈述、缺乏呼应感的选项"],
            trap: "其余选项只是平铺陈述，没有把‘雨’与‘心情’关联升华。", difficulty: 0.65),
        Question(id: "k29", module: .continuation, levelId: "L6",
            stem: "描写‘火车站台上的离别’瞬间凝固的感觉，哪句最佳？",
            options: ["For a moment, the whole platform seemed to freeze around them.",
                      "The platform was quiet for a moment then.", "Time stopped on platform, they said bye.", "Everyone on platform stood still a bit."], answer: 0,
            pointTag: "续写·夸张/凝固时间手法",
            strategy: ["seemed to freeze 用夸张手法定格瞬间", "around them 聚焦人物，画面感强", "排除平淡叙述"],
            trap: "‘Time stopped on platform’ 表达生硬，缺乏文采修饰。", difficulty: 0.6),
        Question(id: "k30", module: .continuation, levelId: "L6",
            stem: "续写结尾想表达‘这段经历将永远留在记忆里’，哪句最佳？",
            options: ["That afternoon would stay with her, long after the summer had faded.",
                      "She will remember that afternoon forever maybe.", "That afternoon, she will not forget it ever.", "She keep that afternoon in memory always."], answer: 0,
            pointTag: "续写·结尾升华·余韵",
            strategy: ["stay with her 比直白的 remember 更含蓄有余味", "long after the summer had faded 补充时间纵深，富有诗意", "排除直白/语法错的选项"],
            trap: "‘She keep that afternoon’ 主谓不一致，缺 -s。", difficulty: 0.6),
    ]
}
