import Foundation

/// 词汇专项词库。起步 20 词：10 个高频搭配辨析易混词对 + 10 个熟词僻义，三种练法(拼写/搭配/僻义)共用。
enum VocabData {

    static let all: [VocabWord] = collocationWords + polysemyWords + collocationWords2 + polysemyWords2
        + collocationWords3 + polysemyWords3

    static func find(_ id: String) -> VocabWord? { all.first { $0.id == id } }
    /// 按拼写(大小写不敏感)查找，供错因诊断里"具体是哪个词"的自由输入匹配。
    static func find(headword: String) -> VocabWord? {
        let target = headword.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard !target.isEmpty else { return nil }
        return all.first { $0.headword.lowercased() == target }
    }

    // MARK: 搭配辨析·易混词对

    static let collocationWords: [VocabWord] = [
        VocabWord(id: "v_raise", headword: "raise", meaning: "vt. 提高；筹集；抚养(及物，必须带宾语)", tier: 1, category: .collocation,
            example: "The charity managed to raise over ten thousand yuan for the flood victims.",
            exampleMeaning: "这家慈善机构为洪灾受害者筹集了超过一万元。",
            collocations: ["raise money", "raise a question", "raise one's hand"],
            quizStem: "The charity managed to ___ over ten thousand yuan for the flood victims.",
            quizOptions: ["raise", "rise", "lift", "grow"], quizAnswer: 0,
            quizExplanation: "raise 及物，后接宾语 money；rise 不及物，不能直接接宾语。"),
        VocabWord(id: "v_rise", headword: "rise", meaning: "vi. 上升；增长(不及物，不接宾语)", tier: 1, category: .collocation,
            example: "Prices have risen sharply this year, surprising many shoppers.",
            exampleMeaning: "今年物价大幅上涨，让许多购物者感到惊讶。",
            collocations: ["prices rise", "the sun rises", "rise to the challenge"],
            quizStem: "Prices have ___ sharply this year, surprising many shoppers.",
            quizOptions: ["risen", "raised", "rose", "raise"], quizAnswer: 0,
            quizExplanation: "have+过去分词构成现在完成时，rise 的过去分词是 risen；raised 需要宾语，此处主语 prices 是自己上涨，应用不及物的 rise。"),
        VocabWord(id: "v_affect", headword: "affect", meaning: "vt. 影响(及物动词)", tier: 1, category: .collocation,
            example: "Lack of sleep can seriously affect your ability to concentrate.",
            exampleMeaning: "睡眠不足会严重影响你的注意力。",
            collocations: ["affect one's health", "affect the result"],
            quizStem: "Lack of sleep can seriously ___ your ability to concentrate.",
            quizOptions: ["affect", "effect", "effort", "afford"], quizAnswer: 0,
            quizExplanation: "affect 是动词'影响'；effect 是名词'效果'，词性不对就不能直接作谓语。"),
        VocabWord(id: "v_effect", headword: "effect", meaning: "n. 效果；影响", tier: 1, category: .collocation,
            example: "The new policy had a positive effect on local businesses.",
            exampleMeaning: "新政策对当地企业产生了积极影响。",
            collocations: ["have an effect on", "in effect", "side effect"],
            quizStem: "The new policy had a positive ___ on local businesses.",
            quizOptions: ["effect", "affect", "cause", "reason"], quizAnswer: 0,
            quizExplanation: "have a(n)...effect on 是固定搭配，effect 在此作名词；affect 是动词，不能用在 a positive ___ 这个名词位置。"),
        VocabWord(id: "v_borrow", headword: "borrow", meaning: "vt. 借(入)，向别人借", tier: 1, category: .collocation,
            example: "Could I borrow your dictionary for a moment?",
            exampleMeaning: "我能借用一下你的词典吗？",
            collocations: ["borrow sth from sb", "borrow money"],
            quizStem: "Could I ___ your dictionary for a moment?",
            quizOptions: ["borrow", "lend", "rent", "owe"], quizAnswer: 0,
            quizExplanation: "borrow(借入)的方向是'我向你借'；lend(借出)方向相反，是'你借给我'。"),
        VocabWord(id: "v_lend", headword: "lend", meaning: "vt. 借(出)，借给别人", tier: 1, category: .collocation,
            example: "Could you lend me your dictionary for a moment?",
            exampleMeaning: "你能把词典借给我用一下吗？",
            collocations: ["lend sb sth", "lend a hand"],
            quizStem: "Could you ___ me your dictionary for a moment?",
            quizOptions: ["lend", "borrow", "rent", "owe"], quizAnswer: 0,
            quizExplanation: "lend sb sth = 借给某人某物，方向是'你借给我'；borrow 方向相反，是'我向你借'。"),
        VocabWord(id: "v_except", headword: "except", meaning: "prep. 除……之外(排除)", tier: 2, category: .collocation,
            example: "Everyone attended the meeting except Tom, who was ill.",
            exampleMeaning: "除了生病的 Tom，所有人都参加了会议。",
            collocations: ["except for", "everyone except"],
            quizStem: "Everyone attended the meeting ___ Tom, who was ill.",
            quizOptions: ["except", "expect", "accept", "exact"], quizAnswer: 0,
            quizExplanation: "except 表'排除'；expect(期待)/accept(接受)/exact(精确的)都是形近词混淆。"),
        VocabWord(id: "v_expect", headword: "expect", meaning: "vt. 期待，预料", tier: 1, category: .collocation,
            example: "We expect the package to arrive by Friday.",
            exampleMeaning: "我们预计包裹周五前会到。",
            collocations: ["expect sb to do sth", "as expected"],
            quizStem: "We ___ the package to arrive by Friday.",
            quizOptions: ["expect", "except", "accept", "exact"], quizAnswer: 0,
            quizExplanation: "expect sb/sth to do = 期待/预料……会做……；except 意为'除了'，语义不通。"),
        VocabWord(id: "v_economic", headword: "economic", meaning: "adj. 经济的(指整体经济、政策层面)", tier: 2, category: .collocation,
            example: "The government announced several new economic policies to boost growth.",
            exampleMeaning: "政府宣布了几项新的经济政策以促进增长。",
            collocations: ["economic policy", "economic growth"],
            quizStem: "The government announced several new ___ policies to boost growth.",
            quizOptions: ["economic", "economical", "economy", "economics"], quizAnswer: 0,
            quizExplanation: "economic policy(经济政策)是固定搭配；economical 指'节约的'，不能修饰国家层面的政策。"),
        VocabWord(id: "v_economical", headword: "economical", meaning: "adj. 节约的，省钱的(指具体使用方式)", tier: 2, category: .collocation,
            example: "This small car is very economical to run.",
            exampleMeaning: "这辆小车开起来很省油、很省钱。",
            collocations: ["economical to run", "an economical choice"],
            quizStem: "This small car is very ___ to run, costing very little on fuel.",
            quizOptions: ["economical", "economic", "economy", "economics"], quizAnswer: 0,
            quizExplanation: "economical 指'省钱的'，修饰具体的使用方式(开车省油)；economic 指宏观经济层面，搭配对象不同。"),
    ]

    // MARK: 熟词僻义

    static let polysemyWords: [VocabWord] = [
        VocabWord(id: "v_address", headword: "address", meaning: "常义:n. 地址；僻义:vt. 解决，处理", tier: 1, category: .polysemy,
            example: "The committee promised to address the problem of overcrowded classrooms.",
            exampleMeaning: "委员会承诺解决教室拥挤的问题。",
            collocations: ["address a problem", "address an issue"],
            quizStem: "The committee promised to address the problem of overcrowded classrooms. \"Address\" here most likely means ___.",
            quizOptions: ["解决，处理", "地址", "发表演讲", "称呼"], quizAnswer: 0,
            quizExplanation: "address the problem = 解决问题，是动词的僻义；'地址'是它的常见义，此处词性(动词)和语境都不符。"),
        VocabWord(id: "v_last", headword: "last", meaning: "常义:adj. 最后的；僻义:vi. 持续", tier: 1, category: .polysemy,
            example: "The meeting lasted nearly two hours, much longer than expected.",
            exampleMeaning: "会议持续了将近两个小时，比预期长得多。",
            collocations: ["last for hours", "a lasting impression"],
            quizStem: "The meeting lasted nearly two hours, much longer than expected. \"Lasted\" here means ___.",
            quizOptions: ["持续", "排在最后", "勉强够用", "仅仅"], quizAnswer: 0,
            quizExplanation: "lasted nearly two hours = 持续了将近两小时，是动词僻义；'最后的'是形容词常见义，与本句词性不符。"),
        VocabWord(id: "v_figure", headword: "figure", meaning: "常义:n. 数字；僻义:n. 人物；figure out 想出", tier: 1, category: .polysemy,
            example: "She is regarded as a key figure in the fight against climate change.",
            exampleMeaning: "她被视为应对气候变化斗争中的关键人物。",
            collocations: ["a key figure", "figure out"],
            quizStem: "She is regarded as a key figure in the fight against climate change. \"Figure\" here means ___.",
            quizOptions: ["人物", "数字", "图形", "身材"], quizAnswer: 0,
            quizExplanation: "a key figure = 关键人物，是名词僻义；'数字'是常见义，与 key(关键的)搭配不符。"),
        VocabWord(id: "v_subject", headword: "subject", meaning: "常义:n. 科目/主题；僻义:be subject to 使遭受", tier: 1, category: .polysemy,
            example: "Workers in the factory were subjected to extremely poor conditions.",
            exampleMeaning: "工厂里的工人遭受着极其恶劣的工作条件。",
            collocations: ["be subject to", "subject sb to sth"],
            quizStem: "Workers in the factory were subjected to extremely poor conditions. \"Subjected to\" here means ___.",
            quizOptions: ["使遭受", "以……为科目", "使服从", "以……为主题"], quizAnswer: 0,
            quizExplanation: "be subjected to = 遭受，是固定搭配的僻义；'科目/主题'是名词常见义，与本句的被动结构不符。"),
        VocabWord(id: "v_content", headword: "content", meaning: "常义:n. 内容；僻义:adj. be content with 满足的", tier: 2, category: .polysemy,
            example: "Although he wasn't rich, he was content with his simple life.",
            exampleMeaning: "尽管他并不富有，但他对自己简朴的生活感到满足。",
            collocations: ["be content with", "table of contents"],
            quizStem: "Although he wasn't rich, he was content with his simple life. \"Content\" here means ___.",
            quizOptions: ["满足的", "内容", "目录", "含量"], quizAnswer: 0,
            quizExplanation: "be content with = 对……感到满足，是形容词僻义；'内容'是名词常见义，词性和语境都不符。"),
        VocabWord(id: "v_novel", headword: "novel", meaning: "常义:n. 小说；僻义:adj. 新颖的", tier: 2, category: .polysemy,
            example: "Scientists proposed a novel approach to treating the disease.",
            exampleMeaning: "科学家提出了一种治疗这种疾病的新颖方法。",
            collocations: ["a novel idea", "a novel approach"],
            quizStem: "Scientists proposed a novel approach to treating the disease. \"Novel\" here means ___.",
            quizOptions: ["新颖的", "小说", "著名的", "复杂的"], quizAnswer: 0,
            quizExplanation: "a novel approach = 新颖的方法，是形容词僻义；'小说'是名词常见义，此处修饰 approach，须是形容词。"),
        VocabWord(id: "v_bear", headword: "bear", meaning: "常义:n. 熊；僻义:vt. 忍受/承担", tier: 1, category: .polysemy,
            example: "She could hardly bear the pain after the surgery.",
            exampleMeaning: "手术后她几乎无法忍受那种疼痛。",
            collocations: ["bear the pain", "bear responsibility"],
            quizStem: "She could hardly bear the pain after the surgery. \"Bear\" here means ___.",
            quizOptions: ["忍受", "熊", "携带", "生育"], quizAnswer: 0,
            quizExplanation: "bear the pain = 忍受疼痛，是动词僻义；'熊'是名词常见义，与 could hardly(几乎不能)的语境和词性都不符。"),
        VocabWord(id: "v_second", headword: "second", meaning: "常义:第二/秒；僻义:vt. 赞同", tier: 2, category: .polysemy,
            example: "I'd like to second the proposal made by my colleague.",
            exampleMeaning: "我想对我同事提出的建议表示赞同。",
            collocations: ["second a proposal/motion"],
            quizStem: "I'd like to second the proposal made by my colleague. \"Second\" here means ___.",
            quizOptions: ["赞同", "排第二", "秒", "派往(借调)"], quizAnswer: 0,
            quizExplanation: "second the proposal = 赞同提议，是动词僻义，常用于正式会议场景；'第二/秒'是常见义，与本句动词位置不符。"),
        VocabWord(id: "v_mean", headword: "mean", meaning: "常义:v. 意思是；僻义:adj. 吝啬的，卑鄙的", tier: 1, category: .polysemy,
            example: "He was too mean to even buy his friends a cup of coffee.",
            exampleMeaning: "他太吝啬了，甚至不愿意给朋友买一杯咖啡。",
            collocations: ["too mean to do sth"],
            quizStem: "He was too mean to even buy his friends a cup of coffee. \"Mean\" here means ___.",
            quizOptions: ["吝啬的", "意思是", "平均的", "中等的"], quizAnswer: 0,
            quizExplanation: "too mean to do = 太吝啬而不愿做，是形容词僻义；'意思是'是动词常见义，词性不符。"),
        VocabWord(id: "v_present", headword: "present", meaning: "常义:n. 礼物；僻义:adj. 出席的", tier: 1, category: .polysemy,
            example: "All the club members were present at yesterday's meeting.",
            exampleMeaning: "俱乐部所有成员都出席了昨天的会议。",
            collocations: ["be present at"],
            quizStem: "All the club members were present at yesterday's meeting. \"Present\" here means ___.",
            quizOptions: ["出席的", "礼物", "现在的", "赠送"], quizAnswer: 0,
            quizExplanation: "be present at = 出席，是形容词僻义；'礼物'是名词常见义，与 were(系动词)+___+at 的结构不符。"),
    ]

    // MARK: 二期扩充·搭配辨析(10 → 20 词)

    static let collocationWords2: [VocabWord] = [
        VocabWord(id: "v_lay", headword: "lay", meaning: "vt. 放置，摆放(及物，三态 lay-laid-laid)", tier: 1, category: .collocation,
            example: "She carefully laid the baby down in the crib without making a sound.",
            exampleMeaning: "她小心地把婴儿放进婴儿床，没有发出一点声音。",
            collocations: ["lay the table", "lay sth down"],
            quizStem: "She carefully ___ the baby down in the crib without making a sound.",
            quizOptions: ["laid", "lay", "lied", "lain"], quizAnswer: 0,
            quizExplanation: "lay(放置)的过去式是laid，及物动词需带宾语baby；lie(躺/位于)是不及物动词，lied是lie(撒谎)的过去式，意思不符。"),
        VocabWord(id: "v_lie", headword: "lie", meaning: "vi. 躺；位于(不及物，三态 lie-lay-lain)", tier: 1, category: .collocation,
            example: "The old village lies quietly at the foot of the mountain.",
            exampleMeaning: "这个古老的村庄静静地坐落在山脚下。",
            collocations: ["lie at the foot of", "lie in bed"],
            quizStem: "The old village ___ quietly at the foot of the mountain.",
            quizOptions: ["lies", "lays", "lied", "laid"], quizAnswer: 0,
            quizExplanation: "lie(位于)是不及物动词，第三人称单数是lies；lay(放置)是及物动词，此处没有宾语，不能用lay。"),
        VocabWord(id: "v_bring", headword: "bring", meaning: "vt. 带来(朝说话人方向)", tier: 1, category: .collocation,
            example: "Please remember to bring your textbook to class tomorrow.",
            exampleMeaning: "请记得明天把课本带来上课。",
            collocations: ["bring sth to sb", "bring about"],
            quizStem: "Please remember to ___ your textbook to class tomorrow.",
            quizOptions: ["bring", "take", "carry", "fetch"], quizAnswer: 0,
            quizExplanation: "bring 指带向说话人所在的地方；take 指带离说话人所在地，方向相反。"),
        VocabWord(id: "v_take", headword: "take", meaning: "vt. 带走(离开说话人方向)", tier: 1, category: .collocation,
            example: "Don't forget to take your umbrella with you when you leave.",
            exampleMeaning: "你离开的时候别忘了带上雨伞。",
            collocations: ["take sth with you", "take away"],
            quizStem: "Don't forget to ___ your umbrella with you when you leave.",
            quizOptions: ["take", "bring", "carry", "fetch"], quizAnswer: 0,
            quizExplanation: "take 指带离当前地点；bring 指带向说话人所在地，方向相反，此处主语正在离开，应用take。"),
        VocabWord(id: "v_sensible", headword: "sensible", meaning: "adj. 明智的，合理的", tier: 1, category: .collocation,
            example: "It would be sensible to leave early to avoid the traffic jam.",
            exampleMeaning: "提前出发以避开交通堵塞是明智的。",
            collocations: ["a sensible decision", "sensible advice"],
            quizStem: "It would be ___ to leave early to avoid the traffic jam.",
            quizOptions: ["sensible", "sensitive", "sensational", "senseless"], quizAnswer: 0,
            quizExplanation: "sensible 指明智的、合理的；sensitive 指敏感的，与避开堵塞的理性建议语境不符。"),
        VocabWord(id: "v_sensitive", headword: "sensitive", meaning: "adj. 敏感的", tier: 1, category: .collocation,
            example: "Many teenagers are quite sensitive about their appearance.",
            exampleMeaning: "许多青少年对自己的外表相当敏感。",
            collocations: ["sensitive to", "a sensitive topic"],
            quizStem: "Many teenagers are quite ___ about their appearance.",
            quizOptions: ["sensitive", "sensible", "sensational", "senseless"], quizAnswer: 0,
            quizExplanation: "sensitive 指敏感的，常与about搭配；sensible 指明智的，与在意外表的情绪语境不符。"),
        VocabWord(id: "v_successful", headword: "successful", meaning: "adj. 成功的", tier: 2, category: .collocation,
            example: "The fundraising event turned out to be highly successful.",
            exampleMeaning: "这次筹款活动结果非常成功。",
            collocations: ["a successful attempt", "successful in doing sth"],
            quizStem: "The fundraising event turned out to be highly ___.",
            quizOptions: ["successful", "successive", "success", "succeed"], quizAnswer: 0,
            quizExplanation: "successful 是形容词成功的；successive 指连续的，词义不符；success/succeed 词性不对，不能作be后的补语形容词。"),
        VocabWord(id: "v_successive", headword: "successive", meaning: "adj. 连续的，依次的", tier: 2, category: .collocation,
            example: "The team has won the championship for three successive years.",
            exampleMeaning: "这个队连续三年赢得了冠军。",
            collocations: ["successive years", "on successive days"],
            quizStem: "The team has won the championship for three ___ years.",
            quizOptions: ["successive", "successful", "success", "succeeding"], quizAnswer: 0,
            quizExplanation: "successive 指连续的，强调一年接一年；本句考查的搭配点是'连续三年'而非'成功的'，故选successive。"),
        VocabWord(id: "v_historic", headword: "historic", meaning: "adj. 有历史意义的，重大的", tier: 2, category: .collocation,
            example: "Landing on the moon was a historic moment for all of humankind.",
            exampleMeaning: "登上月球对全人类来说是一个具有历史意义的时刻。",
            collocations: ["a historic moment", "historic site"],
            quizStem: "Landing on the moon was a ___ moment for all of humankind.",
            quizOptions: ["historic", "historical", "history", "historian"], quizAnswer: 0,
            quizExplanation: "historic 指具有重大历史意义的；historical 指历史上的、与历史有关的，语义偏中性，与本句'重大意义'不符。"),
        VocabWord(id: "v_historical", headword: "historical", meaning: "adj. 历史的，与历史相关的", tier: 2, category: .collocation,
            example: "The museum displays a collection of historical documents from the last century.",
            exampleMeaning: "博物馆展出了上世纪的一批历史文件。",
            collocations: ["historical documents", "historical research"],
            quizStem: "The museum displays a collection of ___ documents from the last century.",
            quizOptions: ["historical", "historic", "history", "historian"], quizAnswer: 0,
            quizExplanation: "historical 指与历史相关的，修饰documents恰当；historic 强调具有重大意义的，语义过重，不适合泛指的文件。"),
        VocabWord(id: "v_considerate", headword: "considerate", meaning: "adj. 体贴的，考虑周到的(指人)", tier: 2, category: .collocation,
            example: "It was very considerate of you to remember my birthday.",
            exampleMeaning: "你能记得我的生日真是太体贴了。",
            collocations: ["considerate of sb to do sth"],
            quizStem: "It was very ___ of you to remember my birthday.",
            quizOptions: ["considerate", "considerable", "considering", "consideration"], quizAnswer: 0,
            quizExplanation: "considerate 指体贴的，常用 it's considerate of sb to do 句型；considerable 指相当大的，修饰程度而非人的品质。"),
        VocabWord(id: "v_considerable", headword: "considerable", meaning: "adj. 相当大的，可观的", tier: 2, category: .collocation,
            example: "Repairing the old bridge will require a considerable amount of money.",
            exampleMeaning: "修复这座老桥需要相当大的一笔资金。",
            collocations: ["a considerable amount of", "considerable effort"],
            quizStem: "Repairing the old bridge will require a ___ amount of money.",
            quizOptions: ["considerable", "considerate", "considering", "consideration"], quizAnswer: 0,
            quizExplanation: "considerable 指相当大的，修饰amount；considerate 指人体贴的，不能修饰money的数量。"),
        VocabWord(id: "v_principal", headword: "principal", meaning: "n. 校长；adj. 主要的", tier: 1, category: .collocation,
            example: "The principal announced the new school rules at this morning's assembly.",
            exampleMeaning: "校长在今天早上的全校集会上宣布了新的校规。",
            collocations: ["the school principal", "the principal reason"],
            quizStem: "The ___ announced the new school rules at this morning's assembly.",
            quizOptions: ["principal", "principle", "principled", "principally"], quizAnswer: 0,
            quizExplanation: "principal 作名词指校长；principle 指原则，词义不符，且本句需要一个表示人的名词。"),
        VocabWord(id: "v_principle", headword: "principle", meaning: "n. 原则", tier: 1, category: .collocation,
            example: "Honesty is one of the most important principles in her life.",
            exampleMeaning: "诚实是她生活中最重要的原则之一。",
            collocations: ["in principle", "a basic principle"],
            quizStem: "Honesty is one of the most important ___ in her life.",
            quizOptions: ["principles", "principals", "principal", "principle"], quizAnswer: 0,
            quizExplanation: "principle 指抽象的原则，此处需复数形式principles；principal 指校长或主要的，与语境不符。"),
        VocabWord(id: "v_complement", headword: "complement", meaning: "vt./n. 补充，使更完美", tier: 2, category: .collocation,
            example: "The soft music perfectly complemented the calm atmosphere of the restaurant.",
            exampleMeaning: "柔和的音乐完美地衬托了餐厅平静的氛围。",
            collocations: ["complement each other", "a perfect complement to"],
            quizStem: "The soft music perfectly ___ the calm atmosphere of the restaurant.",
            quizOptions: ["complemented", "complimented", "completed", "compelled"], quizAnswer: 0,
            quizExplanation: "complement 指补充、衬托，使更完美；compliment 指赞美，发音相同但意思不同，是典型的同音混淆词。"),
        VocabWord(id: "v_compliment", headword: "compliment", meaning: "n./vt. 赞美，称赞", tier: 2, category: .collocation,
            example: "She blushed when he complimented her on her excellent presentation.",
            exampleMeaning: "他称赞她出色的演讲时，她脸红了。",
            collocations: ["compliment sb on sth", "pay sb a compliment"],
            quizStem: "She blushed when he ___ her on her excellent presentation.",
            quizOptions: ["complimented", "complemented", "completed", "compelled"], quizAnswer: 0,
            quizExplanation: "compliment sb on sth 指就某事称赞某人；complement 指补充/衬托，与称赞演讲的语境不符，是同音混淆陷阱。"),
        VocabWord(id: "v_lose", headword: "lose", meaning: "vt. 丢失，输掉", tier: 1, category: .collocation,
            example: "If you don't back up your files, you might lose all your work.",
            exampleMeaning: "如果你不备份文件，可能会丢失所有的工作成果。",
            collocations: ["lose one's way", "lose weight"],
            quizStem: "If you don't back up your files, you might ___ all your work.",
            quizOptions: ["lose", "loose", "loss", "lost"], quizAnswer: 0,
            quizExplanation: "lose 是动词丢失；loose 是形容词松的，词性不符，不能直接跟宾语work。"),
        VocabWord(id: "v_loose", headword: "loose", meaning: "adj. 松的，宽松的", tier: 1, category: .collocation,
            example: "These trousers are too loose around the waist; I need a smaller size.",
            exampleMeaning: "这条裤子腰部太松了，我需要小一号的。",
            collocations: ["a loose fit", "come loose"],
            quizStem: "These trousers are too ___ around the waist; I need a smaller size.",
            quizOptions: ["loose", "lose", "loss", "lost"], quizAnswer: 0,
            quizExplanation: "loose 是形容词松的，修饰trousers合适；lose 是动词丢失，词性和语义都不符。"),
        VocabWord(id: "v_adapt", headword: "adapt", meaning: "vi./vt. 适应；改编", tier: 1, category: .collocation,
            example: "It took her a while to adapt to the fast pace of city life.",
            exampleMeaning: "她花了一段时间才适应了城市生活的快节奏。",
            collocations: ["adapt to", "adapt a novel for the screen"],
            quizStem: "It took her a while to ___ to the fast pace of city life.",
            quizOptions: ["adapt", "adopt", "adept", "adopted"], quizAnswer: 0,
            quizExplanation: "adapt to 指适应，固定搭配；adopt 指采纳/收养，与适应城市生活节奏的语境不符。"),
        VocabWord(id: "v_adopt", headword: "adopt", meaning: "vt. 采纳，采用；收养", tier: 1, category: .collocation,
            example: "The school decided to adopt a new method of teaching grammar.",
            exampleMeaning: "学校决定采用一种新的语法教学方法。",
            collocations: ["adopt a policy", "adopt a child"],
            quizStem: "The school decided to ___ a new method of teaching grammar.",
            quizOptions: ["adopt", "adapt", "adept", "adapted"], quizAnswer: 0,
            quizExplanation: "adopt 指采纳、采用(新方法/政策)；adapt 指使适应，常与to搭配，此处语境是采用新方法，应选adopt。"),
    ]

    // MARK: 二期扩充·熟词僻义(10 → 25 词)

    static let polysemyWords2: [VocabWord] = [
        VocabWord(id: "v_match", headword: "match", meaning: "常义:n. 比赛；僻义:vt. 与……相配/匹敌", tier: 1, category: .polysemy,
            example: "No one in the class could match her speed in the 100-meter race.",
            exampleMeaning: "班里没有人能在100米赛跑中比得上她的速度。",
            collocations: ["match sb in sth", "a perfect match"],
            quizStem: "No one in the class could match her speed in the 100-meter race. \"Match\" here means ___.",
            quizOptions: ["比得上", "比赛", "火柴", "配对"], quizAnswer: 0,
            quizExplanation: "match sb in sth = 在某方面比得上某人，是动词僻义；'比赛/火柴'是名词常见义，与此处的动词位置不符。"),
        VocabWord(id: "v_company", headword: "company", meaning: "常义:n. 公司；僻义:n. 陪伴，相伴", tier: 1, category: .polysemy,
            example: "After his wife passed away, the old man's dog became his only company.",
            exampleMeaning: "妻子去世后，那只狗成了老人唯一的陪伴。",
            collocations: ["keep sb company", "in the company of"],
            quizStem: "After his wife passed away, the old man's dog became his only company. \"Company\" here means ___.",
            quizOptions: ["陪伴", "公司", "一群人", "连队"], quizAnswer: 0,
            quizExplanation: "company 在此指陪伴，是名词僻义；'公司'是更常见义，与'狗成了他唯一的……'的语境不符。"),
        VocabWord(id: "v_capital", headword: "capital", meaning: "常义:n. 首都；僻义:n. 资金/大写字母", tier: 2, category: .polysemy,
            example: "The young entrepreneur struggled to raise enough capital to launch her startup.",
            exampleMeaning: "这位年轻的企业家很难筹集到足够的资金来启动她的创业公司。",
            collocations: ["raise capital", "capital letter"],
            quizStem: "The young entrepreneur struggled to raise enough capital to launch her startup. \"Capital\" here means ___.",
            quizOptions: ["资金", "首都", "大写字母", "死刑"], quizAnswer: 0,
            quizExplanation: "raise capital = 筹集资金，是名词僻义；'首都'是常见义，与'创业筹钱'的商业语境不符。"),
        VocabWord(id: "v_interest", headword: "interest", meaning: "常义:n. 兴趣；僻义:n. 利息", tier: 1, category: .polysemy,
            example: "If you don't pay off your credit card bill, the bank will charge you interest.",
            exampleMeaning: "如果你不还清信用卡账单，银行会向你收取利息。",
            collocations: ["pay interest", "charge interest"],
            quizStem: "If you don't pay off your credit card bill, the bank will charge you interest. \"Interest\" here means ___.",
            quizOptions: ["利息", "兴趣", "利益", "关注"], quizAnswer: 0,
            quizExplanation: "charge interest = 收取利息，是金融领域的名词僻义；'兴趣'是常见义，与'信用卡账单'的语境不符。"),
        VocabWord(id: "v_fine", headword: "fine", meaning: "常义:adj. 好的/晴朗的；僻义:n./vt. 罚款", tier: 1, category: .polysemy,
            example: "Drivers who park illegally on this street will be fined fifty dollars.",
            exampleMeaning: "在这条街上违规停车的司机将被罚款五十美元。",
            collocations: ["fine sb for sth", "pay a fine"],
            quizStem: "Drivers who park illegally on this street will be fined fifty dollars. \"Fined\" here means ___.",
            quizOptions: ["罚款", "美好的", "晴朗的", "精细的"], quizAnswer: 0,
            quizExplanation: "be fined = 被罚款，是动词僻义；'美好的/晴朗的'是形容词常见义，与被动语态的结构不符。"),
        VocabWord(id: "v_count", headword: "count", meaning: "常义:v. 数数；僻义:v. 重要；count on 依靠", tier: 1, category: .polysemy,
            example: "In an emergency like this, every single second counts.",
            exampleMeaning: "在这样的紧急情况下，每一秒钟都很重要。",
            collocations: ["count on sb", "every second counts"],
            quizStem: "In an emergency like this, every single second counts. \"Counts\" here means ___.",
            quizOptions: ["很重要", "数数", "计算", "包括"], quizAnswer: 0,
            quizExplanation: "count 在此指重要、有价值，是动词僻义；'数数'是常见义，与'每一秒钟都……'强调重要性的语境不符。"),
        VocabWord(id: "v_note", headword: "note", meaning: "常义:n. 笔记；僻义:vt. 注意到/n. 纸币", tier: 1, category: .polysemy,
            example: "Please note that the museum will be closed for renovation next month.",
            exampleMeaning: "请注意，博物馆下个月将因装修而关闭。",
            collocations: ["note that...", "take note of"],
            quizStem: "Please note that the museum will be closed for renovation next month. \"Note\" here means ___.",
            quizOptions: ["注意", "做笔记", "纸币", "音符"], quizAnswer: 0,
            quizExplanation: "note that... = 注意到……，是动词僻义；'做笔记/纸币'都是名词常见义，与此处的动词位置不符。"),
        VocabWord(id: "v_plant", headword: "plant", meaning: "常义:n. 植物；僻义:n. 工厂/vt. 种植，安置", tier: 2, category: .polysemy,
            example: "The new car plant is expected to create thousands of jobs in the region.",
            exampleMeaning: "这家新汽车工厂预计将为该地区创造数千个就业机会。",
            collocations: ["a power plant", "plant trees"],
            quizStem: "The new car plant is expected to create thousands of jobs in the region. \"Plant\" here means ___.",
            quizOptions: ["工厂", "植物", "种植", "安置"], quizAnswer: 0,
            quizExplanation: "car plant = 汽车工厂，是名词僻义；'植物'是常见义，与'创造就业机会'的工业语境不符。"),
        VocabWord(id: "v_spring", headword: "spring", meaning: "常义:n. 春天；僻义:n. 泉水/vi. 弹起", tier: 2, category: .polysemy,
            example: "A small spring near the village provides clean water for the local farmers.",
            exampleMeaning: "村子附近的一条小泉为当地农民提供了干净的水源。",
            collocations: ["a hot spring", "spring up"],
            quizStem: "A small spring near the village provides clean water for the local farmers. \"Spring\" here means ___.",
            quizOptions: ["泉水", "春天", "弹簧", "跳跃"], quizAnswer: 0,
            quizExplanation: "spring 在此指泉水，是名词僻义；'春天'是常见义，与'提供干净水源'的语境不符。"),
        VocabWord(id: "v_board", headword: "board", meaning: "常义:n. 木板；僻义:n. 董事会/vt. 登(机、船、车)", tier: 2, category: .polysemy,
            example: "Passengers are kindly requested to board the aircraft through gate twelve.",
            exampleMeaning: "请乘客从十二号登机口登机。",
            collocations: ["board a plane", "room and board"],
            quizStem: "Passengers are kindly requested to board the aircraft through gate twelve. \"Board\" here means ___.",
            quizOptions: ["登上", "木板", "董事会", "包伙食"], quizAnswer: 0,
            quizExplanation: "board the aircraft = 登机，是动词僻义；'木板'是常见义，与'乘客通过登机口……飞机'的语境不符。"),
        VocabWord(id: "v_observe", headword: "observe", meaning: "常义:v. 观察；僻义:v. 遵守/评论说", tier: 2, category: .polysemy,
            example: "All visitors to the temple are expected to observe the local customs.",
            exampleMeaning: "所有参观寺庙的游客都应该遵守当地的习俗。",
            collocations: ["observe the rules", "observe that..."],
            quizStem: "All visitors to the temple are expected to observe the local customs. \"Observe\" here means ___.",
            quizOptions: ["遵守", "观察", "注意到", "庆祝"], quizAnswer: 0,
            quizExplanation: "observe the customs = 遵守习俗，是动词僻义；'观察'是常见义，与'游客应该……当地习俗'的规则语境不符。"),
        VocabWord(id: "v_appreciate", headword: "appreciate", meaning: "常义:v. 欣赏；僻义:v. 感激/意识到", tier: 1, category: .polysemy,
            example: "I would really appreciate it if you could reply to my email as soon as possible.",
            exampleMeaning: "如果你能尽快回复我的邮件，我会非常感激。",
            collocations: ["appreciate it if...", "fully appreciate"],
            quizStem: "I would really appreciate it if you could reply to my email as soon as possible. \"Appreciate\" here means ___.",
            quizOptions: ["感激", "欣赏", "增值", "理解"], quizAnswer: 0,
            quizExplanation: "would appreciate it if... = 如果……我会很感激，是礼貌句式中的僻义；'欣赏'(艺术/风景)是常见义，与请求语境不符。"),
        VocabWord(id: "v_entertain", headword: "entertain", meaning: "常义:v. 使娱乐；僻义:v. 招待/考虑(想法)", tier: 2, category: .polysemy,
            example: "The couple loves to entertain friends and family at their home every weekend.",
            exampleMeaning: "这对夫妇每个周末都喜欢在家里招待朋友和家人。",
            collocations: ["entertain guests", "entertain an idea"],
            quizStem: "The couple loves to entertain friends and family at their home every weekend. \"Entertain\" here means ___.",
            quizOptions: ["招待", "使娱乐", "考虑", "包含"], quizAnswer: 0,
            quizExplanation: "entertain friends and family = 招待朋友和家人，是动词僻义；'使娱乐'是常见义，待客语境下'招待'更准确。"),
        VocabWord(id: "v_exercise", headword: "exercise", meaning: "常义:n./v. 锻炼；僻义:vt. 运用，行使", tier: 1, category: .polysemy,
            example: "The judge urged the jury to exercise great caution before reaching a verdict.",
            exampleMeaning: "法官敦促陪审团在做出判决前要运用极大的谨慎。",
            collocations: ["exercise caution", "exercise power"],
            quizStem: "The judge urged the jury to exercise great caution before reaching a verdict. \"Exercise\" here means ___.",
            quizOptions: ["运用", "锻炼", "练习", "行使"], quizAnswer: 0,
            quizExplanation: "exercise caution = 保持/运用谨慎，是动词僻义；'锻炼身体'是常见义，与'陪审团做判决前……谨慎'的语境不符。"),
        VocabWord(id: "v_fair", headword: "fair", meaning: "常义:adj. 公平的；僻义:n. 集市，游乐场", tier: 1, category: .polysemy,
            example: "Hundreds of visitors flocked to the annual summer fair held in the town square.",
            exampleMeaning: "数百名游客涌向在镇广场举行的年度夏季集市。",
            collocations: ["a funfair", "a fair amount of"],
            quizStem: "Hundreds of visitors flocked to the annual summer fair held in the town square. \"Fair\" here means ___.",
            quizOptions: ["集市", "公平的", "金发的", "中等的"], quizAnswer: 0,
            quizExplanation: "summer fair = 夏季集市/游园会，是名词僻义；'公平的'是常见形容词义，此处fair是被held修饰的名词，词性不符。"),
    ]

    // MARK: 三期扩充·搭配辨析(20 → 30 词)

    static let collocationWords3: [VocabWord] = [
        VocabWord(id: "v_teach", headword: "teach", meaning: "vt. 教(teach sb sth / teach sb to do)", tier: 1, category: .collocation,
            example: "My grandfather taught me how to fix a bicycle when I was ten.",
            exampleMeaning: "我十岁时，爷爷教我怎么修自行车。",
            collocations: ["teach sb sth", "teach sb to do sth"],
            quizStem: "My grandfather ___ me how to fix a bicycle when I was ten.",
            quizOptions: ["taught", "learned", "learnt", "studied"], quizAnswer: 0,
            quizExplanation: "teach sb sth = 教某人某事，动作发出者是爷爷；learn 的方向是'自己学'，主语应是学习者本人，与此处主语矛盾。"),
        VocabWord(id: "v_learn", headword: "learn", meaning: "vt. 学习(learn sth from sb，方向与teach相反)", tier: 1, category: .collocation,
            example: "I learned a lot about cooking from watching my mother every evening.",
            exampleMeaning: "通过每晚看妈妈做饭，我学到了很多烹饪知识。",
            collocations: ["learn sth from sb", "learn to do sth"],
            quizStem: "I ___ a lot about cooking from watching my mother every evening.",
            quizOptions: ["learned", "taught", "informed", "instructed"], quizAnswer: 0,
            quizExplanation: "learn sth from sb = 向某人学习某事，主语'我'是学习者；teach 方向相反，是'教别人'，与'我从妈妈那……'的方向不符。"),
        VocabWord(id: "v_remember", headword: "remember", meaning: "vt. 记得(remember to do=记得要做；remember doing=记得做过)", tier: 1, category: .collocation,
            example: "Please remember to lock the door before you leave the office.",
            exampleMeaning: "离开办公室前请记得锁门。",
            collocations: ["remember to do sth", "remember doing sth"],
            quizStem: "Please ___ to lock the door before you leave the office.",
            quizOptions: ["remember", "remind", "memorize", "recall"], quizAnswer: 0,
            quizExplanation: "remember to do = 记得要做(未做的事)，主语自己记住；remind 需要接宾语(remind sb)，不能直接接 to do 表自己记得。"),
        VocabWord(id: "v_remind", headword: "remind", meaning: "vt. 提醒(remind sb of sth / remind sb to do)", tier: 1, category: .collocation,
            example: "Could you remind me to call the dentist tomorrow morning?",
            exampleMeaning: "你能提醒我明天早上给牙医打电话吗？",
            collocations: ["remind sb to do sth", "remind sb of sth"],
            quizStem: "Could you ___ me to call the dentist tomorrow morning?",
            quizOptions: ["remind", "remember", "memorize", "recall"], quizAnswer: 0,
            quizExplanation: "remind sb to do = 提醒某人做某事，必须带宾语 me；remember 是'自己记得'，不能直接接人作宾语后跟 to do。"),
        VocabWord(id: "v_win", headword: "win", meaning: "vt./vi. 赢得(比赛/奖项，宾语通常是事物)", tier: 1, category: .collocation,
            example: "Our school team won the basketball championship for the first time this year.",
            exampleMeaning: "我们学校的队伍今年第一次赢得了篮球冠军。",
            collocations: ["win a game/prize", "win against sb"],
            quizStem: "Our school team ___ the basketball championship for the first time this year.",
            quizOptions: ["won", "beat", "defeated", "lost"], quizAnswer: 0,
            quizExplanation: "win + 比赛/奖项(championship)是固定搭配；beat/defeated 后面应接'对手(人/队)'而非比赛本身，搭配对象不同。"),
        VocabWord(id: "v_beat", headword: "beat", meaning: "vt. 打败(某个对手，宾语通常是人/队)", tier: 1, category: .collocation,
            example: "The home team beat their rivals by two goals in last night's match.",
            exampleMeaning: "主队在昨晚的比赛中以两球优势击败了对手。",
            collocations: ["beat the opponent/rival", "beat sb at sth"],
            quizStem: "The home team ___ their rivals by two goals in last night's match.",
            quizOptions: ["beat", "won", "gained", "succeeded"], quizAnswer: 0,
            quizExplanation: "beat + 对手(rivals)是固定搭配，指'击败某人/队'；win 后接的应是比赛/奖项本身，不能直接接'对手'作宾语。"),
        VocabWord(id: "v_spend", headword: "spend", meaning: "vt. 花费(主语必须是人，spend time/money on sth)", tier: 1, category: .collocation,
            example: "She spends almost two hours on her English homework every evening.",
            exampleMeaning: "她每天晚上花将近两个小时做英语作业。",
            collocations: ["spend time/money on sth", "spend time doing sth"],
            quizStem: "She ___ almost two hours on her English homework every evening.",
            quizOptions: ["spends", "costs", "takes", "pays"], quizAnswer: 0,
            quizExplanation: "spend 的主语必须是人(she)，花费时间/金钱；cost 的主语应是事物(如 the trip cost...)，主语为人时不能用 cost。"),
        VocabWord(id: "v_cost", headword: "cost", meaning: "vt. 花费(主语通常是物，sth costs sb 多少)", tier: 1, category: .collocation,
            example: "Repairing the old roof cost the family nearly ten thousand yuan.",
            exampleMeaning: "修补这个旧屋顶花了这家人将近一万元。",
            collocations: ["sth costs sb money", "at the cost of"],
            quizStem: "Repairing the old roof ___ the family nearly ten thousand yuan.",
            quizOptions: ["cost", "spent", "paid", "took"], quizAnswer: 0,
            quizExplanation: "cost 的主语是事物(repairing the roof)，常接双宾语(the family + 金额)；spend 的主语应是人，此处主语是动作而非人，故不能用spent。"),
        VocabWord(id: "v_alone", headword: "alone", meaning: "adj./adv. 独自的，单独的(只描述状态，不含情感)", tier: 2, category: .collocation,
            example: "After his children moved away, he chose to live alone in the countryside.",
            exampleMeaning: "孩子们搬走后，他选择独自一人住在乡下。",
            collocations: ["live alone", "leave sb alone"],
            quizStem: "After his children moved away, he chose to live ___ in the countryside.",
            quizOptions: ["alone", "lonely", "only", "single"], quizAnswer: 0,
            quizExplanation: "live alone = 独自居住，只描述客观状态(只有一人)，不一定伴随孤独感；lonely 表主观感受'孤独的'，与'选择'独居的主动语境不太搭。"),
        VocabWord(id: "v_lonely", headword: "lonely", meaning: "adj. 孤独的，寂寞的(描述主观感受)", tier: 2, category: .collocation,
            example: "Even surrounded by classmates, she sometimes felt lonely in the new school.",
            exampleMeaning: "即使周围都是同学，她在新学校里有时还是感到孤独。",
            collocations: ["feel lonely", "a lonely figure"],
            quizStem: "Even surrounded by classmates, she sometimes felt ___ in the new school.",
            quizOptions: ["lonely", "alone", "only", "single"], quizAnswer: 0,
            quizExplanation: "feel lonely = 感到孤独，强调主观情感；alone 只表示客观上'独自一人'，与'即使周围都是同学却……'的情感反差不符。"),
        VocabWord(id: "v_quite", headword: "quite", meaning: "adv. 相当，十分", tier: 1, category: .collocation,
            example: "The math test today was quite difficult for most of the students.",
            exampleMeaning: "今天的数学考试对大多数学生来说相当难。",
            collocations: ["quite difficult", "quite a few"],
            quizStem: "The math test today was ___ difficult for most of the students.",
            quizOptions: ["quite", "quiet", "rather", "quit"], quizAnswer: 0,
            quizExplanation: "quite 是副词'相当'，修饰形容词 difficult；quiet 是形容词'安静的'，词性不符，是典型的拼写形近混淆。"),
        VocabWord(id: "v_quiet", headword: "quiet", meaning: "adj. 安静的", tier: 1, category: .collocation,
            example: "The library remained quiet even during the busiest exam week.",
            exampleMeaning: "即使在考试最繁忙的一周，图书馆依然很安静。",
            collocations: ["keep quiet", "a quiet place"],
            quizStem: "The library remained ___ even during the busiest exam week.",
            quizOptions: ["quiet", "quite", "quit", "quietly"], quizAnswer: 0,
            quizExplanation: "remain + 形容词，quiet(安静的)作补语；quite 是副词'相当'，不能直接作 remain 的补语，词性不符。"),
        VocabWord(id: "v_effective", headword: "effective", meaning: "adj. 有效的(强调效果好)", tier: 2, category: .collocation,
            example: "Regular exercise is one of the most effective ways to reduce stress.",
            exampleMeaning: "规律运动是缓解压力最有效的方式之一。",
            collocations: ["an effective method", "effective communication"],
            quizStem: "Regular exercise is one of the most ___ ways to reduce stress.",
            quizOptions: ["effective", "efficient", "effected", "effecting"], quizAnswer: 0,
            quizExplanation: "effective 强调'效果好、奏效'，修饰 ways(方法)恰当；efficient 强调'省时省力、高效率'，侧重过程而非效果本身。"),
        VocabWord(id: "v_efficient", headword: "efficient", meaning: "adj. 高效的(强调省时省力，效率高)", tier: 2, category: .collocation,
            example: "The new sorting system makes the whole factory far more efficient.",
            exampleMeaning: "新的分拣系统让整个工厂的效率大大提高。",
            collocations: ["an efficient system", "energy-efficient"],
            quizStem: "The new sorting system makes the whole factory far more ___.",
            quizOptions: ["efficient", "effective", "effected", "effecting"], quizAnswer: 0,
            quizExplanation: "efficient 强调'省时省力、效率高'，描述系统运转的方式；effective 强调'结果有效'，此处讲的是运作效率而非单纯结果，故选efficient。"),
        VocabWord(id: "v_respectful", headword: "respectful", meaning: "adj. 表示尊重的(指人的态度)", tier: 2, category: .collocation,
            example: "The students listened in a respectful silence as the veteran shared his story.",
            exampleMeaning: "老兵讲述他的故事时，学生们怀着尊重静静聆听。",
            collocations: ["respectful of/to sb", "a respectful manner"],
            quizStem: "The students listened in a ___ silence as the veteran shared his story.",
            quizOptions: ["respectful", "respectable", "respective", "respected"], quizAnswer: 0,
            quizExplanation: "respectful 指'表示尊重的态度'，修饰silence恰当；respectable 指'值得尊敬的(品质)'，描述对象不是态度而是人/事物本身。"),
        VocabWord(id: "v_respectable", headword: "respectable", meaning: "adj. 值得尊敬的(指人或事物本身的品质)", tier: 2, category: .collocation,
            example: "Her grandfather was a respectable doctor known throughout the small town.",
            exampleMeaning: "她的祖父是一位在这个小镇上家喻户晓、令人尊敬的医生。",
            collocations: ["a respectable career", "respectable behavior"],
            quizStem: "Her grandfather was a ___ doctor known throughout the small town.",
            quizOptions: ["respectable", "respectful", "respective", "disrespectful"], quizAnswer: 0,
            quizExplanation: "respectable 指'本身值得尊敬的'，修饰doctor(身份)恰当；respectful 指'对别人表示尊重的态度'，与描述医生本人的身份地位不符。"),
        VocabWord(id: "v_industrial", headword: "industrial", meaning: "adj. 工业的", tier: 2, category: .collocation,
            example: "The city used to be a major industrial center known for its steel production.",
            exampleMeaning: "这座城市曾是以钢铁生产闻名的重要工业中心。",
            collocations: ["industrial area", "industrial production"],
            quizStem: "The city used to be a major ___ center known for its steel production.",
            quizOptions: ["industrial", "industrious", "industry", "industrialized"], quizAnswer: 0,
            quizExplanation: "industrial center(工业中心)是固定搭配；industrious 指人'勤劳的'，不能用来修饰一座城市的产业性质。"),
        VocabWord(id: "v_industrious", headword: "industrious", meaning: "adj. 勤劳的(指人)", tier: 2, category: .collocation,
            example: "The farmers in this region are known for being industrious and hardworking.",
            exampleMeaning: "这个地区的农民以勤劳能干著称。",
            collocations: ["an industrious worker", "industrious by nature"],
            quizStem: "The farmers in this region are known for being ___ and hardworking.",
            quizOptions: ["industrious", "industrial", "industry", "industrialized"], quizAnswer: 0,
            quizExplanation: "industrious 指人'勤劳的'，与 hardworking 并列修饰farmers恰当；industrial 指'工业的'，不能用来描述人的品质。"),
        VocabWord(id: "v_comfortable", headword: "comfortable", meaning: "adj. 舒适的(描述物或感受本身舒适)", tier: 1, category: .collocation,
            example: "The new mattress is so comfortable that I fall asleep within minutes.",
            exampleMeaning: "新床垫太舒适了，我几分钟就能睡着。",
            collocations: ["a comfortable bed/chair", "feel comfortable"],
            quizStem: "The new mattress is so ___ that I fall asleep within minutes.",
            quizOptions: ["comfortable", "comforting", "comforted", "comfort"], quizAnswer: 0,
            quizExplanation: "comfortable 指事物本身'舒适的'，修饰mattress恰当；comforting 指'令人感到安慰的'，强调情感安抚而非物理舒适度。"),
        VocabWord(id: "v_comforting", headword: "comforting", meaning: "adj. 令人感到安慰的(side指情感上的慰藉)", tier: 1, category: .collocation,
            example: "It was comforting to know that my friends would always support me.",
            exampleMeaning: "知道朋友们会一直支持我，这让人感到安慰。",
            collocations: ["comforting words", "find it comforting"],
            quizStem: "It was ___ to know that my friends would always support me.",
            quizOptions: ["comforting", "comfortable", "comforted", "comfort"], quizAnswer: 0,
            quizExplanation: "comforting 指'让人感到安慰的'，修饰整件事(知道朋友支持)带来的情感效果；comfortable 指物理上的舒适，与本句的情感安慰语境不符。"),
    ]

    // MARK: 三期扩充·熟词僻义(25 → 45 词)

    static let polysemyWords3: [VocabWord] = [
        VocabWord(id: "v_mind", headword: "mind", meaning: "常义:n. 头脑，思维；僻义:vt. 介意", tier: 1, category: .polysemy,
            example: "Would you mind turning down the music a little? I'm trying to study.",
            exampleMeaning: "你介意把音乐声调小一点吗？我在学习。",
            collocations: ["would you mind doing", "make up one's mind"],
            quizStem: "Would you mind turning down the music a little? I'm trying to study. \"Mind\" here means ___.",
            quizOptions: ["介意", "头脑", "记住", "照顾"], quizAnswer: 0,
            quizExplanation: "would you mind doing = 你介意做……吗，是动词僻义，礼貌请求句型；'头脑'是常见名词义，与此处的动词位置不符。"),
        VocabWord(id: "v_story", headword: "story", meaning: "常义:n. 故事；僻义:n. (楼房的)层", tier: 2, category: .polysemy,
            example: "The new library building has six stories and a rooftop reading garden.",
            exampleMeaning: "新图书馆大楼有六层，楼顶还有一个阅读花园。",
            collocations: ["a ten-story building", "tell a story"],
            quizStem: "The new library building has six stories and a rooftop reading garden. \"Stories\" here means ___.",
            quizOptions: ["楼层", "故事", "经历", "新闻报道"], quizAnswer: 0,
            quizExplanation: "six stories = 六层楼，是名词僻义，常与building/楼层数搭配；'故事'是常见义，与'楼顶花园'的建筑语境不符。"),
        VocabWord(id: "v_ground", headword: "ground", meaning: "常义:n. 地面；僻义:n. 理由，根据(on the grounds that)", tier: 2, category: .polysemy,
            example: "The committee rejected his application on the grounds that he had missed the deadline.",
            exampleMeaning: "委员会以他错过截止日期为理由拒绝了他的申请。",
            collocations: ["on the grounds that", "well-grounded"],
            quizStem: "The committee rejected his application on the grounds that he had missed the deadline. \"Grounds\" here means ___.",
            quizOptions: ["理由", "地面", "场地", "基础"], quizAnswer: 0,
            quizExplanation: "on the grounds that = 以……为理由，是名词僻义的固定搭配；'地面'是常见义，与'拒绝申请的理由'语境不符。"),
        VocabWord(id: "v_season", headword: "season", meaning: "常义:n. 季节；僻义:vt. 给…调味", tier: 2, category: .polysemy,
            example: "Chefs usually season the soup with a little salt and pepper just before serving.",
            exampleMeaning: "厨师通常在上菜前用一点盐和胡椒给汤调味。",
            collocations: ["season sth with sth", "seasoned with experience"],
            quizStem: "Chefs usually season the soup with a little salt and pepper just before serving. \"Season\" here means ___.",
            quizOptions: ["给…调味", "季节", "腌制", "成熟"], quizAnswer: 0,
            quizExplanation: "season the soup = 给汤调味，是动词僻义；'季节'是常见名词义，此处season后直接接宾语soup，词性是动词。"),
        VocabWord(id: "v_case", headword: "case", meaning: "常义:n. 情况，箱子；僻义:in case 以防；n. 病例/案例", tier: 1, category: .polysemy,
            example: "Take an umbrella with you in case it rains later this afternoon.",
            exampleMeaning: "带把雨伞，以防今天下午晚些时候下雨。",
            collocations: ["in case", "in case of"],
            quizStem: "Take an umbrella with you in case it rains later this afternoon. \"In case\" here means ___.",
            quizOptions: ["以防", "假设", "因为", "即使"], quizAnswer: 0,
            quizExplanation: "in case = 以防，引导目的状语，是固定短语的僻义用法；与'因为/即使'等逻辑关系词意思不同，不能混用。"),
        VocabWord(id: "v_terms", headword: "terms", meaning: "常义:n. 学期/术语；僻义:terms(pl.) 关系；条款", tier: 2, category: .polysemy,
            example: "Despite their argument last year, the two brothers are now on good terms again.",
            exampleMeaning: "尽管去年吵过架，这两兄弟现在关系又变好了。",
            collocations: ["on good terms with sb", "come to terms with"],
            quizStem: "Despite their argument last year, the two brothers are now on good terms again. \"Terms\" here means ___.",
            quizOptions: ["关系", "学期", "术语", "条款"], quizAnswer: 0,
            quizExplanation: "on good terms with sb = 与某人关系好，是名词僻义固定搭配；'学期/术语'是常见义，与'兄弟关系'的语境不符。"),
        VocabWord(id: "v_credit", headword: "credit", meaning: "常义:n. 信用；僻义:vt. 把…归功于(credit sb with sth)", tier: 2, category: .polysemy,
            example: "Many fans credit the coach with turning the losing team into champions.",
            exampleMeaning: "许多球迷认为，是教练把这支败队变成了冠军队。",
            collocations: ["credit sb with sth", "give sb credit for"],
            quizStem: "Many fans credit the coach with turning the losing team into champions. \"Credit\" here means ___.",
            quizOptions: ["把…归功于", "信用", "学分", "贷方"], quizAnswer: 0,
            quizExplanation: "credit sb with sth = 把…归功于某人，是动词僻义固定搭配；'信用/学分'是常见名词义，与此处动词位置不符。"),
        VocabWord(id: "v_ruler", headword: "ruler", meaning: "常义:n. 尺子；僻义:n. 统治者", tier: 2, category: .polysemy,
            example: "The ancient ruler was remembered for building roads that connected the whole empire.",
            exampleMeaning: "这位古代统治者因修建连接整个帝国的道路而被人们铭记。",
            collocations: ["a wise ruler", "rule over"],
            quizStem: "The ancient ruler was remembered for building roads that connected the whole empire. \"Ruler\" here means ___.",
            quizOptions: ["统治者", "尺子", "管理员", "法官"], quizAnswer: 0,
            quizExplanation: "ruler 在此指统治者(治理帝国的人)，是名词僻义；'尺子'是常见义，与'修建连接帝国的道路'的历史语境不符。"),
        VocabWord(id: "v_quarter", headword: "quarter", meaning: "常义:n. 四分之一；僻义:n. (城市的)区域，街区", tier: 2, category: .polysemy,
            example: "Tourists love wandering through the old quarter with its narrow stone streets.",
            exampleMeaning: "游客喜欢在那些石板窄街的老城区里漫步。",
            collocations: ["the old quarter", "a quarter of an hour"],
            quizStem: "Tourists love wandering through the old quarter with its narrow stone streets. \"Quarter\" here means ___.",
            quizOptions: ["街区", "四分之一", "一刻钟", "季度"], quizAnswer: 0,
            quizExplanation: "the old quarter = 老城区，是名词僻义，指城市中的一个区域；'四分之一'是常见义，与'石板窄街'的地理语境不符。"),
        VocabWord(id: "v_degree", headword: "degree", meaning: "常义:n. 程度；僻义:n. 学位；度(温度)", tier: 1, category: .polysemy,
            example: "After finishing her degree in engineering, she joined a renewable energy company.",
            exampleMeaning: "完成工程学学位后，她加入了一家可再生能源公司。",
            collocations: ["a degree in sth", "to some degree"],
            quizStem: "After finishing her degree in engineering, she joined a renewable energy company. \"Degree\" here means ___.",
            quizOptions: ["学位", "程度", "温度", "学分"], quizAnswer: 0,
            quizExplanation: "a degree in engineering = 工程学学位，是名词僻义；'程度'(to some degree)是常见用法，但此处搭配'in+学科'明显指学位。"),
        VocabWord(id: "v_stress", headword: "stress", meaning: "常义:n. 压力；僻义:vt. 强调(stress that...)", tier: 1, category: .polysemy,
            example: "The doctor stressed that getting enough sleep is just as important as eating well.",
            exampleMeaning: "医生强调，充足的睡眠和健康饮食一样重要。",
            collocations: ["stress that...", "under stress"],
            quizStem: "The doctor stressed that getting enough sleep is just as important as eating well. \"Stressed\" here means ___.",
            quizOptions: ["强调", "施加压力于", "使紧张", "重读"], quizAnswer: 0,
            quizExplanation: "stress that... = 强调……，是动词僻义；'压力'是常见名词义，此处stressed是动词且接that从句，应理解为'强调'。"),
        VocabWord(id: "v_issue", headword: "issue", meaning: "常义:n. 问题，议题；僻义:vt. 发布，发行", tier: 1, category: .polysemy,
            example: "The government issued a statement promising to fix the water shortage by next year.",
            exampleMeaning: "政府发布了一份声明，承诺明年解决缺水问题。",
            collocations: ["issue a statement", "raise an issue"],
            quizStem: "The government issued a statement promising to fix the water shortage by next year. \"Issued\" here means ___.",
            quizOptions: ["发布", "讨论", "解决", "忽视"], quizAnswer: 0,
            quizExplanation: "issue a statement = 发布声明，是动词僻义；'问题/议题'是常见名词义，此处issued是动词，接宾语statement，意为'发布'。"),
        VocabWord(id: "v_minute", headword: "minute", meaning: "常义:n. 分钟；僻义:adj. 极小的(发音不同 /maɪˈnjuːt/)", tier: 2, category: .polysemy,
            example: "Under the microscope, they could see minute particles floating in the water sample.",
            exampleMeaning: "在显微镜下，他们能看到水样中漂浮着极其微小的颗粒。",
            collocations: ["minute details", "a minute amount of"],
            quizStem: "Under the microscope, they could see minute particles floating in the water sample. \"Minute\" here means ___.",
            quizOptions: ["极小的", "一分钟", "会议记录", "刚才的"], quizAnswer: 0,
            quizExplanation: "minute 在此读 /maɪˈnjuːt/，意为'极小的'，修饰particles；'分钟'是更常见的义项(读/ˈmɪnɪt/)，但与显微镜下的语境及形容词位置不符。"),
        VocabWord(id: "v_scale", headword: "scale", meaning: "常义:n. 规模，刻度；僻义:vt. 攀登", tier: 2, category: .polysemy,
            example: "The climbers scaled the steep cliff using only ropes and their bare hands.",
            exampleMeaning: "登山者只用绳索和双手就攀上了那座陡峭的悬崖。",
            collocations: ["scale a wall/cliff", "on a large scale"],
            quizStem: "The climbers scaled the steep cliff using only ropes and their bare hands. \"Scaled\" here means ___.",
            quizOptions: ["攀登", "测量", "缩减", "称重"], quizAnswer: 0,
            quizExplanation: "scale the cliff = 攀登悬崖，是动词僻义；'规模/刻度'是常见名词义，此处scaled是动词且接宾语cliff，意为'攀登'。"),
        VocabWord(id: "v_report", headword: "report", meaning: "常义:n. 报告；僻义:vi. 报到，汇报(report to sb)", tier: 1, category: .polysemy,
            example: "All new employees are asked to report to the front desk at nine sharp.",
            exampleMeaning: "所有新员工都被要求九点准时到前台报到。",
            collocations: ["report to sb", "report for duty"],
            quizStem: "All new employees are asked to report to the front desk at nine sharp. \"Report\" here means ___.",
            quizOptions: ["报到", "报告", "报道", "举报"], quizAnswer: 0,
            quizExplanation: "report to the front desk = 到前台报到，是动词僻义固定搭配；'报告'是常见名词义，此处report是动词，意为'报到'。"),
        VocabWord(id: "v_yield", headword: "yield", meaning: "常义:n. 产量；僻义:vi. 让步，屈服(yield to)", tier: 2, category: .polysemy,
            example: "After hours of debate, the committee finally yielded to public pressure and changed the plan.",
            exampleMeaning: "经过数小时的辩论，委员会最终向公众压力让步，改变了计划。",
            collocations: ["yield to sth", "crop yield"],
            quizStem: "After hours of debate, the committee finally yielded to public pressure and changed the plan. \"Yielded\" here means ___.",
            quizOptions: ["让步", "产出", "屈服于诱惑", "放弃所有权"], quizAnswer: 0,
            quizExplanation: "yield to pressure = 向压力让步，是动词僻义固定搭配；'产量'是常见名词义，此处yielded是动词，接to结构，意为'让步'。"),
        VocabWord(id: "v_drill", headword: "drill", meaning: "常义:n. 钻头；僻义:n./v. (反复)操练，训练", tier: 2, category: .polysemy,
            example: "The whole school took part in a fire drill on Monday morning.",
            exampleMeaning: "周一早上，全校都参加了一次消防演习。",
            collocations: ["a fire drill", "drill students in grammar"],
            quizStem: "The whole school took part in a fire drill on Monday morning. \"Drill\" here means ___.",
            quizOptions: ["演习，训练", "钻头", "钻孔", "纪律"], quizAnswer: 0,
            quizExplanation: "a fire drill = 消防演习，是名词僻义；'钻头'是常见义，与'全校参加……'的安全演练语境不符。"),
        VocabWord(id: "v_counter", headword: "counter", meaning: "常义:n. 柜台；僻义:vt. 反驳，反击", tier: 2, category: .polysemy,
            example: "The lawyer quickly countered the argument with new evidence from the case file.",
            exampleMeaning: "律师很快用案件档案中的新证据反驳了这一论点。",
            collocations: ["counter an argument", "over the counter"],
            quizStem: "The lawyer quickly countered the argument with new evidence from the case file. \"Countered\" here means ___.",
            quizOptions: ["反驳", "结账", "抵消", "计数"], quizAnswer: 0,
            quizExplanation: "counter the argument = 反驳论点，是动词僻义；'柜台'是常见名词义，此处countered是动词且接宾语argument，意为'反驳'。"),
        VocabWord(id: "v_tender", headword: "tender", meaning: "常义:adj. 温柔的，嫩的；僻义:vt. 提出，递交", tier: 2, category: .polysemy,
            example: "The minister tendered his resignation after the scandal was made public.",
            exampleMeaning: "丑闻公开后，这位部长递交了辞职信。",
            collocations: ["tender one's resignation", "a tender voice"],
            quizStem: "The minister tendered his resignation after the scandal was made public. \"Tendered\" here means ___.",
            quizOptions: ["递交", "使温柔", "使变嫩", "投标"], quizAnswer: 0,
            quizExplanation: "tender one's resignation = 递交辞呈，是动词僻义固定搭配；'温柔的/嫩的'是常见形容词义，此处tendered是动词，意为'递交'。"),
        VocabWord(id: "v_file", headword: "file", meaning: "常义:n. 文件；僻义:vi. 排队前进(file in/out)", tier: 2, category: .polysemy,
            example: "When the bell rang, the students filed quietly into the exam hall.",
            exampleMeaning: "铃声响起后，学生们安静地排队走进了考场。",
            collocations: ["file in/out", "file a complaint"],
            quizStem: "When the bell rang, the students filed quietly into the exam hall. \"Filed\" here means ___.",
            quizOptions: ["排队前进", "把…归档", "磨锉", "提交申请"], quizAnswer: 0,
            quizExplanation: "file into the hall = 排队走进大厅，是动词僻义；'文件'是常见名词义，此处filed是动词，描述学生有序进入的动作。"),
    ]
}
